[general]
enabled = yes
pretty = yes
allowed_origins = https://fax.karabuk.edu.tr,https://127.0.0.1
[admin]
type = user
read_only = yes
password = 3278073d60943c8d8b87624834f428c6
password_format = plain
