[modules]
autoload=yes
preload = res_odbc.so
preload = res_config_odbc.so

; Disable unused channel drivers & legacy modules
noload = chan_sip.so
noload = chan_dahdi.so
noload = chan_skinny.so
noload = chan_mgcp.so
noload = chan_ooh323.so
noload = chan_unistim.so
noload = chan_mobile.so
noload = chan_alsa.so
noload = chan_oss.so
noload = chan_iax2.so
noload = chan_motif.so

; Disable unused database drivers & legacy MySQL/LDAP connectors
noload = cdr_mysql.so
noload = app_mysql.so
noload = res_config_mysql.so
noload = res_config_ldap.so
noload = func_odbc.so

; Disable unused reporting, CSV, RADIUS & SQLite drivers
noload = cel_custom.so
noload = cdr_custom.so
noload = cel_tds.so
noload = cel_pgsql.so
noload = cdr_tds.so
noload = cdr_pgsql.so
noload = cdr_syslog.so
noload = cdr_radius.so
noload = cel_radius.so
noload = cdr_sqlite3_custom.so
noload = cel_sqlite3_custom.so

; Disable unused voicemail, DAHDI timing, provisioning & deprecated modules
noload = res_phoneprov.so
noload = res_pjsip_phoneprov_provider.so
noload = app_minivm.so
noload = res_timing_dahdi.so
noload = app_dahdiras.so
noload = res_pktccops.so
noload = res_parking.so
noload = app_festival.so
noload = pbx_lua.so
noload = pbx_ael.so
noload = res_xmpp.so
noload = res_hep.so
noload = res_hep_pjsip.so
noload = res_hep_rtcp.so
noload = app_getcpeid.so
noload = app_image.so
noload = app_url.so
noload = res_speech_vosk.so
noload = app_meetme.so
noload = res_adsi.so
noload = app_adsiprog.so
noload = res_monitor.so
noload = app_nbscat.so
noload = app_ices.so

; Disable incompatible legacy codec files
noload = codec_g729_asterisk11.so
noload = codec_g729_asterisk13.so
noload = codec_g729_asterisk16.so
