[general]
enabled => yes
max_connections => 20

[asterisk]
enabled => yes
dsn => asterisk
username => asterisk_odbc
; password is dynamically set from /etc/ai-pbx.env
password => ${ODBC_PASS}
pre-connect => yes
max_connections => 10
sanitycheck => 30
