[general]
enabled => yes
max_connections => 20

[asterisk]
enabled => yes
dsn => asterisk
username => asterisk_odbc
password => f1131152d36385a46024a909cd60998b
pre-connect => yes
max_connections => 10
sanitycheck => 30
