<?php
/**
 * Website call widgets (/etc/asterisk/pbx/pjsip_widgets.conf and
 * /etc/asterisk/pbx/extensions_widgets.conf), see WebWidgetService.
 *
 * Per active widget <id>:
 *  - PJSIP endpoint widget-<id> (WebRTC, no registration). Its context is
 *    [widget-<id>], which holds nothing but the token check: the browser
 *    dials w<token>, bin/widget_claim.php spends the token, and only then
 *    does the call go on to [widget-<id>-route].
 *  - [widget-<id>-route]: concurrent-call limit (GROUP_COUNT), maximum call
 *    length (TIMEOUT(absolute)), CDR fields (the widget number as the DID,
 *    widget-<id> as the inbound trunk) and the destination.
 *  - Call-back: [widget-<id>-out] dials the visitor through the widget's
 *    outbound route (the Local leg of the call file); when they answer, the
 *    call file continues in [widget-<id>-callback], which routes them like a
 *    widget call.
 * The -route, -out and -callback contexts are not reachable from the
 * endpoint: it can only enter [widget-<id>].
 */

function syncWidgets() {
    return withSyncLock('widgets', '__syncWidgetsBody');
}

function __syncWidgetsBody() {
    // Loaded here, not at the top: the service itself requires asterisk_sync.php.
    require_once dirname(__DIR__) . '/services/WebWidgetService.php';
    $widgets = getDB()->query('SELECT * FROM pbx_web_widgets WHERE is_active = 1 ORDER BY id ASC')->fetchAll(PDO::FETCH_ASSOC);

    writeConfWithRollback('pjsip_widgets.conf', buildWidgetPjsipConf($widgets), function () {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadPJSIP()], t('sync.ctx_widgets'));
    }, t('sync.ctx_widgets'));

    return writeConfWithRollback('extensions_widgets.conf', buildWidgetDialplan($widgets), function () {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], t('sync.ctx_widgets'));
    }, t('sync.ctx_widgets'));
}

/** @param array<int, array> $widgets active widgets */
function buildWidgetPjsipConf(array $widgets): string {
    $codecs = getSystemSetting('pjsip_codecs', 'opus,ulaw,alaw,g722');
    $directMedia = getSystemSetting('pjsip_direct_media', 'no');
    $rtpSymmetric = getSystemSetting('pjsip_rtp_symmetric', 'yes');

    $conf = "; ==========================================================\n";
    $conf .= "; Website call widgets (Auto-generated by AI PBX)\n";
    $conf .= "; ==========================================================\n\n";

    foreach ($widgets as $w) {
        $id = (int) $w['id'];
        $name = toCleanAscii((string) $w['name']);
        $number = preg_replace('/[^0-9]/', '', (string) $w['number']);
        $secret = preg_replace('/[^0-9a-f]/', '', (string) $w['sip_secret']);

        // The same WebRTC settings as the web phone's endpoint-wss template,
        // written out in full so this file does not depend on another file's
        // templates.
        $conf .= "; Widget {$id}: {$name} ({$number})\n";
        $conf .= "[widget-{$id}]\n";
        $conf .= "type=endpoint\n";
        $conf .= "context=widget-{$id}\n";
        $conf .= "auth=widget-{$id}-auth\n";
        $conf .= "callerid=\"Web widget\" <{$number}>\n";
        $conf .= "disallow=all\n";
        $conf .= "allow={$codecs}\n";
        $conf .= "transport=transport-ws\n";
        $conf .= "identify_by=auth_username,username\n";
        $conf .= "dtmf_mode=rfc4733\n";
        $conf .= "rtp_timeout=30\n";
        $conf .= "rtp_timeout_hold=300\n";
        $conf .= "webrtc=yes\n";
        $conf .= "rtcp_mux=yes\n";
        $conf .= "direct_media={$directMedia}\n";
        $conf .= "media_use_received_transport=yes\n";
        $conf .= "ice_support=yes\n";
        $conf .= "use_avpf=yes\n";
        $conf .= "media_encryption=dtls\n";
        $conf .= "dtls_verify=fingerprint\n";
        $conf .= "dtls_setup=actpass\n";
        $conf .= "dtls_cert_file=" . PJSIP_DTLS_CERT . "\n";
        $conf .= "dtls_ca_file=" . PJSIP_DTLS_CERT . "\n";
        $conf .= "rtp_symmetric={$rtpSymmetric}\n";
        $conf .= "rewrite_contact=yes\n";
        $conf .= "force_rport=yes\n\n";

        $conf .= "[widget-{$id}-auth]\n";
        $conf .= "type=auth\n";
        $conf .= "auth_type=userpass\n";
        $conf .= "username=widget-{$id}\n";
        $conf .= "password={$secret}\n\n";
    }

    if ($widgets === []) {
        $conf .= "; No active widgets\n";
    }
    return $conf;
}

/** @param array<int, array> $widgets active widgets */
function buildWidgetDialplan(array $widgets): string {
    require_once dirname(__DIR__) . '/services/WebWidgetService.php';
    $conf = "; ==========================================================\n";
    $conf .= "; Website call widgets (Auto-generated by AI PBX)\n";
    $conf .= "; ==========================================================\n\n";

    foreach ($widgets as $w) {
        $id = (int) $w['id'];
        $name = WebWidgetService::dialplanName((string) $w['name']) ?: "Widget {$id}";
        $number = preg_replace('/[^0-9]/', '', (string) $w['number']);
        $max = max(1, (int) $w['max_concurrent']);
        $seconds = max(60, (int) $w['max_call_seconds']);
        $routeId = (int) ($w['outbound_route_id'] ?? 0);
        $outsideCid = preg_replace('/[^0-9]/', '', WebWidgetService::outsideCallerId($w));

        $conf .= "; --- Widget {$id}: {$name} ({$number}) ---\n";

        // 1. Entry from the browser: only a valid one-time token gets through.
        if ((int) $w['call_enabled'] === 1) {
            $conf .= "[widget-{$id}]\n";
            $conf .= "exten => _w.,1,NoOp(Web widget {$id}: browser call)\n";
            $conf .= " same => n,Set(WIDGET_RES=\${SHELL(/usr/local/bin/widget_claim.php {$id} \${FILTER(0-9a-f,\${EXTEN:1})})})\n";
            $conf .= " same => n,GotoIf(\$[\"\${CUT(WIDGET_RES,|,1)}\" != \"OK\"]?deny)\n";
            $conf .= " same => n,Set(CALLERID(num)={$number})\n";
            $conf .= " same => n,Set(CALLERID(name)=\${IF(\$[\"\${CUT(WIDGET_RES,|,2)}\" != \"\"]?\${CUT(WIDGET_RES,|,2)}:{$name})})\n";
            $conf .= " same => n,Goto(widget-{$id}-route,s,1)\n";
            $conf .= " same => n(deny),NoOp(Web widget {$id}: refused \${WIDGET_RES})\n";
            $conf .= " same => n,Hangup(21)\n\n";
        } else {
            $conf .= "[widget-{$id}]\n";
            $conf .= "exten => _w.,1,Hangup(21)\n\n";
        }

        // 2. Routing shared by browser calls and answered call-backs.
        $conf .= "[widget-{$id}-route]\n";
        $conf .= "exten => s,1,NoOp(Web widget {$id}: {$name})\n";
        $conf .= " same => n,Set(GROUP(aipbx_widget)=w{$id})\n";
        $conf .= " same => n,GotoIf(\$[\${GROUP_COUNT(w{$id}@aipbx_widget)} > {$max}]?widget_busy)\n";
        $conf .= " same => n,Set(TIMEOUT(absolute)={$seconds})\n";
        $conf .= " same => n,Set(CDR(direction)=inbound)\n";
        $conf .= " same => n,Set(CDR(inbound_trunk)=widget-{$id})\n";
        $conf .= " same => n,Set(CDR(did)={$number})\n";
        if ($w['dest_type'] === 'external') {
            // An outside party sees the company's number, never what the
            // visitor typed (the outbound route keeps CALLERID(num) when
            // CDR(inbound_trunk) is set, as for transit calls).
            $external = preg_replace('/[^0-9]/', '', (string) $w['external_number']);
            $conf .= " same => n,Set(CALLERID(num)={$outsideCid})\n";
            $conf .= buildDestinationLines('outbound_route', (string) $routeId, $external) . "\n";
        } else {
            $conf .= buildDestinationLines((string) $w['dest_type'], (string) $w['dest_id'], $number) . "\n";
        }
        $conf .= " same => n,Hangup()\n";
        $conf .= " same => n(widget_busy),NoOp(Web widget {$id}: {$max} calls already)\n";
        $conf .= " same => n,Busy(10)\n\n";

        // 3. Call-back: the Local leg dials the visitor, the call file goes on
        //    in -callback once they answer.
        if ((int) $w['callback_enabled'] === 1 && $routeId > 0) {
            $conf .= "[widget-{$id}-out]\n";
            $conf .= "exten => _X.,1,NoOp(Web widget {$id}: calling back \${EXTEN})\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Set(CALLERID(num)={$outsideCid})\n";
            $conf .= " same => n,Set(__CID_EXTERNAL={$outsideCid})\n";
            $conf .= " same => n,Goto(outbound-route-{$routeId},\${EXTEN},1)\n\n";

            $conf .= "[widget-{$id}-callback]\n";
            $conf .= "exten => _X.,1,NoOp(Web widget {$id}: call-back answered by \${EXTEN})\n";
            $conf .= " same => n,Set(CALLERID(num)=\${EXTEN})\n";
            $conf .= " same => n,Set(CALLERID(name)=\${IF(\$[\"\${WIDGET_CB_NAME}\" != \"\"]?\${WIDGET_CB_NAME}:{$name})})\n";
            $conf .= " same => n,Goto(widget-{$id}-route,s,1)\n\n";
        }
    }

    if ($widgets === []) {
        $conf .= "; No active widgets\n";
    }
    return $conf;
}
