<?php
/**
 * RTP Ayarları Senkronizasyonu (/etc/asterisk/rtp.conf)
 *
 * Diğer üreteçlerden İKİ farkı var:
 *
 * 1) Hedef dosya `pbx/` alt dizininde DEĞİL, doğrudan /etc/asterisk altında.
 *    Bu yüzden writePBXConf()/writeConfWithRollback() kullanılamıyor (onlar
 *    ASTERISK_PBX_DIR'e yazıyor); geri alma mantığı burada elle kuruldu.
 *
 * 2) Dosyayı BİZ tamamen üretiyoruz. Daha önce elle yönetiliyordu; portale
 *    taşındıktan sonra elle yapılan düzenlemeler bir sonraki Uygula'da
 *    kaybolur — dosyanın başındaki uyarı bunu söylüyor.
 *
 * NOT: reload `strictrtp`i devreye alır ama port ARALIĞI değişikliği tam
 * Asterisk restart'ı ister (bkz. AsteriskHelper::reloadRTP).
 */

const RTP_CONF_PATH = '/etc/asterisk/rtp.conf';

function syncRtpSettings()
{
    return withSyncLock('rtp', '__syncRtpSettingsBody');
}

/**
 * rtp.conf icerigini uretir — saf fonksiyon: diske YAZMAZ, reload ETMEZ.
 * RTP_CONF_PATH sabit ve canli /etc/asterisk/rtp.conf'u gosterdigi icin
 * __syncRtpSettingsBody() birim testinden cagrilamaz; uretim mantigi
 * buraya ayrildi ki test edilebilsin (ayni desen:
 * buildInternalNumbersConf, buildIVRDialplanBlock).
 */
function buildRtpConf(): string
{
    $start  = (int) getSystemSetting('rtp_start', '10000');
    $end    = (int) getSystemSetting('rtp_end', '12999');
    $strict = getSystemSetting('rtp_strict', 'yes') === 'no' ? 'no' : 'yes';

    // Servis katmanı zaten doğruluyor; burası son savunma hattı — DB'ye başka
    // bir yoldan bozuk değer girerse Asterisk'in RTP'si tamamen çalışmaz hale
    // gelebilirdi.
    if ($start < 1024 || $start > 65535 || $end < 1024 || $end > 65535 || $end <= $start) {
        $start = 10000;
        $end   = 12999;
    }

    $extern_ip = trim(getSystemSetting('pjsip_external_ip', ''));
    if ($extern_ip === '') {
        $db = getDB();
        $stmt = $db->query("SELECT data FROM pjsipsettings WHERE keyword = 'externip_val' LIMIT 1");
        $extern_ip = trim((string)($stmt ? $stmt->fetchColumn() : ''));
    }
    if ($extern_ip === '') {
        $extern_ip = portalEnv('EXTERNAL_IP', '198.51.100.1');
    }
    $local_ip = trim(getSystemSetting('server_ip', ''));
    if ($local_ip === '') {
        $local_ip = $_SERVER['SERVER_ADDR'] ?? '127.0.0.1';
    }
    $stun_port = defined('STUN_PORT') && STUN_PORT !== '' ? STUN_PORT : '3478';

    $conf  = "; RTP Configuration (Auto-generated by AI PBX)\n";
    $conf .= "; Bu dosya panelden üretilir — elle yapılan değişiklikler bir sonraki\n";
    $conf .= "; 'Uygula' işleminde KAYBOLUR. Santral Ayarları > RTP bölümünü kullanın.\n";
    $conf .= "\n[general]\n";
    $conf .= "rtpstart={$start}\n";
    $conf .= "rtpend={$end}\n";
    $conf .= "strictrtp={$strict}\n";
    $conf .= "probation=8\n";
    $conf .= "rtptimeout=60\n";
    $conf .= "rtpholdtimeout=300\n";
    $conf .= "tos=ef\n";
    $conf .= "cos=6\n";
    if ($local_ip !== '') {
        // stunaddr VARSAYILAN OLARAK KAPALI (2026-09-05).
        //
        // ÖLÇÜLDÜ: bu satır açıkken Asterisk her RTP oturumu kurarken
        // STUN adresine (3478) bir STUN Binding isteği gönderiyor ve 3 kez
        // (3'er saniye arayla) zaman aşımına uğruyor — yani her WebRTC
        // çağrısı ~6 saniye BLOKE oluyordu:
        //   09:16:40 Attempt 1 ... 09:16:43 Attempt 2 ... 09:16:46 Attempt 3
        //   09:16:46 dialplan calismaya basliyor
        // Kullanıcı belirtisi: "webden arayınca çağrı 4-5 sn gecikmeli
        // başlıyor, mobilde 30 sn".
        //
        // Sunucu tarafı SAĞLAM: aynı adrese düz bir soketten (RTP port
        // aralığından dahil) yapılan STUN sorgusu 0.00 sn'de yanıtlanıyor ve
        // güvenlik duvarı 3478/udp'ye izin veriyor. Sorun Asterisk tarafında:
        // WebRTC/ICE oturumlarında soketi pjproject'in ICE yığını yönetiyor,
        // gelen STUN yanıtı stun.c'nin bloke okumasına hiç ulaşmıyor.
        //
        // NAT eşlemesi için gereken şey zaten aşağıdaki `ice_host_candidates`
        // — o STATİK çalışır, hiçbir ağ sorgusu yapmaz. stunaddr gereksizdi.
        //
        // Yine de gerekirse `rtp_stunaddr_enabled` ayarı '1' yapılarak
        // açılabilir (ör. ICE kullanmayan saf SIP kurulumları için).
        if (getSystemSetting('rtp_stunaddr_enabled', '0') === '1') {
            $conf .= "stunaddr={$local_ip}:{$stun_port}\n";
        }
        if ($extern_ip !== '') {
            $conf .= "ice_host_candidates={$local_ip} => {$extern_ip}\n";
        }
    }

    return $conf;
}

function __syncRtpSettingsBody()
{
    $conf = buildRtpConf();

    // Mevcut içeriği sakla: reload başarısız olursa geri yükle.
    $onceki = is_readable(RTP_CONF_PATH) ? file_get_contents(RTP_CONF_PATH) : null;

    if (!FileHelper::writeFile(RTP_CONF_PATH, $conf, 'asterisk', 'asterisk', 0644)) {
        throw new \Exception('rtp.conf yazılamadı (izin/sahiplik?)');
    }

    try {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadRTP()], 'RTP ayarları');
    } catch (\Exception $e) {
        if ($onceki !== null && FileHelper::writeFile(RTP_CONF_PATH, $onceki, 'asterisk', 'asterisk', 0644)) {
            AsteriskHelper::reloadRTP();
            throw new \Exception('RTP ayarları uygulanamadı, ÖNCEKİ HÂLE OTOMATİK GERİ ALINDI: ' . $e->getMessage());
        }
        throw new \Exception('RTP ayarları uygulanamadı ve GERİ ALINAMADI, ELLE MÜDAHALE GEREKİYOR: ' . $e->getMessage());
    }

    return true;
}
