<?php
/**
 * Sync Calling Permissions Dialplan (/etc/asterisk/pbx/extensions_permissions.conf)
 */

function syncPermissions() {
    return withSyncLock('permissions', '__syncPermissionsBody');
}

function __syncPermissionsBody() {
    $db = getDB();
    $groups = $db->query("SELECT * FROM pbx_permission_groups WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Native Calling Permissions Dialplan (Auto-generated by AI PBX)\n\n";

    $conf .= "[sub-check-dial-permission]\n";
    $conf .= "exten => s,1,NoOp(Dial Permission Check for Caller \${ARG1} -> Target \${ARG2} (Group: \${PERMISSION_GROUP_ID}))\n";
    $conf .= " same => n,Set(PERM_GROUP=\${PERMISSION_GROUP_ID})\n";
    $conf .= " same => n,GotoIf(\$[\"\${PERM_GROUP}\" = \"\" | \"\${PERM_GROUP}\" = \"1\"]?perm_allow)\n";
    $conf .= " same => n,Goto(perm-group-\${PERM_GROUP},\${ARG2},1)\n";
    $conf .= " same => n(perm_allow),Return()\n\n";

    $conf .= "[sub-permission-denied]\n";
    $conf .= "exten => s,1,NoOp(Arama Yetki Kisitlamasi: Hedef aranamaz!)\n";
    $conf .= " same => n,Set(CDR(userfield)=CALL_BARRED)\n";
    $conf .= " same => n,Answer()\n";
    $conf .= " same => n,Playback(ss-noservice)\n";
    $conf .= " same => n,Congestion(10)\n";
    $conf .= " same => n,Hangup(21)\n\n";

    foreach ($groups as $g) {
        $gid = intval($g['id']);
        if ($gid === 1) continue; // Grup 1 varsayılan her yöne açık

        $gname = toCleanAscii($g['group_name']);
        $default_action = $g['default_action'] ?? 'allow';

        $conf .= "; ---- Permission Group #{$gid}: {$gname} ----\n";
        $conf .= "[perm-group-{$gid}]\n";

        $rules_stmt = $db->prepare("SELECT * FROM pbx_permission_rules WHERE group_id = ? ORDER BY priority ASC, id ASC");
        $rules_stmt->execute([$gid]);
        $rules = $rules_stmt->fetchAll(PDO::FETCH_ASSOC);

        foreach ($rules as $r) {
            $raw_pattern = trim($r['pattern']);
            $pattern = preg_replace('/[^0-9NXZnxz.\[\]_!*#-]/', '', $raw_pattern);
            if ($pattern === '') continue;

            $action = ($r['action'] === 'allow') ? 'Return()' : 'Goto(sub-permission-denied,s,1)';
            $is_exact = ($r['pattern_type'] === 'exact');

            if ($is_exact) {
                $conf .= "exten => {$pattern},1,{$action}\n";
            } else {
                // Prefix: numara pattern ile başlıyorsa eşleş
                $prefix_exten = str_starts_with($pattern, '_') ? $pattern : "_{$pattern}.";
                $conf .= "exten => {$prefix_exten},1,{$action}\n";
            }
        }

        // Default action for un-matched numbers
        if ($default_action === 'allow') {
            $conf .= "exten => _.,1,Return()\n\n";
        } else {
            $conf .= "exten => _.,1,Goto(sub-permission-denied,s,1)\n\n";
        }
    }

    return writeConfWithRollback('extensions_permissions.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Arama Yetki Grupları senkronizasyonu');
    }, 'Arama Yetki Grupları senkronizasyonu');
}
