<?php
/**
 * Sync Inbound DIDs Dialplan (/etc/asterisk/pbx/extensions_inbound.conf)
 */
function syncInboundDialplan() {
    return withSyncLock('inbound_dialplan', '__syncInboundDialplanBody');
}

function __syncInboundDialplanBody() {
    $db = getDB();
    $dids = $db->query("SELECT * FROM pbx_dids WHERE is_active = 1 ORDER BY did_number ASC")->fetchAll();

    $conf = "; Native Inbound DID Dialplan (Auto-generated by AI PBX)\n";
    $conf .= "[from-trunk-inbound]\n\n";

    if (!empty($dids)) {
        foreach ($dids as $d) {
            $num = preg_replace('/[^0-9]/', '', trim($d['did_number']));
            $title = toCleanAscii($d['title']);
            $conf .= "; DID: {$num} ({$title})\n";
            $conf .= "exten => {$num},1,NoOp(Inbound call for DID {$num} - {$title})\n";
            $conf .= " same => n,Set(CDR(did)={$num})\n";
            $conf .= " same => n,Set(CDR(direction)=inbound)\n";
            if (!empty($d['language'])) {
                $lang = preg_replace('/[^a-zA-Z_]/', '', $d['language']);
                $conf .= " same => n,Set(CHANNEL(language)={$lang})\n";
            }
            // Zorunlu çağrı kaydı. Bu ayar `pbx_dids.record_call` alanında
            // tutuluyordu ama dialplan'a HİÇ yazılmıyordu: panelde işaretli
            // görünüyor, rapora çağrı düşüyor, ama ses dosyası hiç
            // oluşmuyordu (2026-09-01'de DID 13000'de yaşandı).
            //
            // Kayıt, hedefe gitmeden ÖNCE başlatılmalı — Goto sonrasında
            // buraya dönülmez.
            //
            // `b` seçeneği KULLANILMIYOR: o yalnızca çağrı köprülendikten
            // sonra yazmaya başlar, yani IVR anonsu, karşılama ve tuşlama
            // kayda girmez. Gelen rotada kayıt "zorunlu" işaretliyse çağrının
            // tamamı istenir — kayıt ilk andan itibaren başlar.
            if (!empty($d['record_call'])) {
                $rec = "/var/spool/asterisk/monitor/inbound_"
                     . "\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}_to_{$num}.wav";
                $conf .= " same => n,Set(REC_FILE={$rec})\n";
                $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
                $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            }

            $conf .= buildDestinationLines($d['dest_type'], $d['dest_id'], $num) . "\n\n";
        }
    } else {
        $conf .= "; Default Fallback DID\n";
        $conf .= "exten => _X.,1,NoOp(Fallback Inbound Call for DID \${EXTEN})\n";
        $conf .= " same => n,Set(CDR(did)=\${EXTEN})\n";
        $conf .= " same => n,Set(CDR(direction)=inbound)\n";
        $conf .= " same => n,Goto(app-timecondition-1,s,1)\n\n";
    }

    return writeConfWithRollback('extensions_inbound.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Gelen Rota senkronizasyonu');
    }, 'Gelen Rota senkronizasyonu');
}
