<?php
/**
 * Internal destination numbers dialplan generator
 * (/etc/asterisk/pbx/extensions_internalnumbers.conf)
 *
 * Writes the optional numbers given in the panel to IVR / queue / time
 * condition / announcement / call-ending definitions into one context. THIS
 * FILE DOES NOT KNOW how a number is turned into its destination —
 * buildDestinationLines() already does that for inbound routes and IVR keys
 * and is simply called here. So behaviours such as "start recording when
 * entering the queue", "queue language" and "fallback" stay defined in one
 * place.
 *
 * The context is included by [from-internal-pbx-ortak] (see
 * SyncGeneralDialplan.php). Asterisk searches a context's OWN extensions
 * before its includes, so a real extension number always shadows this list —
 * which is the intended behaviour.
 */

require_once __DIR__ . '/DialplanBuilders.php';
require_once __DIR__ . '/../internal_numbers.php';

function syncInternalNumbers()
{
    return withSyncLock('internal_numbers', '__syncInternalNumbersBody');
}

/**
 * Must the channel be answered when this destination is called from an
 * extension?
 *
 * Returns true only when a sound file is really going to be played. The
 * detailed reasoning is in the comment at the top of buildInternalNumbersConf().
 */
function internalNumberNeedsAnswer(string $destType, string $destId): bool
{
    if ($destType === 'announcement') {
        return true;
    }

    if ($destType === 'hangup') {
        $st = getDB()->prepare(
            "SELECT anc.audio_file
               FROM pbx_hangup_actions ha
               JOIN pbx_announcements anc ON anc.id = ha.announcement_id AND anc.is_active = 1
              WHERE ha.action_key = ? AND ha.is_active = 1
              LIMIT 1"
        );
        $st->execute([$destId]);
        return !empty($st->fetchColumn());
    }

    return false;
}

/**
 * Pure generator — touches no DB, writes no disk, testable.
 *
 * If the same number is defined on two different entities (the application
 * layer prevents it, but the data may have been broken by hand) the FIRST
 * definition wins and the second is skipped: writing the same exten twice
 * produces an "extension already in use" warning on Asterisk reload and puts
 * the whole file at risk.
 *
 * Answer() is added ONLY to destinations that really play a sound file
 * (see internalNumberNeedsAnswer). The reasoning is three-fold:
 *  - Announcement: called from an extension, the channel enters Playback
 *    unanswered; early media does not play on every endpoint. Answer()+Wait(1)
 *    is the same as FreePBX's app-announcement pattern.
 *  - Call ending: on a definition WITHOUT an announcement Answer() would be
 *    HARMFUL — on an unanswered channel Busy() sends a clean SIP 486 and the
 *    phone shows "busy"; on an answered channel it plays an in-band tone for
 *    10 seconds. So only definitions with an announcement_id are answered.
 *  - Queue and IVR: never added. Answering before Queue() marks the call
 *    "answered" in the CDR even if the caller gives up while waiting, and
 *    breaks the call-center reports; the IVR block already calls its own
 *    Answer() (see SyncIVRs.php buildIVRDialplanBlock).
 *
 * @param array $entries output of internalNumberEntries()
 */
function buildInternalNumbersConf(array $entries): string
{
    $conf  = "; Internal destination numbers (Auto-generated by AI PBX)\n";
    $conf .= "; Source: the pbx_*.internal_number columns - see src/internal_numbers.php\n\n";
    $conf .= "[internal-numbers-pbx]\n";

    if (empty($entries)) {
        $conf .= "; (no internal numbers defined)\n";
        return $conf;
    }

    $gorulen = [];
    foreach ($entries as $e) {
        $num = preg_replace('/[^0-9]/', '', (string) $e['number']);
        if ($num === '' || isset($gorulen[$num])) continue;
        $gorulen[$num] = true;

        $label = toCleanAscii((string) $e['label']);
        $conf .= "\n; " . $e['dest_type'] . " #" . $e['dest_id'] . " ({$label})\n";
        $conf .= "exten => {$num},1,NoOp(Internal number {$num} -> " . $e['dest_type'] . "/" . $e['dest_id'] . " - {$label})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";
        if (internalNumberNeedsAnswer($e['dest_type'], $e['dest_id'])) {
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Wait(1)\n";
        }
        $conf .= buildDestinationLines($e['dest_type'], $e['dest_id']) . "\n";
    }

    return $conf;
}

function __syncInternalNumbersBody()
{
    $conf = buildInternalNumbersConf(internalNumberEntries());

    return writeConfWithRollback('extensions_internalnumbers.conf', $conf, function () {
        AsteriskHelper::assertReloadsOk(
            [AsteriskHelper::reloadDialplan()],
            t('sync.ctx_internal_numbers')
        );
    }, t('sync.ctx_internal_numbers'));
}
