<?php
/**
 * Single Master File Queue Sync Module (/etc/asterisk/pbx/queues_pbx.conf)
 * Consolidates all active call center queues into a single master configuration file reading from `queues_details` key-value table.
 */

require_once __DIR__ . '/../queue_helper.php';

function syncQueue($queue_id) {
    return syncAllQueues();
}

function syncAllQueues() {
    return withSyncLock('queues', '__syncAllQueuesBody');
}

function __syncAllQueuesBody() {
    $db = getDB();
    $queues = $db->query("SELECT * FROM pbx_queues WHERE is_active = 1 ORDER BY queue_name ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; ==========================================================\n";
    $conf .= "; Master Call Center Queues Configuration (Auto-generated by AI PBX via queues_details DB)\n";
    $conf .= "; ==========================================================\n\n";

    $conf .= "[general]\n";
    $conf .= "persistentmembers = yes\n";
    $conf .= "autofill = yes\n";
    $conf .= "monitor-type = MixMonitor\n";
    $conf .= "queue_log = yes\n\n";

    foreach ($queues as $q) {
        $q_name = $q['queue_name'];
        $title = toCleanAscii($q['title']);
        $musicclass = toCleanAscii(!empty($q['musicclass']) ? $q['musicclass'] : 'default');

        // Fetch details map from `queues_details` table
        $q_map = QueueHelper::getDetailsMap($q_name);
        if (empty($q_map)) {
            QueueHelper::syncQueueToDetails($q);
            $q_map = QueueHelper::getDetailsMap($q_name);
        }

        $conf .= "; Call Center Queue ID {$q['id']}: {$title} ({$q_name})\n";
        $conf .= "[{$q_name}]\n";
        $conf .= "musicclass={$musicclass}\n";

        // Output all key-value directives stored in `queues_details`
        foreach ($q_map as $k => $v) {
            if ($v === '' || $v === null) continue;
            $conf .= toCleanAscii($k) . "=" . toCleanAscii($v) . "\n";
        }

        // Statik temsilciler: config'ten yüklenen üye Asterisk tarafından "dynamic"
        // değildir, "queue remove member" ile çıkarılamaz, sadece pause edilebilir.
        // Arayüz/interface/state_interface dinamik girişle (QueueHelper::setMembership)
        // birebir aynı tutulur — yoksa aynı temsilci iki ayrı üye olarak görünürdü.
        foreach (QueueHelper::staticMembersOf($q) as $s_ext) {
            $s_ext = preg_replace('/[^0-9]/', '', $s_ext);
            if ($s_ext === '') continue;
            $conf .= "member => Local/{$s_ext}@from-internal-pbx/n,0,Temsilci {$s_ext},hint:{$s_ext}@from-internal-pbx\n";
        }
        $conf .= "\n";
    }

    // Delete old individual queue files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/queue_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }

    $result = writeConfWithRollback("queues_pbx.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadQueue('all')], 'Kuyruk senkronizasyonu');
    }, 'Kuyruk senkronizasyonu');

    foreach ($queues as $q) {
        purgeStaticFromPersistentMembers($q['queue_name'], QueueHelper::staticMembersOf($q));
    }

    return $result;
}

/**
 * Dinamikken statiğe çevrilen temsilcinin eski kaydı astdb'deki
 * Queue/PersistentMembers/<kuyruk> değerinde kalıyor (Asterisk bu değeri sadece
 * dinamik üye eklenip çıkarıldığında yeniden yazar). Temizlenmezse Asterisk
 * yeniden başladığında config'te artık olmayan (statikten çıkarılmış) temsilci
 * dinamik üye olarak kuyruğa geri gelirdi. Değer "|" ile ayrılmış
 * "interface;penalty;paused;..." kayıtlarından oluşur (app_queue dump_queue_members).
 */
function purgeStaticFromPersistentMembers($q_name, array $static_exts) {
    if (empty($static_exts)) return;
    @exec("asterisk -rx " . escapeshellarg("database get Queue/PersistentMembers $q_name"), $out);
    $value = null;
    foreach ($out ?: [] as $line) {
        if (strpos($line, 'Value: ') === 0) $value = substr($line, 7);
    }
    if ($value === null || $value === '') return;

    $static_ifaces = array_map(fn($e) => "Local/{$e}@from-internal-pbx/n", $static_exts);
    $entries = explode('|', $value);
    $kept = array_filter($entries, fn($entry) => !in_array(explode(';', $entry)[0], $static_ifaces, true));
    if (count($kept) === count($entries)) return;

    if (empty($kept)) {
        @exec("asterisk -rx " . escapeshellarg("database del Queue/PersistentMembers $q_name"));
    } else {
        @exec("asterisk -rx " . escapeshellarg("database put Queue/PersistentMembers $q_name \"" . str_replace('"', '', implode('|', $kept)) . "\""));
    }
}

