<?php
/**
 * Sync Outbound Routes Dialplan (/etc/asterisk/pbx/extensions_outbound.conf)
 */
/*
 * The `b` option of MixMonitor is NOT USED.
 *
 * `b` starts writing only after the call is bridged; announcements, ringing
 * and keypresses are not recorded. It does not even do what one expects: if
 * the call is never bridged the file is still created, just EMPTY (44 bytes,
 * a bare WAV header — seen in outbound call recordings on 2026-09-01). So it
 * does not prevent empty files from piling up either.
 */
function syncOutboundDialplan() {
    return withSyncLock('outbound_dialplan', '__syncOutboundDialplanBody');
}

function __syncOutboundDialplanBody() {
    // Trunk channel limits. The route's trunks_json does not have them; the
    // limit is kept on the trunk's own record (pbx_trunks.max_channels).
    $trunk_limitleri = [];
    $trunk_cid_norm = [];
    foreach (getDB()->query("SELECT trunk_name, max_channels, cid_keep_last, cid_prepend FROM pbx_trunks")->fetchAll(PDO::FETCH_ASSOC) as $tl) {
        $trunk_limitleri[$tl['trunk_name']] = intval($tl['max_channels']);
        $trunk_cid_norm[$tl['trunk_name']] = [
            'keep_last' => max(0, min(20, intval($tl['cid_keep_last'] ?? 0))),
            'prepend' => preg_replace('/[^0-9+]/', '', (string)($tl['cid_prepend'] ?? '')),
        ];
    }

    $db = getDB();
    $routes = $db->query("SELECT * FROM pbx_outbound_routes WHERE is_active = 1 ORDER BY sort_order ASC, id ASC")->fetchAll();
    $external_dial_timeout = intval(getSystemSetting('pjsip_external_dial_timeout', '60'));

    // Routes are split by group. Every group gets its own context; users can
    // only use the routes of the group they are in.
    //
    // Group 1 is also generated as [from-internal-outbound]: the existing
    // endpoints and the Local/...@from-internal-pbx calls in the queues are
    // bound to this name, so nothing changes on installs without groups.
    $gruplar = [];
    foreach ($routes as $r) {
        $g = max(1, intval($r['route_group'] ?? 1));
        $gruplar[$g][] = $r;
    }
    if (empty($gruplar)) {
        $gruplar[1] = [];
    }
    ksort($gruplar);

    $conf = "; Native Outbound Dialplan Context (Auto-generated by AI PBX)\n\n";
    // Each route's body is also published as [outbound-route-<id>] (any number),
    // so a destination "outbound route" sends calls straight to that route.
    $route_blocks = [];

    foreach ($gruplar as $grup_no => $grup_rotalari) {
        $conf .= "; ---- Outbound route group {$grup_no} ----\n";
        $conf .= "[from-internal-outbound-{$grup_no}]\n\n";
        $routes = $grup_rotalari;

    if (!empty($routes)) {
        foreach ($routes as $r) {
            $name = toCleanAscii($r['route_name']);
            $pattern = preg_replace('/[^0-9NXZnxz.\[\]_!*#-]/', '', trim($r['match_pattern']));
            $prepend = preg_replace('/[^0-9]/', '', trim($r['prepend'] ?? ''));
            $append = preg_replace('/[^0-9]/', '', trim($r['append'] ?? ''));
            $strip_front = intval($r['strip_front'] ?? 0);
            $strip_back = intval($r['strip_back'] ?? 0);
            $is_internal = !empty($r['is_internal']);

            // Trunk list: no primary/backup split — a chain of trunks added one
            // by one and tried in order. Every entry can have its own caller ID
            // masking value. Empty/undefined trunk names are dropped; if no
            // trunk is left (new/empty install) the single active trunk in the
            // system is used, and without one it ends with Congestion().
            $trunks_raw = !empty($r['trunks_json']) ? (json_decode($r['trunks_json'], true) ?: []) : [];
            $trunk_chain = [];
            foreach ($trunks_raw as $t) {
                $tn = trim($t['trunk_name'] ?? '');
                if ($tn === '') continue;
                $trunk_chain[] = ['trunk_name' => $tn, 'callerid_override' => trim($t['callerid_override'] ?? ''), 'max_channels' => intval($trunk_limitleri[$tn] ?? 0)];
            }
            if (empty($trunk_chain)) {
                $fallback = AsteriskHelper::getPrimaryTrunkName();
                if ($fallback !== null) {
                    $trunk_chain[] = ['trunk_name' => $fallback, 'callerid_override' => '', 'max_channels' => 0];
                }
            }

            $trunk_label = !empty($trunk_chain) ? implode(' -> ', array_column($trunk_chain, 'trunk_name')) : 'YOK (tanımlı/aktif trunk bulunamadı)';
            $block_start = strlen($conf);
            $conf .= "; Outbound Route: {$name} (Pattern: {$pattern} -> Trunk: {$trunk_label})\n";
            $conf .= "exten => {$pattern},1,NoOp(Outbound Call via Route {$name} -> Trunk {$trunk_label})\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Gosub(sub-check-dial-permission,s,1(\${CALLERID(num)},\${EXTEN}))\n";

            if (empty($trunk_chain)) {
                $conf .= " same => n,NoOp(Bu rota icin tanimli/aktif bir dis hat yok)\n";
                $conf .= " same => n,Congestion(10)\n";
                $conf .= " same => n,Hangup(34)\n\n";
                $route_blocks[(int)$r['id']] = [$pattern, substr($conf, $block_start)];
                continue;
            }

            // Number transformation: strip from the front/back first, then add the prefix/suffix.
            // Asterisk ${VAR:offset:length} with a negative length means "N characters from the end".
            $core = "\${EXTEN}";
            if ($strip_front > 0 || $strip_back > 0) {
                $core = ($strip_back > 0) ? "\${EXTEN:{$strip_front}:-{$strip_back}}" : "\${EXTEN:{$strip_front}}";
            }
            $dial_num = $prepend . $core . $append;

            // The CID of the first trunk to try is applied before the recording file name is set.
            // The original caller number is restored before every trunk attempt,
            // so a fallback trunk's normalization does not stack on the previous one.
            $conf .= " same => n,Set(AIPBX_SRC_CID=\${CALLERID(num)})\n";
            $conf .= buildTrunkCallerIdLine($trunk_chain[0], $is_internal);
            $conf .= buildTrunkCidNormalizeLine($trunk_cid_norm[$trunk_chain[0]['trunk_name']] ?? null);

            $conf .= " same => n,Set(REC_FILE=/var/spool/asterisk/monitor/outbound_\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}_to_{$dial_num}.wav)\n";
            $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
            $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            $conf .= " same => n,Set(CHANNEL(accountcode)=\${CALLERID(num)})\n";

            // Try in order: when a trunk returns CHANUNAVAIL/CONGESTION, move on to the next.
            // Every attempt applies its own trunk's CID (the first one was applied above already).
            $count = count($trunk_chain);
            foreach ($trunk_chain as $idx => $t) {
                $step = $idx + 1;
                if ($idx > 0) {
                    $conf .= " same => n(try{$step}),NoOp(Trying trunk {$t['trunk_name']})\n";
                    $conf .= " same => n,Set(CALLERID(num)=\${AIPBX_SRC_CID})\n";
                    $conf .= buildTrunkCallerIdLine($t, $is_internal);
                    $conf .= buildTrunkCidNormalizeLine($trunk_cid_norm[$t['trunk_name']] ?? null);
                }
                // Trunk channel limit. `max_channels` was entered in the panel
                // and saved to the database but NEVER reached the dialplan:
                // calls were unlimited although "at most N channels" was set
                // (2026-09-01 field audit).
                //
                // The GROUP counter is per channel; Asterisk drops it itself
                // when the call ends. When the limit is full this trunk counts
                // as CONGESTION so the next trunk in the chain is tried.
                $limit = intval($t['max_channels'] ?? 0);
                if ($limit > 0) {
                    $conf .= " same => n,Set(GROUP(trunk)={$t['trunk_name']})\n";
                    $conf .= " same => n,GotoIf(\$[\${GROUP_COUNT(" . $t['trunk_name'] . "@trunk)} > {$limit}]?trunkfull{$step})\n";
                }
                // D-1: the 'r' option was removed (only 'T' is used).
                // The carrier's early media (183 Session Progress / announcement / real busy tone)
                // thus reaches the caller directly instead of being masked by a fake local ring.
                $conf .= " same => n,Set(JITTERBUFFER(adaptive)=default)\n";
                $conf .= " same => n,Dial(PJSIP/{$dial_num}@{$t['trunk_name']},{$external_dial_timeout},Tb(sub-callee-jb^s^1))\n";
                if ($limit > 0) {
                    $conf .= " same => n,Goto(afterdial{$step})\n";
                    $conf .= " same => n(trunkfull{$step}),NoOp(Trunk {$t['trunk_name']} kanal siniri dolu: {$limit})\n";
                    $conf .= " same => n,Set(DIALSTATUS=CONGESTION)\n";
                    $conf .= " same => n(afterdial{$step}),NoOp()\n";
                }
                if ($step < $count) {
                    $next = $step + 1;
                    $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\"=\"CHANUNAVAIL\"|\"\${DIALSTATUS}\"=\"CONGESTION\"]?try{$next}:donecall)\n";
                }
            }
            // D-2: after Dial, instead of a bare Hangup, branch to the status handler that
            // passes the real DIALSTATUS and HANGUPCAUSE codes on to the SIP side.
            $done_label = ($count > 1) ? '(donecall)' : '';
            $conf .= " same => n{$done_label},Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
            $route_blocks[(int)$r['id']] = [$pattern, substr($conf, $block_start)];
        }
    } else {
        $fallback_trunk = AsteriskHelper::getPrimaryTrunkName();
        $conf .= "; Fallback Outbound Route\n";
        if ($fallback_trunk === null) {
            $conf .= "; No trunk defined yet - outbound calling is disabled.\n";
            $conf .= "exten => _NXXXXXX,1,NoOp(No trunk configured)\n";
            $conf .= " same => n,Congestion(10)\n";
            $conf .= " same => n,Hangup(34)\n\n";
            $conf .= "exten => _05XXXXXXXXX,1,NoOp(No trunk configured)\n";
            $conf .= " same => n,Congestion(10)\n";
            $conf .= " same => n,Hangup(34)\n\n";
        } else {
            $conf .= "exten => _NXXXXXX,1,NoOp(Fallback Outbound Call)\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Dial(PJSIP/\${EXTEN}@{$fallback_trunk},{$external_dial_timeout},T)\n";
            $conf .= " same => n,Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
            $conf .= "exten => _05XXXXXXXXX,1,NoOp(Fallback Mobile Outbound Call)\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Dial(PJSIP/\${EXTEN}@{$fallback_trunk},{$external_dial_timeout},T)\n";
            $conf .= " same => n,Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
        }
    }
    } // grup dongusu sonu

    foreach ($route_blocks as $route_id => [$pattern, $block]) {
        $conf .= "[outbound-route-{$route_id}]\n";
        $conf .= preg_replace('/^exten => ' . preg_quote($pattern, '/') . ',1,/m', 'exten => _[0-9*#+].,1,', $block, 1);
    }

    // Publish group 1 under the old name too: the existing endpoints' context
    // and the Local/...@from-internal-pbx calls in the queues are bound to it.
    // So nothing changes on installs without groups.
    $conf .= "; ---- Backward compatibility: the old name of group 1 ----\n";
    $conf .= "[from-internal-outbound]\n";
    $conf .= "include => from-internal-outbound-1\n\n";

    // Outbound call termination and status handling (D-1 / D-2)
    // BUSY -> 486 Busy Here, CONGESTION -> 503, NOANSWER -> 480, CHANUNAVAIL -> HANGUPCAUSE (e.g. 404/603)
    $conf .= "; ---- Outbound call status handling (D-1 / D-2) ----\n";
    $conf .= "[sub-outbound-status]\n";
    $conf .= "exten => s,1,NoOp(Outbound Status: s - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:16)})\n\n";
    $conf .= "exten => ANSWER,1,NoOp(Outbound Status: ANSWER - Normal Hangup)\n";
    $conf .= " same => n,Hangup(16)\n\n";
    $conf .= "exten => BUSY,1,NoOp(Outbound Status: BUSY - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(17)\n\n";
    $conf .= "exten => CONGESTION,1,NoOp(Outbound Status: CONGESTION - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(34)\n\n";
    $conf .= "exten => CHANUNAVAIL,1,NoOp(Outbound Status: CHANUNAVAIL - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:1)})\n\n";
    $conf .= "exten => NOANSWER,1,NoOp(Outbound Status: NOANSWER - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(19)\n\n";
    $conf .= "exten => CANCEL,1,NoOp(Outbound Status: CANCEL)\n";
    $conf .= " same => n,Hangup(16)\n\n";
    $conf .= "exten => DONTCALL,1,NoOp(Outbound Status: DONTCALL)\n";
    $conf .= " same => n,Hangup(21)\n\n";
    $conf .= "exten => TORTURE,1,NoOp(Outbound Status: TORTURE)\n";
    $conf .= " same => n,Hangup(21)\n\n";
    $conf .= "exten => INVALIDARGS,1,NoOp(Outbound Status: INVALIDARGS)\n";
    $conf .= " same => n,Hangup(38)\n\n";
    $conf .= "exten => i,1,NoOp(Outbound Status: Unknown status - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:16)})\n\n";
    $conf .= "exten => e,1,NoOp(Outbound Status: e)\n";
    $conf .= " same => n,Hangup(16)\n\n";
    $conf .= "exten => h,1,NoOp(Outbound Channel Hangup Complete)\n\n";

    return writeConfWithRollback('extensions_outbound.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Giden Rota senkronizasyonu');
    }, 'Giden Rota senkronizasyonu');
}
