<?php
/**
 * UDPTL (T.38 fax media ports & FEC) sync (/etc/asterisk/udptl.conf)
 */

define('UDPTL_CONF_PATH', ASTERISK_CONF_DIR . '/udptl.conf');

function syncUdptlSettings()
{
    return withSyncLock('udptl', '__syncUdptlSettingsBody');
}

function __syncUdptlSettingsBody()
{
    $start       = (int) getSystemSetting('udptl_start', '4100');
    $end         = (int) getSystemSetting('udptl_end', '4999');
    $checksums   = getSystemSetting('udptl_checksums', 'yes') === 'no' ? 'no' : 'yes';
    $fec_entries = max(0, min(9, (int) getSystemSetting('udptl_fec_entries', '3')));
    $fec_span    = max(0, min(9, (int) getSystemSetting('udptl_fec_span', '3')));

    if ($start < 1024 || $start > 65535 || $end < 1024 || $end > 65535 || $end <= $start) {
        $start = 4100;
        $end   = 4999;
    }

    $conf  = "; UDPTL Configuration (Auto-generated by AI PBX)\n";
    $conf .= "; Generated by the portal — manual edits are LOST on the next\n";
    $conf .= "; Apply. Use the UDPTL section of the PBX settings instead.\n";
    $conf .= "\n[general]\n";
    $conf .= "udptlstart={$start}\n";
    $conf .= "udptlend={$end}\n";
    $conf .= "udptlchecksums={$checksums}\n";
    $conf .= "udptlfecentries={$fec_entries}\n";
    $conf .= "udptlfecspan={$fec_span}\n";

    $onceki = is_readable(UDPTL_CONF_PATH) ? file_get_contents(UDPTL_CONF_PATH) : null;

    if (!FileHelper::writeFile(UDPTL_CONF_PATH, $conf, 'asterisk', 'asterisk', 0644)) {
        throw new \Exception(sprintf(t('sync.err_conf_write'), 'udptl.conf'));
    }

    try {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadUDPTL()], t('sync.ctx_udptl'));
    } catch (\Exception $e) {
        if ($onceki !== null && FileHelper::writeFile(UDPTL_CONF_PATH, $onceki, 'asterisk', 'asterisk', 0644)) {
            AsteriskHelper::reloadUDPTL();
            throw new \Exception(sprintf(t('sync.err_settings_rolled_back'), 'UDPTL', $e->getMessage()));
        }
        throw new \Exception(sprintf(t('sync.err_settings_no_rollback'), 'UDPTL', $e->getMessage()));
    }

    return true;
}
