<?php
/**
 * Feature Code (Star Code) Dialplan Sync Module (/etc/asterisk/pbx/extensions_featurecodes.conf)
 *
 * Kodlar `pbx_feature_codes` tablosundan okunur (admin panelden düzenlenebilir).
 * DND/Çağrı Yönlendirme durumu astdb yerine doğrudan sys_users'ta tutulur;
 * bu yüzden telefon üzerinden kod tuşlandığında dialplan sadece bir arka plan
 * betiğini tetikler (feature_code_action.php), o da DB'yi günceller ve
 * syncEverything() ile dialplan'ı yeniden üretip reload eder — sistemin
 * genelindeki "DB -> config üret -> reload" deseniyle birebir aynı.
 */

function syncFeatureCodes() {
    return withSyncLock('featurecodes', '__syncFeatureCodesBody');
}

function __syncFeatureCodesBody() {
    $db = getDB();
    $codes = $db->query("SELECT * FROM pbx_feature_codes WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Feature Code (Star Code) Dialplan (Auto-generated by AI PBX)\n\n";
    $conf .= "[featurecodes-pbx]\n\n";

    foreach ($codes as $c) {
        $code = preg_replace('/[^0-9A-Za-z_.*#\[\]-]/', '', trim($c['code']));
        $key = preg_replace('/[^a-zA-Z0-9_]/', '', (string)$c['feature_key']);
        if ($code === '' || $key === '') continue;

        $conf .= "; " . toCleanAscii($c['title']) . " ({$key})\n";
        $allowed = trim($c['allowed_roles'] ?? '');
        $gated = $allowed !== '';

        if ($key === 'queue_login' || $key === 'queue_logout') {
            $base_code = rtrim(ltrim($code, '_'), '.X');
            $pattern_code = '_' . $base_code . '.';
            $prefix_len = strlen($base_code);
            $action = ($key === 'queue_login') ? 'queue_login' : 'queue_logout';

            // 1. Doğrudan kod tuşlandığında (*81 / *80): Temsilcinin atanmış olduğu tüm kuyruklara giriş/çıkış
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - tum kuyruklar)\n";
            $conf .= "exten => {$base_code},1,NoOp(Feature Code {$key} (all queues) by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_base)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_base),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php {$action} \${CALLERID(num)} all &)\n";
            $conf .= " same => n,Answer()\n";
            if ($key === 'queue_login') {
                $conf .= " same => n,Playback(queue-agentlogin-success)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PLAYBACKSTATUS}\" = \"SUCCESS\"]?login_all_done)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n(login_all_done),Wait(2)\n";
                $conf .= " same => n,Hangup()\n\n";
            } else {
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(0.2)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n\n";
            }

            // 2. Belirli kuyruk no/id tuşlandığında (*81<kuyruk> / *80<kuyruk>): Belirli kuyruğa giriş/çıkış
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - belirli kuyruk)\n";
            $conf .= "exten => {$pattern_code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_pat)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_pat),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,Set(QID=\${EXTEN:{$prefix_len}})\n";
            $conf .= " same => n,GotoIf(\$[\"\${QID}\" = \"\"]?{$key}_empty)\n";
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php {$action} \${CALLERID(num)} \${QID} &)\n";
            $conf .= " same => n,Answer()\n";
            if ($key === 'queue_login') {
                $conf .= " same => n,Playback(queue-agentlogin-success)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PLAYBACKSTATUS}\" = \"SUCCESS\"]?login_pat_done)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n(login_pat_done),Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
            } else {
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(0.2)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
            }
            $conf .= " same => n({$key}_empty),Playback(beep)\n";
            $conf .= " same => n,Wait(2)\n";
            $conf .= " same => n,Hangup()\n\n";
            continue;
        }

        if ($key === 'queue_pause') {
            $base_code = rtrim(ltrim($code, '_'), '.X');
            $pattern_code = '_' . $base_code . '.';
            $prefix_len = strlen($base_code);

            // 1. Doğrudan kod tuşlandığında (*22): Varsayılan mola türü (1. mola)
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - varsayilan)\n";
            $conf .= "exten => {$base_code},1,NoOp(Feature Code {$key} (default) by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_base)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_base),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_pause \${CALLERID(num)} 1 &)\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(0.2)\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(1)\n";
            $conf .= " same => n,Hangup()\n\n";

            // 2. Mola ID ile tuşlandığında (*22<mola_id>, ör: *221, *222):
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - mola id ile)\n";
            $conf .= "exten => {$pattern_code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_pat)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_pat),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,Set(REASON_ID=\${EXTEN:{$prefix_len}})\n";
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_pause \${CALLERID(num)} \${REASON_ID} &)\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(0.2)\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(1)\n";
            $conf .= " same => n,Hangup()\n\n";
            continue;
        }

        $conf .= "; " . toCleanAscii($c['title']) . " ({$key})\n";
        $conf .= "exten => {$code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";

        if ($gated) {
            $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
            $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
            $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key})\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Hangup()\n";
            $conf .= " same => n(allowed_{$key}),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
        }

        switch ($key) {
            case 'dnd_toggle':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php dnd_toggle \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_set':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(CFTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${CFTARGET}\" = \"\"]?cfset_empty)\n";
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_set \${CALLERID(num)} \${CFTARGET} &)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(cfset_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_cancel':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_cancel \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_group':
                $conf .= " same => n,Pickup()\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_directed':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(PICKTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PICKTARGET}\" = \"\"]?pickdir_empty)\n";
                $conf .= " same => n,PickupChan(PJSIP/\${PICKTARGET}-sip&PJSIP/\${PICKTARGET}-webrtc&PJSIP/\${PICKTARGET}-mob-webrtc)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(pickdir_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;


            case 'spy':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(SPYTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${SPYTARGET}\" = \"\"]?spy_empty)\n";
                $conf .= " same => n,ChanSpy(PJSIP/\${SPYTARGET},b)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(spy_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'queue_unpause':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_unpause \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(1)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            default:
                // Bilinmeyen/gelecekteki feature_key: güvenli varsayılan (sadece kapat)
                $conf .= " same => n,Hangup()\n";
                break;
        }
        $conf .= "\n";
    }

    return writeConfWithRollback('extensions_featurecodes.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Özellik Kodu senkronizasyonu');
    }, 'Özellik Kodu senkronizasyonu');
}
