<?php
/**
 * Feature Code (Star Code) Dialplan Sync Module (/etc/asterisk/pbx/extensions_featurecodes.conf)
 *
 * The codes are read from the `pbx_feature_codes` table (editable in the
 * admin panel). The DND/call forwarding state is kept directly in sys_users
 * instead of astdb; so when a code is dialed on the phone, the dialplan only
 * triggers a background script (feature_code_action.php), which updates the
 * DB and regenerates + reloads the dialplan with syncEverything() — exactly
 * the system-wide "DB -> generate config -> reload" pattern.
 */

function syncFeatureCodes() {
    return withSyncLock('featurecodes', '__syncFeatureCodesBody');
}

function __syncFeatureCodesBody() {
    $db = getDB();
    $codes = $db->query("SELECT * FROM pbx_feature_codes WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Feature Code (Star Code) Dialplan (Auto-generated by AI PBX)\n\n";
    $conf .= "[featurecodes-pbx]\n\n";

    foreach ($codes as $c) {
        $code = preg_replace('/[^0-9A-Za-z_.*#\[\]-]/', '', trim($c['code']));
        $key = preg_replace('/[^a-zA-Z0-9_]/', '', (string)$c['feature_key']);
        if ($code === '' || $key === '') continue;

        $conf .= "; " . toCleanAscii($c['title']) . " ({$key})\n";
        $allowed = trim($c['allowed_roles'] ?? '');
        $gated = $allowed !== '';

        if ($key === 'queue_login' || $key === 'queue_logout') {
            $base_code = rtrim(ltrim($code, '_'), '.X');
            $pattern_code = '_' . $base_code . '.';
            $prefix_len = strlen($base_code);
            $action = ($key === 'queue_login') ? 'queue_login' : 'queue_logout';

            // 1. Code dialed alone (*81 / *80): log in/out of all queues the agent is assigned to
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - all queues)\n";
            $conf .= "exten => {$base_code},1,NoOp(Feature Code {$key} (all queues) by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_base)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_base),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php {$action} \${CALLERID(num)} all &)\n";
            $conf .= " same => n,Answer()\n";
            if ($key === 'queue_login') {
                $conf .= " same => n,Playback(queue-agentlogin-success)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PLAYBACKSTATUS}\" = \"SUCCESS\"]?login_all_done)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n(login_all_done),Wait(2)\n";
                $conf .= " same => n,Hangup()\n\n";
            } else {
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(0.2)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n\n";
            }

            // 2. A specific queue no/id dialed (*81<queue> / *80<queue>): log in/out of that queue
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - specific queue)\n";
            $conf .= "exten => {$pattern_code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_pat)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_pat),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,Set(QID=\${EXTEN:{$prefix_len}})\n";
            $conf .= " same => n,GotoIf(\$[\"\${QID}\" = \"\"]?{$key}_empty)\n";
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php {$action} \${CALLERID(num)} \${QID} &)\n";
            $conf .= " same => n,Answer()\n";
            if ($key === 'queue_login') {
                $conf .= " same => n,Playback(queue-agentlogin-success)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PLAYBACKSTATUS}\" = \"SUCCESS\"]?login_pat_done)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n(login_pat_done),Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
            } else {
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(0.2)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(2)\n";
                $conf .= " same => n,Hangup()\n";
            }
            $conf .= " same => n({$key}_empty),Playback(beep)\n";
            $conf .= " same => n,Wait(2)\n";
            $conf .= " same => n,Hangup()\n\n";
            continue;
        }

        if ($key === 'queue_pause') {
            $base_code = rtrim(ltrim($code, '_'), '.X');
            $pattern_code = '_' . $base_code . '.';
            $prefix_len = strlen($base_code);

            // 1. Code dialed alone (*22): the default pause type (pause 1)
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - default)\n";
            $conf .= "exten => {$base_code},1,NoOp(Feature Code {$key} (default) by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_base)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_base),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_pause \${CALLERID(num)} 1 &)\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(0.2)\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(1)\n";
            $conf .= " same => n,Hangup()\n\n";

            // 2. Dialed with a pause ID (*22<pause_id>, e.g. *221, *222):
            $conf .= "; " . toCleanAscii($c['title']) . " ({$key} - with pause id)\n";
            $conf .= "exten => {$pattern_code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";
            if ($gated) {
                $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
                $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
                $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key}_pat)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(allowed_{$key}_pat),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
            }
            $conf .= " same => n,Set(REASON_ID=\${EXTEN:{$prefix_len}})\n";
            $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_pause \${CALLERID(num)} \${REASON_ID} &)\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(0.2)\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Wait(1)\n";
            $conf .= " same => n,Hangup()\n\n";
            continue;
        }

        $conf .= "; " . toCleanAscii($c['title']) . " ({$key})\n";
        $conf .= "exten => {$code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";

        if ($gated) {
            $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
            $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
            $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key})\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Hangup()\n";
            $conf .= " same => n(allowed_{$key}),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
        }

        switch ($key) {
            case 'dnd_toggle':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php dnd_toggle \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_set':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(CFTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${CFTARGET}\" = \"\"]?cfset_empty)\n";
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_set \${CALLERID(num)} \${CFTARGET} &)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(cfset_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_cancel':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_cancel \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_group':
                $conf .= " same => n,Pickup()\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_directed':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(PICKTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PICKTARGET}\" = \"\"]?pickdir_empty)\n";
                $conf .= " same => n,PickupChan(PJSIP/\${PICKTARGET}-sip&PJSIP/\${PICKTARGET}-webrtc&PJSIP/\${PICKTARGET}-mob-webrtc)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(pickdir_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;


            case 'spy':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(SPYTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${SPYTARGET}\" = \"\"]?spy_empty)\n";
                $conf .= " same => n,ChanSpy(PJSIP/\${SPYTARGET},b)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(spy_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'spy_whisper':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(SPYTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${SPYTARGET}\" = \"\"]?spy_w_empty)\n";
                $conf .= " same => n,ChanSpy(PJSIP/\${SPYTARGET},qwb)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(spy_w_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'spy_barge':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(SPYTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${SPYTARGET}\" = \"\"]?spy_b_empty)\n";
                $conf .= " same => n,ChanSpy(PJSIP/\${SPYTARGET},qBb)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(spy_b_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'voicemail_my':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,VoiceMailMain(\${CALLERID(num)}@default,s)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'voicemail_general':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,VoiceMailMain(@default)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'queue_unpause':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_unpause \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Wait(1)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            default:
                // Unknown/future feature_key: safe default (just hang up)
                $conf .= " same => n,Hangup()\n";
                break;
        }
        $conf .= "\n";
    }

    return writeConfWithRollback('extensions_featurecodes.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Özellik Kodu senkronizasyonu');
    }, 'Özellik Kodu senkronizasyonu');
}
