<?php
/**
 * Single Master File Extension Sync Module (/etc/asterisk/pbx/pjsip_endpoints.conf)
 * Consolidates all active subscriber endpoints into a single master configuration file reading from `sip` key-value table.
 */

require_once __DIR__ . '/../sip_helper.php';

/**
 * PJSIP identify blogunun From basliginda kabul edecegi HOST listesi.
 *
 * Neden gerekli: identify blogu yalnizca kullanici kismina bakiyordu
 * (`<?sip:3001[@:]`), yani From basliginin HOST kismi ne olursa olsun
 * esleşiyordu. 2026-09-05'te sentetik SIP OPTIONS ile OLCULDU:
 * `From: <sip:3001@198.51.100.1>` (trunk'in adresi) de `3001-sip`
 * endpoint'iyle esleşiyor, `sip:999999@198.51.100.1` ise "No matching
 * endpoint" aliyor. Yani dis hattan gelen ve arayan numarasi bir portal
 * dahilisine esit olan bir cagri, trunk endpoint'i yerine o kullanicinin
 * endpoint'iyle eslesip auth istendigi icin 401 ile dusebiliyordu
 * (bulgu2.md B2-3). Kimlik dogrulama acigi DEGIL — islevsel bir risk.
 *
 * Cozum: host kismini santralin KENDI adreslerine baglamak. Gercek masaustu
 * telefon loglarda `From: "3001" <sip:3001@pbx.example.com>` gonderiyor,
 * yani PBX'in adresini kullaniyor; disaridan gelen cagri ise kendi/uzak
 * hostunu tasiyor.
 *
 * Liste `pjsip_identify_hosts` ayariyla (virgullu) EZILEBILIR. Otomatik
 * kaynaklar: pjsip_external_ip, sunucunun yerel IPv4 adresleri, Apache
 * ServerName ve localhost. Liste bos kalirsa ESKI GENIS desen kullanilir —
 * yanlis bir daraltmanin telefonlari kayit disi birakmasindansa eski
 * davranisa donmek yeglenir.
 *
 * @return string[] regex'e girecek ham host degerleri
 */
function pjsipIdentifyHosts(): array
{
    $elle = trim((string) getSystemSetting('pjsip_identify_hosts', ''));
    if ($elle !== '') {
        return array_values(array_filter(array_map('trim', explode(',', $elle))));
    }

    $hosts = ['localhost', '127.0.0.1'];

    $harici = trim((string) getSystemSetting('pjsip_external_ip', ''));
    if ($harici !== '') { $hosts[] = $harici; }

    if (function_exists('net_get_interfaces')) {
        foreach ((array) net_get_interfaces() as $iface) {
            foreach ($iface['unicast'] ?? [] as $u) {
                if (!empty($u['address']) && filter_var($u['address'], FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
                    $hosts[] = $u['address'];
                }
            }
        }
    }

    // Apache ServerName — masaustu telefonlarin From hostu bu (loglarda dogrulandi).
    foreach (glob('/etc/httpd/conf.d/*.conf') as $f) {
        $icerik = @file_get_contents($f);
        if ($icerik !== false && preg_match_all('/^\s*ServerName\s+(\S+)/mi', $icerik, $m)) {
            foreach ($m[1] as $sn) { $hosts[] = trim($sn); }
        }
    }

    return array_values(array_unique(array_filter($hosts)));
}

function syncExtension($ext) {
    return syncAllExtensions();
}

function syncAllExtensions() {
    return withSyncLock('extensions', '__syncAllExtensionsBody');
}

function __syncAllExtensionsBody() {
    $db = getDB();
    // Faks kullanıcıları (extension_type='fax') hiçbir zaman SIP kaydı yapmaz
    // (gelen faks doğrudan [from-trunk-fax]'a düşer, giden faks call-file ile
    // gönderilir) — bu yüzden PJSIP endpoint/AOR/auth ÜRETİLMEZ.
    $users = $db->query("SELECT extension, full_name, sip_password, sip_auth_digest, cid_internal, cid_external, pickup_group, role, outbound_group FROM sys_users WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip' ORDER BY extension ASC")->fetchAll(PDO::FETCH_ASSOC);

    $webrtc_codecs = getSystemSetting('pjsip_codecs', 'opus,ulaw,alaw,g722');
    $wired_codecs = getSystemSetting('pjsip_wired_codecs', 'alaw,ulaw,g729');
    $direct_media = getSystemSetting('pjsip_direct_media', 'no');
    $rtp_symmetric = getSystemSetting('pjsip_rtp_symmetric', 'yes');
    $qualify_frequency = intval(getSystemSetting('pjsip_qualify_frequency', '60'));
    $qualify_frequency_mobile = intval(getSystemSetting('pjsip_qualify_frequency_mobile', '0'));

    $conf = "; ==========================================================\n";
    $conf .= "; Master PJSIP Endpoints Configuration (Auto-generated by AI PBX via sip Key-Value DB)\n";
    $conf .= "; ==========================================================\n\n";

    // 1. Base Templates
    // Standart SIP cihazları (masa telefonu, klasik softphone): DTLS/ICE/AVPF YOK
    $conf .= "[endpoint-sip](!)\n";
    $conf .= "type=endpoint\n";
    $conf .= "context=from-internal-pbx\n";
    $conf .= "disallow=all\n";
    $conf .= "allow={$wired_codecs}\n";
    $conf .= "transport=transport-udp\n";
    $conf .= "identify_by=auth_username,username\n";
    $conf .= "rtp_symmetric={$rtp_symmetric}\n";
    $conf .= "rewrite_contact=yes\n";
    $conf .= "force_rport=yes\n";
    $conf .= "direct_media=no\n";
    $conf .= "dtmf_mode=rfc4733\n";
    $conf .= "rtp_timeout=60\n";
    $conf .= "rtp_timeout_hold=300\n\n";

    // WebRTC (tarayıcı/WSS) istemcileri: DTLS-SRTP, ICE, AVPF
    $conf .= "[endpoint-wss](!)\n";
    $conf .= "type=endpoint\n";
    $conf .= "context=from-internal-pbx\n";
    $conf .= "disallow=all\n";
    $conf .= "allow={$webrtc_codecs}\n";
    $conf .= "transport=transport-ws\n";
    $conf .= "identify_by=auth_username,username\n";
    $conf .= "dtmf_mode=rfc4733\n";
    $conf .= "rtp_timeout=30\n";
    $conf .= "rtp_timeout_hold=300\n";
    $conf .= "webrtc=yes\n";
    $conf .= "rtcp_mux=yes\n";
    $conf .= "direct_media={$direct_media}\n";
    $conf .= "media_use_received_transport=yes\n";
    $conf .= "ice_support=yes\n";
    $conf .= "use_avpf=yes\n";
    $conf .= "media_encryption=dtls\n";
    $conf .= "dtls_verify=fingerprint\n";
    $conf .= "dtls_setup=actpass\n";
    $conf .= "dtls_cert_file=" . PJSIP_DTLS_CERT . "\n";
    $conf .= "dtls_ca_file=" . PJSIP_DTLS_CERT . "\n";
    $conf .= "rtp_symmetric={$rtp_symmetric}\n";
    $conf .= "rewrite_contact=yes\n";
    $conf .= "force_rport=yes\n\n";

    $conf .= "[auth-userpass](!)\n";
    $conf .= "type=auth\n";
    $conf .= "auth_type=userpass\n\n";

    // Dual-Endpoint AOR izolasyonu: Her endpoint YALNIZCA kendi AOR'una baglanir.
    // Capraz baglama YAPILMAZ: PJSIP_DIAL_CONTACTS(<ext>-sip) endpoint'in TUM
    // AOR'larini tarar; -sip endpoint'i -webrtc AOR'una bagliysa webphone
    // kontagi DTLS'siz endpoint konfigurasyonuyla aranir ve tarayici
    // "Called with SDP without DTLS fingerprint" hatasi verir. Paralel calma
    // dialplan tarafinda C_SIP & C_WEB birlestirilerek saglanir.
    // (remove_existing=no → ayni turden ikinci cihaz birinciyi silmez)
    $conf .= "[aor-dual](!)\n";
    $conf .= "type=aor\n";
    $conf .= "max_contacts=10\n";
    $conf .= "remove_existing=no\n";
    $conf .= "default_expiration=1800\n";
    $conf .= "maximum_expiration=3600\n";
    $conf .= "minimum_expiration=60\n";
    $conf .= "qualify_frequency={$qualify_frequency}\n\n";

    // Mobil WebRTC AOR Sablonu (M6):
    // Tek mobil cihaz, yeni baglanti geldiginde eski olu kontak derhal silinir
    $conf .= "[aor-mobile](!)\n";
    $conf .= "type=aor\n";
    $conf .= "max_contacts=1\n";
    $conf .= "remove_existing=yes\n";
    $conf .= "default_expiration=1800\n";
    $conf .= "maximum_expiration=3600\n";
    $conf .= "minimum_expiration=60\n";
    $conf .= "qualify_frequency={$qualify_frequency_mobile}\n\n";

    // 2. Active Extension Endpoints (Driven by `sip` Key-Value Data)
    // Identify bloklarinda kabul edilecek From host'lari (tek sefer hesaplanir).
    $identify_hosts = pjsipIdentifyHosts();
    $identify_host_re = implode('|', array_map(function ($h) {
        return str_replace(['.', '-'], ['\\.', '\\-'], $h);
    }, $identify_hosts));

    foreach ($users as $u) {
        $ext = preg_replace('/[^0-9]/', '', (string)$u['extension']);
        if ($ext === '') continue;
        $name = toCleanAscii($u['full_name']);

        // Fetch settings from `sip` table (or fallback to sync)
        $sip_map = SIPHelper::getSettingsMap($ext);
        if (empty($sip_map)) {
            SIPHelper::syncExtensionToSIP($ext, $u['full_name'], $u['sip_password'], $u['sip_auth_digest'] ?? 1);
            $sip_map = SIPHelper::getSettingsMap($ext);
        }

        $secret = !empty($sip_map['secret']) ? $sip_map['secret'] : (!empty($u['sip_password']) ? $u['sip_password'] : 'Pass' . $ext . '!');
        $auth_digest = isset($u['sip_auth_digest']) ? (intval($u['sip_auth_digest']) === 1) : true;
        if (isset($sip_map['auth_digest']) && !isset($u['sip_auth_digest'])) {
            $auth_digest = !in_array(strtolower($sip_map['auth_digest']), ['no', '0', 'false', 'off'], true);
        }
        // Kullanicinin giden rota grubu context'i belirler. Grup 1 (varsayilan)
        // eski adi kullanir; boylece grup atanmamis kurulumlarda hicbir ucun
        // context'i degismez. Diger gruplar kendi context'ine gider ve yalnizca
        // o gruptaki giden rotalari gorur.
        //
        // sip tablosunda elle bir context tanimlanmissa o kazanir (ozel durumlar
        // icin kacis yolu).
        $grup = max(1, intval($u['outbound_group'] ?? 1));
        $grup_context = ($grup > 1) ? "from-internal-g{$grup}" : 'from-internal-pbx';
        $context = !empty($sip_map['context']) ? $sip_map['context'] : $grup_context;
        $callerid = !empty($sip_map['callerid']) ? $sip_map['callerid'] : "\"{$name}\" <{$ext}>";
        $transport = !empty($sip_map['transport']) ? $sip_map['transport'] : 'transport-wss';
        $max_contacts = !empty($sip_map['max_contacts']) ? $sip_map['max_contacts'] : '5';

        // Kullanıcının dahili/harici arama CID tercihleri kanal değişkeni olarak
        // endpoint'e gömülür; [from-internal-outbound] rota tipine göre bunlardan
        // birini CALLERID(num) olarak uygular (bkz. SyncDialplan.php).
        $cid_internal = toCleanAscii($u['cid_internal'] ?? '');
        $cid_external = toCleanAscii($u['cid_external'] ?? '');
        $role = trim($u['role'] ?? '');
        $set_vars = "set_var=CID_INTERNAL={$cid_internal}\nset_var=CID_EXTERNAL={$cid_external}\nset_var=USER_ROLE={$role}\n";

        // Grup çekme (Pickup) için: aynı pickup_group'taki dahililer birbirinin
        // çalan çağrısını *20 (bkz. SyncFeatureCodes.php) ile çekebilir.
        $pickup_group = trim($u['pickup_group'] ?? '');
        $pickup_lines = '';
        if ($pickup_group !== '') {
            $pickup_lines = "named_call_group={$pickup_group}\nnamed_pickup_group={$pickup_group}\n";
        }

        $conf .= "; Extension {$ext}: {$name} (Dual-Endpoint: Standart SIP + WebRTC)\n";
        $conf .= "[{$ext}-sip](endpoint-sip)\n";
        if ($auth_digest) {
            $conf .= "auth=auth{$ext}-sip\n";
        }
        $conf .= "aors={$ext}-sip,{$ext}\n";
        $conf .= "context={$context}\n";
        $conf .= "callerid={$callerid}\n";
        $conf .= $set_vars;
        $conf .= $pickup_lines;

        if ($transport !== 'transport-wss') {
            $conf .= "transport={$transport}\n";
        }

        // Pass-through any extra custom PJSIP parameters stored in `sip` table.
        // WebRTC'ye özgü anahtarlar (dtls/ice/avpf/direct_media) standart SIP
        // endpoint'ine ASLA yazılmaz — masa telefonları bu parametrelerle uyumsuzdur.
        $ignore_keys = ['type', 'account', 'secret', 'context', 'callerid', 'transport', 'max_contacts', 'remove_existing', 'auth_digest'];
        $sip_blocked = [
            'disallow', 'allow', 'rtp_symmetric', 'rewrite_contact', 'force_rport',
            'direct_media', 'ice_support', 'use_avpf', 'media_encryption',
            'media_encryption_optimistic', 'dtls_verify', 'dtls_setup',
            'dtls_cert_file', 'dtls_ca_file', 'dtls_rekey', 'force_avp'
        ];
        foreach ($sip_map as $k => $v) {
            if (in_array($k, $ignore_keys) || $v === '') continue;
            if (!in_array($k, $sip_blocked)) {
                $conf .= toCleanAscii($k) . "=" . toCleanAscii($v) . "\n";
            }
        }
        $conf .= "\n";

        $conf .= "[{$ext}-webrtc](endpoint-wss)\n";
        $conf .= "auth=auth{$ext}-webrtc\n";
        $conf .= "aors={$ext}-webrtc\n";
        $conf .= "context={$context}\n";
        $conf .= "callerid={$callerid}\n";
        $conf .= $set_vars;
        $conf .= $pickup_lines . "\n";

        $conf .= "[{$ext}-mob-webrtc](endpoint-wss)\n";
        $conf .= "auth=auth{$ext}-mob-webrtc\n";
        $conf .= "aors={$ext}-mob-webrtc\n";
        $conf .= "context={$context}\n";
        $conf .= "callerid={$callerid}\n";
        $conf .= $set_vars;
        $conf .= $pickup_lines . "\n";

        if ($auth_digest) {
            $conf .= "[auth{$ext}-sip](auth-userpass)\n";
            $conf .= "username={$ext}\n";
            $conf .= "password={$secret}\n\n";
        }

        // Standart SIP cihazları (masaüstü/donanım telefonları, PhonerLite vb.) kullanıcı adı
        // olarak <dahili>-sip yerine doğrudan <dahili> gönderir. Asterisk PJSIP'in gelen
        // From başlığındaki dahiliyi (örn. "3001") doğru endpoint ile eşleştirebilmesi
        // için identify bloğu her zaman eklenir.
        //
        // Host kısmı santralin kendi adresleriyle sınırlandırıldı (2026-09-05,
        // bulgu2.md B2-3) — gerekçe ve ölçüm için bkz. pjsipIdentifyHosts().
        // Liste boşsa eski geniş desene düşülür.
        $conf .= "[{$ext}-sip-identify]\n";
        $conf .= "type=identify\n";
        $conf .= "endpoint={$ext}-sip\n";
        if (!empty($identify_host_re)) {
            $conf .= "match_header=From: /<?sip:{$ext}@({$identify_host_re})/\n\n";
        } else {
            $conf .= "match_header=From: /<?sip:{$ext}[@:]/\n\n";
        }

        $conf .= "[auth{$ext}-webrtc](auth-userpass)\n";
        $conf .= "username={$ext}-webrtc\n";
        $conf .= "password={$secret}\n\n";

        $conf .= "[auth{$ext}-mob-webrtc](auth-userpass)\n";
        $conf .= "username={$ext}-mob-webrtc\n";
        $conf .= "password={$secret}\n\n";

        // Önceki mantık ("değer 10'dan büyükse kullan, değilse 10 kullan") 10'u
        // aşılamaz bir TABAN yapıyordu — admin bir dahiliyi kasıtlı olarak daha
        // az eşzamanlı cihazla (ör. 2) sınırlamak istese bile bu her zaman 10'a
        // yükseltiliyordu (2026-08-21 denetiminde bulundu). Artık pozitif herhangi
        // bir yapılandırılmış değer olduğu gibi kullanılıyor, sadece eksik/geçersiz
        // (0 veya negatif) durumda 10'a düşülüyor.
        $max_c = (intval($max_contacts) > 0) ? intval($max_contacts) : 10;
        $conf .= "[{$ext}-webrtc](aor-dual)\nmax_contacts={$max_c}\n\n";
        $conf .= "[{$ext}-mob-webrtc](aor-mobile)\n\n";
        $conf .= "[{$ext}-sip](aor-dual)\nmax_contacts={$max_c}\n\n";
        $conf .= "[{$ext}](aor-dual)\nmax_contacts={$max_c}\n\n";
    }

    // Clean up old individual files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/pjsip_ext_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }
    FileHelper::deleteFile(ASTERISK_PBX_DIR . '/pjsip_00_template.conf');

    return writeConfWithRollback("pjsip_endpoints.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([
            AsteriskHelper::reloadPJSIP(),
            AsteriskHelper::reloadDialplan(),
        ], 'Dahili senkronizasyonu');
    }, 'Dahili senkronizasyonu');
}

