<?php
/**
 * Sync Ring Groups Dialplan (/etc/asterisk/pbx/extensions_ringgroups.conf)
 */

require_once __DIR__ . '/DialplanBuilders.php';

function syncRingGroups() {
    return withSyncLock('ring_groups', '__syncRingGroupsBody');
}

function __syncRingGroupsBody() {
    $db = getDB();
    $ring_groups = $db->query("SELECT * FROM pbx_ring_groups WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Native Ring Groups Dialplan Context (Auto-generated by AI PBX)\n\n";

    foreach ($ring_groups as $rg) {
        $id = intval($rg['id']);
        $num = preg_replace('/[^0-9]/', '', (string)$rg['group_number']);
        $name = toCleanAscii($rg['name']);
        $timeout = max(5, min(300, intval($rg['ring_timeout'] ?: 30)));
        $strategy = $rg['ring_strategy'] ?? 'ringall';
        $cid_prefix = trim($rg['cid_prefix'] ?? '');
        $record = !empty($rg['record_call']);

        $conf .= "; ---- Ring Group #{$id}: {$name} ({$num}) ----\n";
        $conf .= "[app-ringgroup-{$id}]\n";
        $conf .= "exten => s,1,NoOp(Ring Group {$id}: {$name} - Group Number: {$num})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";

        if ($cid_prefix !== '') {
            $clean_prefix = toCleanAscii($cid_prefix);
            $conf .= " same => n,ExecIf(\$[\"\${CALLERID(name)}\" != \"\"]?Set(CALLERID(name)={$clean_prefix} \${CALLERID(name)}):Set(CALLERID(name)={$clean_prefix} \${CALLERID(num)}))\n";
        }

        if ($record) {
            $conf .= " same => n,GotoIf(\$[\"\${MIXMONITOR_FILENAME}\" != \"\"]?rg_rec_exists_{$id})\n";
            $conf .= " same => n,Set(REC_FILE=/var/spool/asterisk/monitor/rg_\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}.wav)\n";
            $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
            $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            $conf .= " same => n(rg_rec_exists_{$id}),NoOp(Ring Group Record: \${MIXMONITOR_FILENAME})\n";
        }

        // Parse numbers list (comma/space/newline separated)
        $raw_numbers = preg_split('/[\s,;]+/', trim($rg['numbers_list'] ?? ''));
        $channels = [];
        foreach ($raw_numbers as $entry) {
            $entry = preg_replace('/[^0-9+]/', '', trim($entry));
            if ($entry === '') continue;

            // Dahili numara kontrolü (5 haneye kadar veya dahili veritabanında kayıtlı)
            if (strlen($entry) <= 5 && !str_starts_with($entry, '0')) {
                $channels[] = "Local/{$entry}@from-internal-pbx-ortak/n";
            } else {
                // Harici numara (dış hat rotaları üzerinden)
                $channels[] = "Local/{$entry}@from-internal-outbound-1/n";
            }
        }
        $channels = array_values(array_unique($channels));

        if (empty($channels)) {
            $conf .= " same => n,NoOp(Ring Group {$id} icinde aranacak numara yok)\n";
        } elseif ($strategy === 'sequential') {
            $step_timeout = max(5, intval($timeout / max(1, count($channels))));
            foreach ($channels as $idx => $chan) {
                $conf .= " same => n,Dial({$chan},{$step_timeout},tT)\n";
                $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?rg_done_{$id})\n";
            }
        } else {
            // 'ringall' veya 'random' (varsayılan: tüm hedefleri aynı anda çaldır)
            if ($strategy === 'random') {
                shuffle($channels);
            }
            $dial_str = implode('&', $channels);
            $conf .= " same => n,Dial({$dial_str},{$timeout},tT)\n";
            $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?rg_done_{$id})\n";
        }

        // Fallback Hedefi
        $fallback = buildDestinationLines($rg['fallback_dest_type'] ?? 'hangup', $rg['fallback_dest_id'] ?? 'busy');
        $conf .= " same => n,NoOp(Ring Group {$id} cevap verilmedi -> Fallback)\n";
        $conf .= $fallback . "\n";
        $conf .= " same => n(rg_done_{$id}),Hangup()\n\n";
    }

    return writeConfWithRollback('extensions_ringgroups.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Çalma Grupları senkronizasyonu');
    }, 'Çalma Grupları senkronizasyonu');
}
