<?php
/**
 * Time Condition Sync Module (/etc/asterisk/pbx/extensions_timecondition_<id>.conf)
 */

function syncTimeCondition($tc_id) {
    // Diğer domainlerden farklı olarak her zaman koşulu KENDİ dosyasına
    // yazıyor (extensions_timecondition_<id>.conf) — bu yüzden kilit ID
    // bazlı: farklı zaman koşullarının eşzamanlı düzenlenmesi birbirini
    // beklemez, sadece AYNI ID'ye yapılan eşzamanlı çağrılar serileşir.
    // (syncAllTimeConditions() bu fonksiyonu döngüyle çağırır — kilidi
    // burada değil ID bazlı tutmak, kendi kendine deadlock oluşturmaz.)
    return withSyncLock('timecondition_' . intval($tc_id), function() use ($tc_id) {
        return __syncTimeConditionBody($tc_id);
    });
}

function __syncTimeConditionBody($tc_id) {
    $db = getDB();
    $st = $db->prepare("SELECT * FROM pbx_time_conditions WHERE id = ?");
    $st->execute([$tc_id]);
    $tc = $st->fetch();

    $filename = "extensions_timecondition_{$tc_id}.conf";
    $filepath = ASTERISK_PBX_DIR . '/' . $filename;

    if (!$tc || intval($tc['is_active']) !== 1) {
        FileHelper::deleteFile($filepath);
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Zaman Koşulu senkronizasyonu');
        return true;
    }

    $title = toCleanAscii($tc['title']);

    // Kural listesi: [{time_group_id, match_dest_type, match_dest_id}, ...]
    // TimeConditionService::saveTimeCondition() ile aynı şemayı kullanır.
    // Sırayla değerlendirilir, zamanı tutan İLK kural kazanır. rules_json
    // boşsa (eski/tek kurallı kayıt) düz kolonlar tek kural olarak kullanılır.
    $rule_defs = [];
    if (!empty($tc['rules_json'])) {
        $decoded = json_decode($tc['rules_json'], true);
        if (is_array($decoded)) {
            foreach ($decoded as $er) {
                if (!empty($er['time_group_id']) && !empty($er['match_dest_type'])) {
                    $rule_defs[] = $er;
                }
            }
        }
    }
    if (empty($rule_defs) && intval($tc['time_group_id']) > 0) {
        $rule_defs[] = [
            'time_group_id' => $tc['time_group_id'],
            'match_dest_type' => $tc['match_dest_type'],
            'match_dest_id' => $tc['match_dest_id']
        ];
    }

    $day_map = [1=>'mon', 2=>'tue', 3=>'wed', 4=>'thu', 5=>'fri', 6=>'sat', 7=>'sun'];
    $resolved_rules = [];
    $tatiller = [];
    foreach ($rule_defs as $rd) {
        $tg_st = $db->prepare("SELECT * FROM pbx_time_groups WHERE id = ? AND is_active = 1");
        $tg_st->execute([intval($rd['time_group_id'])]);
        $tg = $tg_st->fetch();
        if (!$tg) continue;

        $t_start = substr($tg['time_start'] ?? '08:30:00', 0, 5);
        $t_end = substr($tg['time_end'] ?? '17:30:00', 0, 5);
        $days_raw = $tg['days_of_week'] ?? '1,2,3,4,5';

        $ast_days = [];
        foreach (explode(',', $days_raw) as $d) {
            $d = trim($d);
            if (isset($day_map[$d])) $ast_days[] = $day_map[$d];
        }

        $days_str = '*';
        if (count($ast_days) === 5 && !array_diff(['mon','tue','wed','thu','fri'], $ast_days)) {
            $days_str = 'mon-fri';
        } elseif (!empty($ast_days)) {
            $days_str = implode('&', $ast_days);
        }

        // Tatil gunleri. `holidays_json` panelde kaydediliyordu ama dialplan'a
        // HIC yazilmiyordu: kullanici tatil girse de o gun normal mesai gibi
        // yonlendiriliyordu (2026-09-01 alan denetiminde bulundu).
        foreach ((array)json_decode($tg['holidays_json'] ?? '[]', true) as $h) {
            $h = trim((string)$h);
            // Yalnizca YYYY-AA-GG kabul edilir; baska bir sey dialplan'a girmez.
            if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $h)) $tatiller[$h] = true;
        }

        $resolved_rules[] = [
            'time' => "{$t_start}-{$t_end}",
            'days' => $days_str,
            'match_dest_type' => $rd['match_dest_type'],
            'match_dest_id' => $rd['match_dest_id'] ?? ''
        ];
    }

    $conf = "; Native Dialplan Time Condition ID {$tc_id}: {$title} (Auto-generated by AI PBX)\n";
    $conf .= "[app-timecondition-{$tc_id}]\n";
    $conf .= "exten => s,1,NoOp(Evaluating Native Time Condition ID {$tc_id}: {$title})\n";

    // Tatil kontrolu mesai kurallarindan ONCE gelir: tatil gunu hangi gune
    // denk gelirse gelsin kapali sayilir.
    //
    // GotoIfTime'in YIL alani yok, bu yuzden tam tarih karsilastiriliyor —
    // aksi halde "2026-01-01" her yil tekrar ederdi.
    if (!empty($tatiller)) {
        $conf .= " same => n,Set(BUGUN=\${STRFTIME(\${EPOCH},,%Y-%m-%d)})\n";
        foreach (array_keys($tatiller) as $h) {
            $conf .= " same => n,GotoIf(\$[\"\${BUGUN}\" = \"{$h}\"]?tc_nomatch)\n";
        }
    }

    foreach ($resolved_rules as $i => $r) {
        $conf .= " same => n,GotoIfTime({$r['time']},{$r['days']},*,*?tc_rule_{$i})\n";
    }
    $conf .= " same => n,Goto(tc_nomatch)\n\n";

    foreach ($resolved_rules as $i => $r) {
        $rule_num = $i + 1;
        $conf .= " same => n(tc_rule_{$i}),NoOp(Time Condition {$tc_id} Rule {$rule_num} Matched -> {$r['match_dest_type']})\n";
        $conf .= buildDestinationLines($r['match_dest_type'], $r['match_dest_id']) . "\n\n";
    }

    $conf .= " same => n(tc_nomatch),NoOp(Time Condition {$tc_id} Not Matched -> {$tc['nomatch_dest_type']})\n";
    $conf .= buildDestinationLines($tc['nomatch_dest_type'], $tc['nomatch_dest_id']) . "\n\n";

    $conf .= " same => n,Hangup()\n";

    return writeConfWithRollback($filename, $conf, function() use ($tc_id) {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], "Zaman Koşulu #{$tc_id} senkronizasyonu");
    }, "Zaman Koşulu #{$tc_id} senkronizasyonu");
}

function syncAllTimeConditions() {
    $db = getDB();
    $tcs = $db->query("SELECT id FROM pbx_time_conditions WHERE is_active = 1")->fetchAll(PDO::FETCH_COLUMN);
    $active_files = [];

    foreach ($tcs as $id) {
        syncTimeCondition($id);
        $active_files[] = "extensions_timecondition_{$id}.conf";
    }

    $all_files = glob(ASTERISK_PBX_DIR . '/extensions_timecondition_*.conf');
    foreach ($all_files as $f) {
        $b = basename($f);
        if (!in_array($b, $active_files)) {
            FileHelper::deleteFile($f);
        }
    }

    AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Zaman Koşulu toplu senkronizasyonu');
    return true;
}
