<?php
/**
 * Sync Music on Hold (/etc/asterisk/pbx/musiconhold_pbx.conf)
 */
function syncAsteriskMOH() {
    return withSyncLock('moh', '__syncAsteriskMOHBody');
}

function __syncAsteriskMOHBody() {
    $db = getDB();
    $classes = $db->query("SELECT * FROM pbx_moh_classes WHERE is_active = 1 ORDER BY name ASC")->fetchAll();

    $conf = "; Native Music On Hold Configuration (Auto-generated by AI PBX)\n\n";

    if (!empty($classes)) {
        foreach ($classes as $c) {
            $name = trim($c['name']);
            $directory = trim($c['directory']);
            $sort = trim($c['sort'] ?? 'alpha');

            $conf .= "[{$name}]\n";
            $conf .= "mode=files\n";
            $conf .= "directory={$directory}\n";
            $conf .= "sort={$sort}\n\n";
        }
    } else {
        $conf .= "[default]\n";
        $conf .= "mode=files\n";
        $conf .= "directory=/var/lib/asterisk/moh\n";
        $conf .= "sort=alpha\n\n";
    }

    return writeConfWithRollback('musiconhold_pbx.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadMOH()], 'MOH senkronizasyonu');
    }, 'MOH senkronizasyonu');
}
