<?php
/**
 * Single Master File Queue Sync Module (/etc/asterisk/pbx/queues_pbx.conf)
 * Consolidates all active call center queues into a single master configuration file reading from `queues_details` key-value table.
 */

require_once __DIR__ . '/../queue_helper.php';

function syncQueue($queue_id) {
    return syncAllQueues();
}

function syncAllQueues() {
    return withSyncLock('queues', '__syncAllQueuesBody');
}

function __syncAllQueuesBody() {
    $db = getDB();
    $queues = $db->query("SELECT * FROM pbx_queues WHERE is_active = 1 ORDER BY queue_name ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; ==========================================================\n";
    $conf .= "; Master Call Center Queues Configuration (Auto-generated by AI PBX via queues_details DB)\n";
    $conf .= "; ==========================================================\n\n";

    $conf .= "[general]\n";
    $conf .= "persistentmembers = yes\n";
    $conf .= "autofill = yes\n";
    $conf .= "monitor-type = MixMonitor\n";
    $conf .= "queue_log = yes\n\n";

    foreach ($queues as $q) {
        $q_name = $q['queue_name'];
        $title = toCleanAscii($q['title']);
        $musicclass = toCleanAscii(!empty($q['musicclass']) ? $q['musicclass'] : 'default');

        // Fetch details map from `queues_details` table
        $q_map = QueueHelper::getDetailsMap($q_name);
        if (empty($q_map)) {
            QueueHelper::syncQueueToDetails($q);
            $q_map = QueueHelper::getDetailsMap($q_name);
        }

        $conf .= "; Call Center Queue ID {$q['id']}: {$title} ({$q_name})\n";
        $conf .= "[{$q_name}]\n";
        $conf .= "musicclass={$musicclass}\n";

        // Output all key-value directives stored in `queues_details`
        foreach ($q_map as $k => $v) {
            if ($v === '' || $v === null) continue;
            $conf .= toCleanAscii($k) . "=" . toCleanAscii($v) . "\n";
        }

        // Static agents: a member loaded from the config is not "dynamic" for
        // Asterisk, cannot be removed with "queue remove member", only paused.
        // The interface/state_interface are kept exactly the same as the dynamic
        // entry (QueueHelper::setMembership) — otherwise the same agent would
        // show up as two separate members.
        foreach (QueueHelper::staticMembersOf($q) as $s_ext) {
            $s_ext = preg_replace('/[^0-9]/', '', $s_ext);
            if ($s_ext === '') continue;
            $conf .= "member => Local/{$s_ext}@from-internal-pbx/n,0,Agent {$s_ext},hint:{$s_ext}@from-internal-pbx\n";
        }
        $conf .= "\n";
    }

    // Delete old individual queue files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/queue_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }

    $result = writeConfWithRollback("queues_pbx.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadQueue('all')], t('sync.ctx_queues'));
    }, t('sync.ctx_queues'));

    foreach ($queues as $q) {
        purgeStaticFromPersistentMembers($q['queue_name'], QueueHelper::staticMembersOf($q));
    }

    return $result;
}

/**
 * The old entry of an agent switched from dynamic to static stays in the
 * Queue/PersistentMembers/<queue> value in astdb (Asterisk rewrites that value
 * only when a dynamic member is added or removed). Without cleaning it, on an
 * Asterisk restart the agent no longer in the config (removed from static)
 * would come back to the queue as a dynamic member. The value consists of
 * "|"-separated "interface;penalty;paused;..." entries (app_queue
 * dump_queue_members).
 */
function purgeStaticFromPersistentMembers($q_name, array $static_exts) {
    if (empty($static_exts)) return;
    @exec("asterisk -rx " . escapeshellarg("database get Queue/PersistentMembers $q_name"), $out);
    $value = null;
    foreach ($out ?: [] as $line) {
        if (strpos($line, 'Value: ') === 0) $value = substr($line, 7);
    }
    if ($value === null || $value === '') return;

    $static_ifaces = array_map(fn($e) => "Local/{$e}@from-internal-pbx/n", $static_exts);
    $entries = explode('|', $value);
    $kept = array_filter($entries, fn($entry) => !in_array(explode(';', $entry)[0], $static_ifaces, true));
    if (count($kept) === count($entries)) return;

    if (empty($kept)) {
        @exec("asterisk -rx " . escapeshellarg("database del Queue/PersistentMembers $q_name"));
    } else {
        @exec("asterisk -rx " . escapeshellarg("database put Queue/PersistentMembers $q_name \"" . str_replace('"', '', implode('|', $kept)) . "\""));
    }
}

