<?php
/**
 * Sync Outbound Routes Dialplan (/etc/asterisk/pbx/extensions_outbound.conf)
 */
/*
 * MixMonitor'da `b` secenegi KULLANILMIYOR.
 *
 * `b` yalnizca cagri koprulendikten sonra yazmaya baslar; anons, calma ve
 * tuslama kayda girmez. Ustelik bekleneni de yapmiyor: cagri hic
 * koprulenmezse dosya yine olusuyor, sadece ICI BOS kaliyor (44 bayt, salt
 * WAV basligi — 2026-09-01'de giden cagri kayitlarinda goruldu). Yani bos
 * dosya birikmesini de onlemiyor.
 */
function syncOutboundDialplan() {
    return withSyncLock('outbound_dialplan', '__syncOutboundDialplanBody');
}

function __syncOutboundDialplanBody() {
    // Trunk kanal sinirlari. Rotanin trunks_json'inda bu bilgi yok; sinir
    // trunk'in kendi kaydinda (pbx_trunks.max_channels) tutuluyor.
    $trunk_limitleri = [];
    foreach (getDB()->query("SELECT trunk_name, max_channels FROM pbx_trunks")->fetchAll(PDO::FETCH_ASSOC) as $tl) {
        $trunk_limitleri[$tl['trunk_name']] = intval($tl['max_channels']);
    }

    $db = getDB();
    $routes = $db->query("SELECT * FROM pbx_outbound_routes WHERE is_active = 1 ORDER BY id ASC")->fetchAll();
    $external_dial_timeout = intval(getSystemSetting('pjsip_external_dial_timeout', '60'));

    // Rotalar gruba gore ayrilir. Her grup kendi context'ini alir; kullanici
    // hangi gruptaysa yalnizca o gruptaki rotalari kullanabilir.
    //
    // Grup 1 ayrica [from-internal-outbound] adiyla da uretilir: mevcut uclar
    // ve kuyruklardaki Local/...@from-internal-pbx cagrilari bu ada bagli,
    // yani grup atanmamis kurulumlarda hicbir sey degismez.
    $gruplar = [];
    foreach ($routes as $r) {
        $g = max(1, intval($r['route_group'] ?? 1));
        $gruplar[$g][] = $r;
    }
    if (empty($gruplar)) {
        $gruplar[1] = [];
    }
    ksort($gruplar);

    $conf = "; Native Outbound Dialplan Context (Auto-generated by AI PBX)\n\n";

    foreach ($gruplar as $grup_no => $grup_rotalari) {
        $conf .= "; ---- Giden Rota Grubu {$grup_no} ----\n";
        $conf .= "[from-internal-outbound-{$grup_no}]\n\n";
        $routes = $grup_rotalari;

    if (!empty($routes)) {
        foreach ($routes as $r) {
            $name = toCleanAscii($r['route_name']);
            $pattern = preg_replace('/[^0-9NXZnxz.\[\]_!*#-]/', '', trim($r['match_pattern']));
            $prepend = preg_replace('/[^0-9]/', '', trim($r['prepend'] ?? ''));
            $append = preg_replace('/[^0-9]/', '', trim($r['append'] ?? ''));
            $strip_front = intval($r['strip_front'] ?? 0);
            $strip_back = intval($r['strip_back'] ?? 0);
            $is_internal = !empty($r['is_internal']);

            // Dış hat listesi: birincil/yedek ayrımı yok — tek tek eklenen, sırasıyla
            // denenen bir zincir. Her girişin kendi Caller ID maskeleme değeri olabilir.
            // Boş/tanımsız trunk adları elenir; hiç trunk kalmazsa (yeni/boş kurulum)
            // sistemdeki tek aktif trunk'a düşülür, o da yoksa Congestion() ile biter.
            $trunks_raw = !empty($r['trunks_json']) ? (json_decode($r['trunks_json'], true) ?: []) : [];
            $trunk_chain = [];
            foreach ($trunks_raw as $t) {
                $tn = trim($t['trunk_name'] ?? '');
                if ($tn === '') continue;
                $trunk_chain[] = ['trunk_name' => $tn, 'callerid_override' => trim($t['callerid_override'] ?? ''), 'max_channels' => intval($trunk_limitleri[$tn] ?? 0)];
            }
            if (empty($trunk_chain)) {
                $fallback = AsteriskHelper::getPrimaryTrunkName();
                if ($fallback !== null) {
                    $trunk_chain[] = ['trunk_name' => $fallback, 'callerid_override' => '', 'max_channels' => 0];
                }
            }

            $trunk_label = !empty($trunk_chain) ? implode(' -> ', array_column($trunk_chain, 'trunk_name')) : 'YOK (tanımlı/aktif trunk bulunamadı)';
            $conf .= "; Outbound Route: {$name} (Pattern: {$pattern} -> Trunk: {$trunk_label})\n";
            $conf .= "exten => {$pattern},1,NoOp(Outbound Call via Route {$name} -> Trunk {$trunk_label})\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";

            if (empty($trunk_chain)) {
                $conf .= " same => n,NoOp(Bu rota icin tanimli/aktif bir dis hat yok)\n";
                $conf .= " same => n,Congestion(10)\n";
                $conf .= " same => n,Hangup(34)\n\n";
                continue;
            }

            // Numara dönüşümü: önce baştan/sondan silme, sonra ön ek/son ek eklenir.
            // Asterisk ${VAR:offset:length} negatif length ile "sondan N karakter" ifade eder.
            $core = "\${EXTEN}";
            if ($strip_front > 0 || $strip_back > 0) {
                $core = ($strip_back > 0) ? "\${EXTEN:{$strip_front}:-{$strip_back}}" : "\${EXTEN:{$strip_front}}";
            }
            $dial_num = $prepend . $core . $append;

            // İlk denenecek trunk'ın CID'i, kayıt dosyası adı belirlenmeden önce uygulanır.
            $conf .= buildTrunkCallerIdLine($trunk_chain[0], $is_internal);

            $conf .= " same => n,Set(REC_FILE=/var/spool/asterisk/monitor/outbound_\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}_to_{$dial_num}.wav)\n";
            $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
            $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            $conf .= " same => n,Set(CHANNEL(accountcode)=\${CALLERID(num)})\n";

            // Sırayla dene: bir trunk CHANUNAVAIL/CONGESTION dönerse bir sonrakine geç.
            // Her deneme kendi trunk'ının CID'ini uygular (ilk deneme yukarıda zaten uygulandı).
            $count = count($trunk_chain);
            foreach ($trunk_chain as $idx => $t) {
                $step = $idx + 1;
                if ($idx > 0) {
                    $conf .= " same => n(try{$step}),NoOp(Trying trunk {$t['trunk_name']})\n";
                    $conf .= buildTrunkCallerIdLine($t, $is_internal);
                }
                // Trunk kanal siniri. `max_channels` panelde giriliyor ve
                // veritabanina yaziliyordu ama dialplan'a HIC yansimiyordu:
                // "en fazla N kanal" denmesine ragmen sinirsiz arama
                // yapiliyordu (2026-09-01 alan denetimi).
                //
                // GROUP sayaci kanal bazlidir; cagri bitince Asterisk kendisi
                // dusurur. Sinir dolduysa bu trunk CONGESTION saydirilir ki
                // zincirdeki bir sonraki trunk denensin.
                $limit = intval($t['max_channels'] ?? 0);
                if ($limit > 0) {
                    $conf .= " same => n,Set(GROUP(trunk)={$t['trunk_name']})\n";
                    $conf .= " same => n,GotoIf(\$[\${GROUP_COUNT(" . $t['trunk_name'] . "@trunk)} > {$limit}]?trunkfull{$step})\n";
                }
                // D-1: 'r' seçeneği kaldırıldı (yalnızca 'T' kullanılıyor).
                // Böylece operatörün erken medyası (183 Session Progress / anons / gerçek meşgul tonu)
                // arayana doğrudan iletilir, yapay yerel zil ile maskelenmez.
                $conf .= " same => n,Set(JITTERBUFFER(adaptive)=default)\n";
                $conf .= " same => n,Dial(PJSIP/{$dial_num}@{$t['trunk_name']},{$external_dial_timeout},Tb(sub-callee-jb^s^1))\n";
                if ($limit > 0) {
                    $conf .= " same => n,Goto(afterdial{$step})\n";
                    $conf .= " same => n(trunkfull{$step}),NoOp(Trunk {$t['trunk_name']} kanal siniri dolu: {$limit})\n";
                    $conf .= " same => n,Set(DIALSTATUS=CONGESTION)\n";
                    $conf .= " same => n(afterdial{$step}),NoOp()\n";
                }
                if ($step < $count) {
                    $next = $step + 1;
                    $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\"=\"CHANUNAVAIL\"|\"\${DIALSTATUS}\"=\"CONGESTION\"]?try{$next}:donecall)\n";
                }
            }
            // D-2: Dial bitiminde argümansız Hangup yerine gerçek DIALSTATUS ve HANGUPCAUSE
            // kodlarını SIP tarafına ileten durum yöneticisine dallanılır.
            $done_label = ($count > 1) ? '(donecall)' : '';
            $conf .= " same => n{$done_label},Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
        }
    } else {
        $fallback_trunk = AsteriskHelper::getPrimaryTrunkName();
        $conf .= "; Fallback Outbound Route\n";
        if ($fallback_trunk === null) {
            $conf .= "; Henuz hicbir trunk/dis hat tanimlanmadi - giden arama devre disi.\n";
            $conf .= "exten => _NXXXXXX,1,NoOp(No trunk configured)\n";
            $conf .= " same => n,Congestion(10)\n";
            $conf .= " same => n,Hangup(34)\n\n";
            $conf .= "exten => _05XXXXXXXXX,1,NoOp(No trunk configured)\n";
            $conf .= " same => n,Congestion(10)\n";
            $conf .= " same => n,Hangup(34)\n\n";
        } else {
            $conf .= "exten => _NXXXXXX,1,NoOp(Fallback Outbound Call)\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Dial(PJSIP/\${EXTEN}@{$fallback_trunk},{$external_dial_timeout},T)\n";
            $conf .= " same => n,Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
            $conf .= "exten => _05XXXXXXXXX,1,NoOp(Fallback Mobile Outbound Call)\n";
            $conf .= " same => n,Set(CDR(direction)=outbound)\n";
            $conf .= " same => n,Dial(PJSIP/\${EXTEN}@{$fallback_trunk},{$external_dial_timeout},T)\n";
            $conf .= " same => n,Goto(sub-outbound-status,\${IF($[\"\${DIALSTATUS}\" != \"\"]?\${DIALSTATUS}:NOANSWER)},1)\n\n";
        }
    }
    } // grup dongusu sonu

    // Grup 1'i eski adiyla da yayinla: mevcut uclarin context'i ve
    // kuyruklardaki Local/...@from-internal-pbx cagrilari bu ada bagli.
    // Boylece grup atanmamis kurulumlarda hicbir sey degismiyor.
    $conf .= "; ---- Geriye uyumluluk: grup 1'in eski adi ----\n";
    $conf .= "[from-internal-outbound]\n";
    $conf .= "include => from-internal-outbound-1\n\n";

    // Giden çağrı sonlandırma ve durum yönetimi (D-1 / D-2)
    // BUSY -> 486 Busy Here, CONGESTION -> 503, NOANSWER -> 480, CHANUNAVAIL -> HANGUPCAUSE (örn 404/603)
    $conf .= "; ---- Giden Cagri Durum Yonetimi (D-1 / D-2) ----\n";
    $conf .= "[sub-outbound-status]\n";
    $conf .= "exten => s,1,NoOp(Outbound Status: s - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:16)})\n\n";
    $conf .= "exten => ANSWER,1,NoOp(Outbound Status: ANSWER - Normal Hangup)\n";
    $conf .= " same => n,Hangup(16)\n\n";
    $conf .= "exten => BUSY,1,NoOp(Outbound Status: BUSY - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(17)\n\n";
    $conf .= "exten => CONGESTION,1,NoOp(Outbound Status: CONGESTION - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(34)\n\n";
    $conf .= "exten => CHANUNAVAIL,1,NoOp(Outbound Status: CHANUNAVAIL - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:1)})\n\n";
    $conf .= "exten => NOANSWER,1,NoOp(Outbound Status: NOANSWER - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(19)\n\n";
    $conf .= "exten => CANCEL,1,NoOp(Outbound Status: CANCEL)\n";
    $conf .= " same => n,Hangup(16)\n\n";
    $conf .= "exten => DONTCALL,1,Hangup(21)\n\n";
    $conf .= "exten => TORTURE,1,Hangup(21)\n\n";
    $conf .= "exten => INVALIDARGS,1,Hangup(38)\n\n";
    $conf .= "exten => i,1,NoOp(Outbound Status: Unknown status - Cause: \${HANGUPCAUSE})\n";
    $conf .= " same => n,Hangup(\${IF(\$[\"\${HANGUPCAUSE}\" != \"\" & \"\${HANGUPCAUSE}\" != \"0\"]?\${HANGUPCAUSE}:16)})\n\n";
    $conf .= "exten => e,1,Hangup(16)\n\n";
    $conf .= "exten => h,1,NoOp(Outbound Channel Hangup Complete)\n\n";

    return writeConfWithRollback('extensions_outbound.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Giden Rota senkronizasyonu');
    }, 'Giden Rota senkronizasyonu');
}
