<?php
/**
 * Sync Inbound DIDs Dialplan (/etc/asterisk/pbx/extensions_inbound.conf)
 */
function syncInboundDialplan() {
    return withSyncLock('inbound_dialplan', '__syncInboundDialplanBody');
}

function __syncInboundDialplanBody() {
    $db = getDB();
    $dids = $db->query("SELECT * FROM pbx_dids WHERE is_active = 1 ORDER BY did_number ASC")->fetchAll();
    $trunks = $db->query("SELECT * FROM pbx_trunks WHERE is_active = 1 ORDER BY trunk_name ASC")->fetchAll();

    $conf = "; ==========================================================\n";
    $conf .= "; Native Inbound DID Dialplan (Auto-generated by AI PBX)\n";
    $conf .= "; ==========================================================\n\n";

    // ------------------------------------------------------------------
    // Per-trunk inbound call handling and DID normalization
    // ------------------------------------------------------------------
    if (!empty($trunks)) {
        foreach ($trunks as $t) {
            $t_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $t['trunk_name']);
            if (empty($t_name)) continue;
            $title = toCleanAscii($t['title'] ?? $t_name);
            $trim_digits = intval($t['did_trim_digits'] ?? 0);
            $allow_outbound = !empty($t['allow_outbound_routing']);
            $route_group = max(1, intval($t['outbound_route_group'] ?? 1));
            $is_kapanma_tonu = (($t['context'] ?? '') === 'from-trunk-kapanma-tonu');

            $conf .= "; --- Trunk inbound: {$t_name} ({$title}) ---\n";
            $conf .= "[from-trunk-{$t_name}]\n";
            $conf .= "exten => _.,1,NoOp(Inbound trunk call [{$t_name}] - caller: \${CALLERID(num)} - target: \${EXTEN})\n";
            $conf .= " same => n,Set(CDR(direction)=inbound)\n";
            $conf .= " same => n,Set(CDR(inbound_trunk)={$t_name})\n";

            if ($is_kapanma_tonu) {
                // Hang-up tone detector (in-band disconnect supervision)
                $conf .= " same => n,Set(TONE_DETECT(0,,brg(kapanma-tonu,s,1))=)\n";
            }

            if ($trim_digits > 0) {
                $conf .= " same => n,Set(NORMALIZED_DID=\${IF(\$[\${LEN(\${EXTEN})} >= {$trim_digits}]?\${EXTEN:-{$trim_digits}}:\${EXTEN})})\n";
                $conf .= " same => n,NoOp(DID Kirpma uygulandi ({$trim_digits} hane): \${EXTEN} -> \${NORMALIZED_DID})\n";
            } else {
                $conf .= " same => n,Set(NORMALIZED_DID=\${EXTEN})\n";
            }

            $conf .= " same => n,Set(CDR(did)=\${NORMALIZED_DID})\n";
            $conf .= " same => n,Goto(from-trunk-{$t_name}-route,\${NORMALIZED_DID},1)\n\n";

            // For calls arriving without a DID (s)
            $conf .= "exten => s,1,NoOp(DID olmadan gelen cagri [{$t_name}] - Arayan: \${CALLERID(num)})\n";
            $conf .= " same => n,Set(CDR(direction)=inbound)\n";
            $conf .= " same => n,Set(CDR(inbound_trunk)={$t_name})\n";
            if ($is_kapanma_tonu) {
                $conf .= " same => n,Set(TONE_DETECT(0,,brg(kapanma-tonu,s,1))=)\n";
            }
            $conf .= " same => n,Set(CDR(did)=s)\n";
            $conf .= " same => n,Goto(from-trunk-{$t_name}-route,s,1)\n\n";

            // Routing context (route context)
            $conf .= "[from-trunk-{$t_name}-route]\n";
            $conf .= "; 1. Defined inbound routes (DID rules)\n";
            $conf .= "include => from-trunk-inbound\n";

            if ($allow_outbound) {
                $conf .= "; 2. Trunk-to-trunk / transit: outbound routes (group {$route_group})\n";
                $conf .= "include => from-internal-outbound-{$route_group}\n";
                $conf .= "; 3. Extensions & internal numbers\n";
                $conf .= "include => from-internal-pbx-ortak\n";
            }

            $conf .= "; 4. Closing for unmatched routes\n";
            $conf .= "include => from-trunk-notfound\n\n";
        }
    }

    // ------------------------------------------------------------------
    // General inbound routes (DID matches)
    // ------------------------------------------------------------------
    $conf .= "[from-trunk-inbound]\n\n";

    if (!empty($dids)) {
        foreach ($dids as $d) {
            $num = preg_replace('/[^0-9]/', '', trim($d['did_number']));
            $title = toCleanAscii($d['title']);
            $conf .= "; DID: {$num} ({$title})\n";
            $conf .= "exten => {$num},1,NoOp(Inbound call for DID {$num} - {$title})\n";
            $conf .= " same => n,Set(CDR(did)={$num})\n";
            $conf .= " same => n,Set(CDR(direction)=inbound)\n";
            if (!empty($d['language'])) {
                $lang = preg_replace('/[^a-zA-Z_]/', '', $d['language']);
                $conf .= " same => n,Set(CHANNEL(language)={$lang})\n";
            }
            // Mandatory call recording.
            if (!empty($d['record_call'])) {
                $rec = "/var/spool/asterisk/monitor/inbound_"
                     . "\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${FILTER(0-9+,\${CALLERID(num)})}_to_{$num}.wav";
                $conf .= " same => n,Set(REC_FILE={$rec})\n";
                $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
                $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            }

            $conf .= buildDestinationLines($d['dest_type'], $d['dest_id'], $num) . "\n\n";
        }
    } else {
        $conf .= "; No specific DIDs configured yet\n\n";
    }

    // ------------------------------------------------------------------
    // Closing context for unmatched calls
    // ------------------------------------------------------------------
    $conf .= "[from-trunk-notfound]\n";
    $conf .= "exten => _.,1,NoOp(Eslesen gelen rota bulunamadi - DID: \${EXTEN})\n";
    $conf .= " same => n,Playtones(congestion)\n";
    $conf .= " same => n,Congestion(10)\n";
    $conf .= " same => n,Hangup(1)\n\n";

    $conf .= "exten => s,1,NoOp(Eslesen gelen rota bulunamadi - DID: s)\n";
    $conf .= " same => n,Playtones(congestion)\n";
    $conf .= " same => n,Congestion(10)\n";
    $conf .= " same => n,Hangup(1)\n\n";

    // ------------------------------------------------------------------
    // Hang-up tone detector wrapper (for backward compatibility)
    // ------------------------------------------------------------------
    $conf .= "; --- Inbound route wrapper with hang-up tone detection ---\n";
    $conf .= "[from-trunk-kapanma-tonu]\n";
    $conf .= "exten => _X.,1,NoOp(Kapanma tonu algilayicisi devrede - DID \${EXTEN})\n";
    $conf .= " same => n,Set(TONE_DETECT(0,,brg(kapanma-tonu,s,1))=)\n";
    $conf .= " same => n,Goto(from-trunk-inbound,\${EXTEN},1)\n\n";

    $conf .= "[kapanma-tonu]\n";
    $conf .= "exten => s,1,NoOp(Kapanma tonu algilandi - cagri kapatiliyor)\n";
    $conf .= " same => n,Hangup()\n\n";

    return writeConfWithRollback('extensions_inbound.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], t('sync.ctx_inbound'));
    }, t('sync.ctx_inbound'));
}
