<?php
/**
 * Single Master File IVR Sync Module (/etc/asterisk/pbx/extensions_ivrs.conf)
 * Consolidates all active IVR menus into a single master dialplan file.
 */

function syncIVR($ivr_id) {
    return syncAllIVRs();
}

function syncAllIVRs() {
    return withSyncLock('ivrs', '__syncAllIVRsBody');
}

/**
 * Tek bir IVR menüsünün dialplan bloğunu üretir — saf fonksiyon (DB'ye dokunmaz,
 * test edilebilir olsun diye __syncAllIVRsBody()'den çıkarıldı).
 *
 * max_failures: "i" (geçersiz tuşlama) her tetiklendiğinde kanal bazlı bir
 * sayaç (IVR{id}FAILS) artırılır; sayaç eşiğin altındaysa menü (s,1) baştan
 * çalınır, eşiğe ulaşınca invalid_dest_type/id hedefine düşülür. Zaman aşımı
 * (t) bu sayaca dahil değildir, davranışı değişmedi.
 *
 * allow_direct_dial: açıksa, IVR menüsü çalarken aktif bir dahili numarası
 * çevrilirse doğrudan [from-internal-pbx]'teki gerçek çağrı mantığına
 * (DND/CF, dual-endpoint paralel çalma vb.) yönlendirilir — mantık burada
 * TEKRARLANMAZ, sadece Goto ile devredilir. Zaten menüde tanımlı bir tuşla
 * (digit entry) çakışan numaralar atlanır (aynı exten'in iki kez tanımlanması
 * Asterisk reload'da "already in use" uyarısına yol açar).
 */
function buildIVRDialplanBlock($ivr, $entries, $active_exts = []) {
    $ivr_id = $ivr['id'];
    $title = toCleanAscii($ivr['title']);
    $prompt = FileHelper::sanitizeAudioPath($ivr['prompt_file']);
    $timeout = intval($ivr['timeout_seconds'] ?: 10);
    $max_failures = max(1, intval($ivr['max_failures'] ?: 3));
    $fail_var = "IVR{$ivr_id}FAILS";

    $conf = "; Native Dialplan IVR Menu ID {$ivr_id}: {$title}\n";
    $conf .= "[app-ivr-{$ivr_id}]\n";
    $conf .= "exten => s,1,NoOp(Executing Native IVR ID {$ivr_id}: {$title})\n";
    $conf .= " same => n,Answer()\n";
    if (!empty($ivr['language'])) {
        $ivr_lang = preg_replace('/[^a-zA-Z_]/', '', $ivr['language']);
        $conf .= " same => n,Set(CHANNEL(language)={$ivr_lang})\n";
    }
    $conf .= " same => n,Set(TIMEOUT(digit)=3)\n";
    $conf .= " same => n,Set(TIMEOUT(response)={$timeout})\n";
    $conf .= " same => n,Background({$prompt})\n";
    $conf .= " same => n,WaitExten({$timeout})\n\n";

    $used_digits = [];
    if (!empty($entries)) {
        foreach ($entries as $e) {
            $digit = trim($e['digit']);
            $used_digits[$digit] = true;
            $conf .= "; Option Digit {$digit}\n";
            $conf .= "exten => {$digit},1,NoOp(IVR {$ivr_id} Pressed Digit {$digit} -> {$e['dest_type']})\n";
            $conf .= buildDestinationLines($e['dest_type'], $e['dest_id']) . "\n\n";
        }
    }

    if (!empty($ivr['allow_direct_dial']) && !empty($active_exts)) {
        $conf .= "; Menu sirasinda dogrudan dahili arama (allow_direct_dial)\n";
        foreach ($active_exts as $e) {
            $ext = trim($e['extension']);
            if ($ext === '' || isset($used_digits[$ext])) continue;
            $conf .= "exten => {$ext},1,NoOp(IVR {$ivr_id} Direct Dial to Extension {$ext})\n";
            $conf .= " same => n,Goto(from-internal-pbx,{$ext},1)\n\n";
        }
    }

    $conf .= "; Timeout Destination\n";
    $conf .= "exten => t,1,NoOp(IVR {$ivr_id} Timed Out -> {$ivr['timeout_dest_type']})\n";
    $conf .= buildDestinationLines($ivr['timeout_dest_type'], $ivr['timeout_dest_id']) . "\n\n";

    $conf .= "; Invalid Destination - {$max_failures} basarisiz denemeye kadar menu tekrarlanir\n";
    $conf .= "exten => i,1,NoOp(IVR {$ivr_id} Invalid Digit)\n";
    $conf .= " same => n,Set({$fail_var}=\$[\${{$fail_var}:-0}+1])\n";
    $conf .= " same => n,GotoIf(\$[\${{$fail_var}} < {$max_failures}]?s,1)\n";
    $conf .= " same => n,NoOp(IVR {$ivr_id} Max Invalid Attempts ({$max_failures}) Reached -> {$ivr['invalid_dest_type']})\n";
    $conf .= buildDestinationLines($ivr['invalid_dest_type'], $ivr['invalid_dest_id']) . "\n\n";

    $conf .= "exten => h,1,Hangup()\n\n";

    return $conf;
}

function __syncAllIVRsBody() {
    $db = getDB();
    $ivrs = $db->query("SELECT * FROM pbx_ivrs WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);
    $active_exts = $db->query("SELECT extension, full_name FROM sys_users WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip'")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; ==========================================================\n";
    $conf .= "; Master IVR Dialplan Menus (Auto-generated by AI PBX)\n";
    $conf .= "; ==========================================================\n\n";

    foreach ($ivrs as $ivr) {
        $e_st = $db->prepare("SELECT * FROM pbx_ivr_entries WHERE ivr_id = ? ORDER BY digit ASC");
        $e_st->execute([$ivr['id']]);
        $entries = $e_st->fetchAll(PDO::FETCH_ASSOC);

        $conf .= buildIVRDialplanBlock($ivr, $entries, $active_exts);
    }

    // Delete old individual IVR files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/extensions_ivr_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }

    return writeConfWithRollback("extensions_ivrs.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'IVR senkronizasyonu');
    }, 'IVR senkronizasyonu');
}
