<?php
/**
 * Sync Inbound DIDs Dialplan (/etc/asterisk/pbx/extensions_inbound.conf)
 */
function syncInboundDialplan() {
    return withSyncLock('inbound_dialplan', '__syncInboundDialplanBody');
}

function __syncInboundDialplanBody() {
    $db = getDB();
    $dids = $db->query("SELECT * FROM pbx_dids WHERE is_active = 1 ORDER BY did_number ASC")->fetchAll();

    $conf = "; Native Inbound DID Dialplan (Auto-generated by AI PBX)\n";
    $conf .= "[from-trunk-inbound]\n\n";

    if (!empty($dids)) {
        foreach ($dids as $d) {
            $num = preg_replace('/[^0-9]/', '', trim($d['did_number']));
            $title = toCleanAscii($d['title']);
            $conf .= "; DID: {$num} ({$title})\n";
            $conf .= "exten => {$num},1,NoOp(Inbound call for DID {$num} - {$title})\n";
            $conf .= " same => n,Set(CDR(did)={$num})\n";
            $conf .= " same => n,Set(CDR(direction)=inbound)\n";
            if (!empty($d['language'])) {
                $lang = preg_replace('/[^a-zA-Z_]/', '', $d['language']);
                $conf .= " same => n,Set(CHANNEL(language)={$lang})\n";
            }
            // Zorunlu çağrı kaydı. Bu ayar `pbx_dids.record_call` alanında
            // tutuluyordu ama dialplan'a HİÇ yazılmıyordu: panelde işaretli
            // görünüyor, rapora çağrı düşüyor, ama ses dosyası hiç
            // oluşmuyordu (2026-09-01'de DID 13000'de yaşandı).
            //
            // Kayıt, hedefe gitmeden ÖNCE başlatılmalı — Goto sonrasında
            // buraya dönülmez.
            //
            // `b` seçeneği KULLANILMIYOR: o yalnızca çağrı köprülendikten
            // sonra yazmaya başlar, yani IVR anonsu, karşılama ve tuşlama
            // kayda girmez. Gelen rotada kayıt "zorunlu" işaretliyse çağrının
            // tamamı istenir — kayıt ilk andan itibaren başlar.
            if (!empty($d['record_call'])) {
                $rec = "/var/spool/asterisk/monitor/inbound_"
                     . "\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}_to_{$num}.wav";
                $conf .= " same => n,Set(REC_FILE={$rec})\n";
                $conf .= " same => n,MixMonitor(\${REC_FILE})\n";
                $conf .= " same => n,Set(CDR(userfield)=\${REC_FILE})\n";
            }

            $conf .= buildDestinationLines($d['dest_type'], $d['dest_id'], $num) . "\n\n";
        }
    } else {
        $conf .= "; Default Fallback DID\n";
        $conf .= "exten => _X.,1,NoOp(Fallback Inbound Call for DID \${EXTEN})\n";
        $conf .= " same => n,Set(CDR(did)=\${EXTEN})\n";
        $conf .= " same => n,Set(CDR(direction)=inbound)\n";
        // Hiç Gelen Rota tanımlı değilken var olmayabilecek bir context'e (ör. eski
        // sabit "app-timecondition-1") Goto yapmak çağrıyı hata ile düşürürdü.
        $conf .= " same => n,Hangup(1)\n\n";
    }

    // ------------------------------------------------------------------
    // Kapanma tonu algilamasi (in-band disconnect supervision)
    //
    // Bazi hatlarda karsi santral cagrinin kapandigini SINYALLE bildirmez;
    // bunun yerine ses yoluna kadansli mesgul tonu basar. CCIS uzerinden
    // gelen sehir hatti cagrilarinda olculdu (2026-09-15): arayan kapattiktan
    // sonra NEC 110 ms ton / 90 ms sessizlik kadansiyla tonu cagri bitene
    // kadar caliyor, ama tek bir CCIS mesaji gondermiyor. Ton algilanmazsa
    // cagri ayakta kalir, IVR/kuyruk devam eder ve temsilciye BOS CAGRI duser.
    //
    // Bu context'i kullanan trunk'larda ton algilanir algilanmaz cagri
    // kapatilir. Trunk'in "Context" alani buna ayarlanarak devreye alinir;
    // digerleri etkilenmez.
    $conf .= "; --- Kapanma tonu algilayan gelen rota sarmalayicisi ---\n";
    $conf .= "[from-trunk-kapanma-tonu]\n";
    $conf .= "exten => _X.,1,NoOp(Kapanma tonu algilayicisi devrede - DID \${EXTEN})\n";
    // 'r' SART: algilayici varsayilan olarak HER IKI YONU dinler. Onceki
    // surumde verilmemisti ve Asterisk'in arayana GONDERDIGI sesi (IVR
    // anonsu, kuyruk calma tonu) kadansli ton sanip cagriyi kapatiyordu
    // (2026-09-15, iki yanlis pozitif: biri anonsun 7. saniyesinde, biri
    // kuyruk calmaya basladiktan 4 sn sonra). Yalnizca KARSI TARAFTAN
    // GELEN ses denetlenmeli.
    $conf .= " same => n,Set(TONE_DETECT(0,,brg(kapanma-tonu,s,1))=)\n";
    $conf .= " same => n,Goto(from-trunk-inbound,\${EXTEN},1)\n\n";

    $conf .= "[kapanma-tonu]\n";
    $conf .= "exten => s,1,NoOp(Kapanma tonu algilandi - cagri kapatiliyor)\n";
    $conf .= " same => n,Hangup()\n\n";

    return writeConfWithRollback('extensions_inbound.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Gelen Rota senkronizasyonu');
    }, 'Gelen Rota senkronizasyonu');
}
