<?php
/**
 * Single Master File Queue Sync Module (/etc/asterisk/pbx/queues_pbx.conf)
 * Consolidates all active call center queues into a single master configuration file reading from `queues_details` key-value table.
 */

require_once __DIR__ . '/../queue_helper.php';

function syncQueue($queue_id) {
    return syncAllQueues();
}

function syncAllQueues() {
    return withSyncLock('queues', '__syncAllQueuesBody');
}

function __syncAllQueuesBody() {
    $db = getDB();
    $queues = $db->query("SELECT * FROM pbx_queues WHERE is_active = 1 ORDER BY queue_name ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; ==========================================================\n";
    $conf .= "; Master Call Center Queues Configuration (Auto-generated by AI PBX via queues_details DB)\n";
    $conf .= "; ==========================================================\n\n";

    $conf .= "[general]\n";
    $conf .= "persistentmembers = yes\n";
    $conf .= "autofill = yes\n";
    $conf .= "monitor-type = MixMonitor\n";
    $conf .= "queue_log = yes\n\n";

    foreach ($queues as $q) {
        $q_name = $q['queue_name'];
        $title = toCleanAscii($q['title']);
        $musicclass = toCleanAscii(!empty($q['musicclass']) ? $q['musicclass'] : 'default');

        // Fetch details map from `queues_details` table
        $q_map = QueueHelper::getDetailsMap($q_name);
        if (empty($q_map)) {
            QueueHelper::syncQueueToDetails($q);
            $q_map = QueueHelper::getDetailsMap($q_name);
        }

        $conf .= "; Call Center Queue ID {$q['id']}: {$title} ({$q_name})\n";
        $conf .= "[{$q_name}]\n";
        $conf .= "musicclass={$musicclass}\n";

        // Output all key-value directives stored in `queues_details`
        foreach ($q_map as $k => $v) {
            if ($v === '' || $v === null) continue;
            $conf .= toCleanAscii($k) . "=" . toCleanAscii($v) . "\n";
        }
        $conf .= "\n";
    }

    // Delete old individual queue files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/queue_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }

    return writeConfWithRollback("queues_pbx.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadQueue('all')], 'Kuyruk senkronizasyonu');
    }, 'Kuyruk senkronizasyonu');
}

