<?php
/**
 * Sync General Dialplan (/etc/asterisk/pbx/extensions_general.conf)
 */
require_once __DIR__ . '/DialplanBuilders.php';

function syncGeneralDialplan() {
    return withSyncLock('general_dialplan', '__syncGeneralDialplanBody');
}

function __syncGeneralDialplanBody() {
    $db = getDB();
    // Faks kullanıcılarının (extension_type='fax') hiç PJSIP kaydı yok — dahiliden
    // dahiliye çevirme (direct dial) listesine dahil edilmezler.
    $active_exts = $db->query("SELECT extension, full_name FROM sys_users WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip'")->fetchAll();
    $internal_dial_timeout = intval(getSystemSetting('pjsip_internal_dial_timeout', '30'));

    $conf = "; Native General PBX Dialplan Contexts (Auto-generated by AI PBX)\n\n";

    // Dahili arama ve hint'ler ORTAK context'te durur; giden rota kumesi
    // buraya dahil DEGILDIR. Boylece her grup ayni dahili plani paylasip
    // yalnizca kendi giden rotalarini alabiliyor.
    $conf .= "[from-internal-pbx-ortak]\n";
    $conf .= "; Internal Extension-to-Extension Direct Calling\n";

    if (!empty($active_exts)) {
        foreach ($active_exts as $e) {
            $ext = trim($e['extension']);
            $name = toCleanAscii($e['full_name']);
            // Hint olmadan bu extension'ı arayan "Local/{$ext}@from-internal-pbx" kuyruk
            // üyesi cihaz durumu HER ZAMAN "Not in use" (boşta/müsait) görünüyordu — çünkü
            // Local kanalın device state'i, hedeflediği extension'da bir hint tanımı yoksa
            // asla gerçek PJSIP kayıt/çağrı durumunu yansıtmaz. Sonuç: telefonu kapalı/kayıtsız
            // bir dahili, kuyrukta ve süpervizör ekranında sürekli "çevrimiçi" görünüyordu.
            $conf .= "exten => {$ext},hint,PJSIP/{$ext}-sip&PJSIP/{$ext}-webrtc&PJSIP/{$ext}-mob-webrtc\n";
            $conf .= "exten => {$ext},1,NoOp(Direct Call to Extension {$ext} - {$name})\n";
            $conf .= " same => n,Set(CDR(direction)=internal)\n";

            $extDial = buildExtensionDialLines($ext, $db, 'direct');
            $conf .= implode("\n", $extDial['lines']) . "\n";
        }
    } else {
        $conf .= "exten => _3XXX,1,NoOp(Internal Call to PJSIP Extension \${EXTEN})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";
        $conf .= " same => n,Set(C_SIP=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-sip)})\n";
        $conf .= " same => n,Set(C_WEB=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-webrtc)})\n";
        $conf .= " same => n,Set(C_MOB=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-mob-webrtc)})\n";
        $conf .= " same => n,Set(DIAL_CONTACTS=\${C_SIP}\${IF(\$[\"\${C_SIP}\" != \"\" & \"\${C_WEB}\" != \"\"]?&)}\${C_WEB})\n";
        $conf .= " same => n,Set(DIAL_CONTACTS=\${DIAL_CONTACTS}\${IF(\$[\"\${DIAL_CONTACTS}\" != \"\" & \"\${C_MOB}\" != \"\"]?&)}\${C_MOB})\n";
        $conf .= " same => n,GotoIf(\$[\"\${DIAL_CONTACTS}\" = \"\"]?unavail)\n";
        $conf .= " same => n,Dial(\${DIAL_CONTACTS},{$internal_dial_timeout},tT)\n";
        $conf .= " same => n,Hangup()\n";
        $conf .= " same => n(unavail),NoOp(No registered contacts for \${EXTEN})\n";
        $conf .= " same => n,Hangup()\n";
    }

    // Varsayilan context: ortak dahili plan + grup 1 giden rotalari.
    // Mevcut tum uclar ve kuyruklardaki Local/...@from-internal-pbx cagrilari
    // buraya bagli oldugu icin adi ve davranisi degismiyor.
    // Panelden numara verilmis IVR/kuyruk/zaman kosulu/anons/cagri sonlandirma
    // hedefleri. Ayri bir dosyada uretiliyor (SyncInternalNumbers.php) — boylece
    // yeni bir numara eklendiginde bu buyuk dosya yeniden yazilmiyor.
    // include, ortak context'in KENDI extension'larindan sonra aranir:
    // gercek bir dahili numarasi her zaman onceliklidir.
    $conf .= "include => internal-numbers-pbx\n";

    $conf .= "\n; Varsayilan (Grup 1) — dahili + giden rotalar\n";
    $conf .= "[from-internal-pbx]\n";
    $conf .= "include => from-internal-pbx-ortak\n";
    $conf .= "include => from-internal-outbound-1\n";
    $conf .= "include => featurecodes-pbx\n\n";

    // Giden rota gruplari.
    //
    // [from-internal-pbx] grup 1'i kullanir (yukaridaki include). Baska
    // gruplardaki kullanicilar icin ayri birer context uretiliyor: dahili
    // arama ve feature kodlari aynen gecerli, yalnizca giden rota kumesi
    // degisiyor.
    //
    // Boyle kurulmasinin nedeni: grup 1 hic dokunulmadan kaliyor, dolayisiyla
    // grup atanmamis kurulumlarda ve kuyruklardaki
    // Local/...@from-internal-pbx cagrilarinda hicbir sey degismiyor.
    $gruplar = getDB()->query(
        "SELECT DISTINCT route_group FROM pbx_outbound_routes WHERE is_active = 1 AND route_group <> 1 ORDER BY route_group"
    )->fetchAll(PDO::FETCH_COLUMN);

    foreach ($gruplar as $g) {
        $g = intval($g);
        if ($g <= 1) continue;
        $conf .= "; Giden Rota Grubu {$g} kullanicilari\n";
        $conf .= "[from-internal-g{$g}]\n";
        $conf .= "include => from-internal-pbx-ortak\n";
        $conf .= "include => from-internal-outbound-{$g}\n";
        $conf .= "include => featurecodes-pbx\n\n";
    }

    $conf .= "; AMI Originate Context for Web Dialer & Header Softphone\n";
    $conf .= "[cc-internal]\n";
    $conf .= "include => from-internal-pbx\n\n";

    // Native Incoming FAX Context
    $conf .= "; Native Incoming FAX Context\n";
    $conf .= "[from-trunk-fax]\n";
    $conf .= "exten => _X!,1,NoOp(Incoming FAX processing for \${EXTEN} from \${CALLERID(num)})\n";
    // Kanal AÇIKÇA cevaplanmalı ve medya yolunun oturması beklenmeli.
    //
    // Burada Answer() yoktu; ReceiveFAX kanalı kendisi cevaplamaya çalışıyor
    // ve başarısız oluyordu:
    //     WARNING res_fax.c: Channel 'PJSIP/<trunk>-...' failed answer attempt.
    // Sonuç: her gelen faks Status=FAILED, Pages=0 ile düşüyordu (2026-09-01'de
    // 78 çağrının tamamı). Wait(1), cevaplama ile faks tonu dinlemeye
    // başlamak arasında ses yolunun kurulmasına zaman tanır — tonun ilk
    // saniyesi kaçarsa anlaşma hiç başlamıyor.
    $conf .= " same => n,Answer()\n";
    $conf .= " same => n,Wait(1)\n";
    $conf .= " same => n,StopPlaytones()\n";
    $conf .= " same => n,Set(FAXOPT(ecm)=no)\n";
    $conf .= " same => n,Set(FAXOPT(modem)=v29,v27)\n";
    $conf .= " same => n,Set(FAXOPT(maxrate)=9600)\n";
    $conf .= " same => n,Set(FAXOPT(minrate)=2400)\n";
    // UNIQUEID eklenir: aynı saniyede aynı CALLERID'den 2. bir çağrı gelirse
    // (STRFTIME+CALLERID tek başına) FAX_ID çakışıp dosya üzerine yazılabilirdi.
    $conf .= " same => n,Set(FAX_ID=\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${CALLERID(num)}_\${UNIQUEID})\n";
    $conf .= " same => n,Set(FAX_FILE=/var/spool/asterisk/fax/\${FAX_ID}.tif)\n";
    // `df` seçeneği: `d` (faks hata ayıklama günlüğü) + `f` (T.38 destekli kanallarda
    // anlaşma sağlanamazsa ses bandına/G.711'e otomatik geri düşme/fallback izin ver).
    $conf .= " same => n,ReceiveFAX(\${FAX_FILE},df)\n";
    $conf .= " same => n,Hangup()\n\n";
    $conf .= "exten => h,1,NoOp(FAX Receive Completed: Status=\${FAXOPT(status)}, Pages=\${FAXOPT(pages)})\n";
    $conf .= " same => n,Set(FAX_CNUM=\${FILTER(0-9+,\${CALLERID(num)})})\n";
    $conf .= " same => n,Set(FAX_DID=\${FILTER(0-9+,\${IF(\$[\"\${CDR(did)}\" != \"\"]?\${CDR(did)}:\${EXTEN})})})\n";
    $conf .= " same => n,ExecIf(\$[\"\${FAX_FILE}\" != \"\"]?System(/usr/local/bin/process_incoming_fax.sh \"\${FAX_FILE}\" \"\${FAX_DID}\" \"\${FAX_CNUM}\" \"\${FAXOPT(pages)}\" \"\${FAXOPT(status)}\"))\n";

    $fax_header_info = toCleanAscii(getSystemSetting('fax_header_info', 'AI PBX Fax Server'));
    $fax_station_id = toCleanAscii(getSystemSetting('fax_local_station_id', 'FAX37'));

    $conf .= "\n; Native Outgoing FAX Context (SendFAX via Call Files)\n";
    $conf .= "[outbound-fax]\n";
    $conf .= "exten => s,1,NoOp(Sending Outbound FAX to \${FAX_DEST} from \${FAX_SENDER})\n";
    // Gönderen adı çağrı dosyasında SetVar: FAX_SENDER_NAME olarak gelir (fax_send.php);
    // boşsa (ör. eski/elle oluşturulmuş bir .call dosyası) sadece global başlık kullanılır.
    $conf .= " same => n,Set(FAXOPT(headerinfo)={$fax_header_info}\${IF(\$[\"\${FAX_SENDER_NAME}\" != \"\"]?\" - \"\${FAX_SENDER_NAME}:)})\n";
    // TSID = global önek + gönderen faks kullanıcısının dahilisi (FAX_SENDER, .call
    // dosyasında zaten fax_send.php tarafından set ediliyor) — ör. önek 0312555 +
    // dahili 1234 = 03125551234 (2026-08-31, kullanıcı isteği).
    $conf .= " same => n,Set(FAXOPT(localstationid)={$fax_station_id}\${FAX_SENDER})\n";
    $conf .= " same => n,SendFAX(\${FAX_TIF_PATH},d,f)\n";
    $conf .= " same => n,Hangup()\n\n";
    $conf .= "exten => h,1,NoOp(Outbound FAX Completed. Status=\${FAXOPT(status)})\n";
    $conf .= " same => n,System(/usr/local/bin/process_outgoing_fax_result.sh \"\${FAX_ID}\" \"\${FAXOPT(status)}\" \"\${FAXOPT(error)}\" \"\${FAXOPT(pages)}\")\n\n";

    // Enterprise Adaptive Jitter Buffer (AJB) Subroutine for Callee Channels
    $conf .= "; Enterprise Adaptive Jitter Buffer (AJB) Subroutine for Callee Channels\n";
    $conf .= "[sub-callee-jb]\n";
    $conf .= "exten => s,1,NoOp(Applying Adaptive Jitter Buffer to Callee Channel \${CHANNEL})\n";
    $conf .= " same => n,Set(JITTERBUFFER(adaptive)=default)\n";
    $conf .= " same => n,Return()\n\n";

    return writeConfWithRollback('extensions_general.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Genel Ayarlar senkronizasyonu');
    }, 'Genel Ayarlar senkronizasyonu');
}
