<?php
/**
 * Sync Voicemail Mailboxes (/etc/asterisk/pbx/voicemail_pbx.conf)
 */

function syncVoicemail() {
    return withSyncLock('voicemail', '__syncVoicemailBody');
}

function __syncVoicemailBody() {
    $db = getDB();
    $users = $db->query(
        "SELECT extension, full_name, email, voicemail_enabled, voicemail_pin, voicemail_email, voicemail_email_notify, voicemail_attach_audio 
         FROM sys_users 
         WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip'
         ORDER BY extension ASC"
    )->fetchAll(PDO::FETCH_ASSOC);

    // 1. Ensure /etc/asterisk/voicemail.conf includes pbx/voicemail_pbx.conf
    $main_vm_conf = ASTERISK_CONF_DIR . '/voicemail.conf';
    if (is_file($main_vm_conf)) {
        $vm_content = @file_get_contents($main_vm_conf);
        if ($vm_content !== false && strpos($vm_content, 'voicemail_pbx.conf') === false) {
            // Put include right after [default]
            if (preg_match('/^\[default\]/m', $vm_content)) {
                $vm_content = preg_replace('/^\[default\]/m', "[default]\n#include \"pbx/voicemail_pbx.conf\"", $vm_content, 1);
            } else {
                $vm_content .= "\n[default]\n#include \"pbx/voicemail_pbx.conf\"\n";
            }
            @file_put_contents($main_vm_conf, $vm_content);
        }
        // Voicemail e-mails come from the "voicemail" e-mail template
        // (bin/voicemail_mail.php). The include goes right after [general]:
        // Asterisk takes the first value of a key, so ours win over the stock file.
        $vm_content = @file_get_contents($main_vm_conf);
        if ($vm_content !== false && strpos($vm_content, 'voicemail_general.conf') === false && preg_match('/^\[general\][^\n]*$/m', $vm_content)) {
            $vm_content = preg_replace('/^\[general\][^\n]*$/m', "$0\n#include \"pbx/voicemail_general.conf\"", $vm_content, 1);
            @file_put_contents($main_vm_conf, $vm_content);
        }
    }
    require_once dirname(__DIR__) . '/file_helper.php';
    FileHelper::writeFile(ASTERISK_PBX_DIR . '/voicemail_general.conf', voicemailGeneralConf());

    // 2. Generate voicemail_pbx.conf
    $conf = "; Native Voicemail Mailboxes (Auto-generated by AI PBX)\n";
    $conf .= "; mailbox => password,name,email,pager,options\n\n";

    foreach ($users as $u) {
        $ext = preg_replace('/[^0-9]/', '', (string)$u['extension']);
        if ($ext === '') continue;

        $enabled = isset($u['voicemail_enabled']) ? intval($u['voicemail_enabled']) : 1;
        if (!$enabled) continue;

        $pin = !empty($u['voicemail_pin']) ? preg_replace('/[^0-9]/', '', (string)$u['voicemail_pin']) : $ext;
        if ($pin === '') $pin = $ext;

        $name = toCleanAscii($u['full_name']);
        $email = trim($u['voicemail_email'] ?? '') ?: trim($u['email'] ?? '');
        // E-mail notification switched off: no address, Asterisk sends no mail.
        if (isset($u['voicemail_email_notify']) && intval($u['voicemail_email_notify']) === 0) {
            $email = '';
        }
        $attach = (isset($u['voicemail_attach_audio']) && intval($u['voicemail_attach_audio']) === 0) ? 'no' : 'yes';

        $conf .= "{$ext} => {$pin},{$name},{$email},,attach={$attach}|saycid=yes|envelope=yes\n";
    }

    return writeConfWithRollback('voicemail_pbx.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadVoicemail()], t('sync.ctx_voicemail'));
    }, t('sync.ctx_voicemail'));
}

/**
 * [general] settings of voicemail.conf managed by AiPBX (included first).
 * Asterisk pipes each notification to bin/voicemail_mail.php, which sends the
 * "voicemail" e-mail template; emailbody carries the details as key=value
 * lines for it (VoicemailMailParser).
 */
function voicemailGeneralConf(): string
{
    $script = realpath(dirname(__DIR__, 2) . '/bin/voicemail_mail.php') ?: dirname(__DIR__, 2) . '/bin/voicemail_mail.php';
    $body = 'AIPBX-VM\\nmailbox=${VM_MAILBOX}\\nname=${VM_NAME}\\nmsgnum=${VM_MSGNUM}\\nduration=${VM_DUR}'
        . '\\ncidnum=${VM_CIDNUM}\\ncidname=${VM_CIDNAME}\\ncallerid=${VM_CALLERID}\\ndate=${VM_DATE}\\n';
    return "; Managed by AiPBX (SyncVoicemail) - changes are overwritten.\n"
        . "; Voicemail e-mails use the \"voicemail\" template: Admin -> E-Mail -> Templates.\n"
        . "mailcmd=/usr/bin/php {$script}\n"
        . "charset=UTF-8\n"
        . "emaildateformat=%d.%m.%Y %H:%M\n"
        . "emailsubject=Voicemail \${VM_MAILBOX}\n"
        . "emailbody={$body}\n";
}
