<?php
/**
 * Global PJSIP Transport Sync Module (/etc/asterisk/pbx/pjsip_transports.conf)
 * Generates global PJSIP transports (UDP, TCP, TLS, WSS, WS) reading strictly from `pjsipsettings` key-value DB table.
 */

function syncTransports() {
    return withSyncLock('transports', '__syncTransportsBody');
}

function __syncTransportsBody() {
    $db = getDB();

    // Fetch settings map from pjsipsettings DB table
    $stmt = $db->query("SELECT keyword, data FROM pjsipsettings");
    $settings = $stmt ? $stmt->fetchAll(PDO::FETCH_KEY_PAIR) : [];

    $bind_udp = $settings['bindaddr'] ?? '';
    $bind_udp_port = $settings['bindport'] ?? '';

    $tcp_enabled = !empty($settings['tcp_enabled']) && $settings['tcp_enabled'] !== '0' && strtolower($settings['tcp_enabled']) !== 'no';
    $bind_tcp = $settings['tcp_bindaddr'] ?? '';
    $bind_tcp_port = $settings['tcp_bindport'] ?? '';

    $tls_enabled = !empty($settings['tls_enabled']) && $settings['tls_enabled'] !== '0' && strtolower($settings['tls_enabled']) !== 'no';
    $bind_tls = $settings['tls_bindaddr'] ?? '';
    $bind_tls_port = $settings['tls_bindport'] ?? '';
    $tls_cert = $settings['tls_cert_file'] ?? '';
    $tls_priv_key = $settings['tls_priv_key_file'] ?? '';

    $wss_enabled = !isset($settings['wss_enabled']) || ($settings['wss_enabled'] !== '0' && strtolower($settings['wss_enabled']) !== 'no');
    $wss_bind = $settings['wss_bindaddr'] ?? '';
    $wss_port = $settings['wss_bindport'] ?? '';

    $ws_enabled = !empty($settings['ws_enabled']) && $settings['ws_enabled'] !== '0' && strtolower($settings['ws_enabled']) !== 'no';
    $ws_bind = $settings['ws_bindaddr'] ?? '';
    $ws_port = $settings['ws_bindport'] ?? '';

    $extern_ip = $settings['externip_val'] ?? '';

    // Yerel ağlar: DB'deki localnet_* / netmask_* dinamik kayıtlarından okunur
    $local_nets = [];
    for ($i = 0; isset($settings["localnet_{$i}"]); $i++) {
        $net = trim($settings["localnet_{$i}"]);
        if ($net === '') continue;
        $mask = isset($settings["netmask_{$i}"]) && trim($settings["netmask_{$i}"]) !== '' ? trim($settings["netmask_{$i}"]) : '255.255.255.0';
        $local_nets[] = $net . '/' . $mask;
    }

    $local_net_lines = '';
    foreach ($local_nets as $ln) {
        $local_net_lines .= "local_net={$ln}\n";
    }

    $conf = "; ==========================================================\n";
    $conf .= "; Master PJSIP Transports Configuration (Auto-generated by AI PBX via pjsipsettings DB)\n";
    $conf .= "; ==========================================================\n\n";

    // [global] bölümü artık burada üretiliyor (2026-08-31, kullanıcı isteği):
    // user_agent Santral Ayarları'ndan (sys_settings.pjsip_user_agent)
    // yönetilebilsin diye /etc/asterisk/pjsip.conf'taki elle yazılmış [global]
    // buraya taşındı — PJSIP'te aynı bölüm iki dosyada tanımlanırsa çakışır,
    // o yüzden orada BIRAKILMADI (transportların taşınmasıyla aynı gerekçe).
    $user_agent = toCleanAscii(getSystemSetting('pjsip_user_agent', 'Asterisk PBX'));
    if ($user_agent !== '') {
        $conf .= "[global]\n";
        $conf .= "user_agent={$user_agent}\n\n";
    }

    // 1. Standard UDP Transport for Desk Phones & SIP Trunks
    if (!empty($bind_udp) && !empty($bind_udp_port)) {
        $conf .= "[transport-udp]\n";
        $conf .= "type=transport\n";
        $conf .= "protocol=udp\n";
        $conf .= "bind={$bind_udp}:{$bind_udp_port}\n";
        $conf .= $local_net_lines;
        if (!empty($extern_ip)) {
            $conf .= "external_media_address={$extern_ip}\n";
            $conf .= "external_signaling_address={$extern_ip}\n";
        }
        $conf .= "\n";
    }

    // 2. TCP Transport
    if ($tcp_enabled && !empty($bind_tcp) && !empty($bind_tcp_port)) {
        $conf .= "[transport-tcp]\n";
        $conf .= "type=transport\n";
        $conf .= "protocol=tcp\n";
        $conf .= "bind={$bind_tcp}:{$bind_tcp_port}\n";
        $conf .= $local_net_lines;
        if (!empty($extern_ip)) {
            $conf .= "external_media_address={$extern_ip}\n";
            $conf .= "external_signaling_address={$extern_ip}\n";
        }
        $conf .= "\n";
    }

    // 3. TLS Transport (Encrypted SIP)
    if ($tls_enabled && !empty($bind_tls) && !empty($bind_tls_port)) {
        $conf .= "[transport-tls]\n";
        $conf .= "type=transport\n";
        $conf .= "protocol=tls\n";
        $conf .= "bind={$bind_tls}:{$bind_tls_port}\n";
        if (!empty($tls_cert)) {
            $conf .= "cert_file={$tls_cert}\n";
        }
        if (!empty($tls_priv_key)) {
            $conf .= "priv_key_file={$tls_priv_key}\n";
        }
        $conf .= "method=tlsv1_2\n";
        $conf .= $local_net_lines;
        if (!empty($extern_ip)) {
            $conf .= "external_media_address={$extern_ip}\n";
            $conf .= "external_signaling_address={$extern_ip}\n";
        }
        $conf .= "\n";
    }

    // 4. WSS Transport for Secure WebRTC Browser Clients
    if ($wss_enabled && !empty($wss_bind) && !empty($wss_port)) {
        $conf .= "[transport-wss]\n";
        $conf .= "type=transport\n";
        $conf .= "protocol=wss\n";
        $conf .= "bind={$wss_bind}:{$wss_port}\n";
        if (!empty($tls_cert)) {
            $conf .= "cert_file={$tls_cert}\n";
        }
        if (!empty($tls_priv_key)) {
            $conf .= "priv_key_file={$tls_priv_key}\n";
        }
        $conf .= $local_net_lines;
        if (!empty($extern_ip)) {
            $conf .= "external_media_address={$extern_ip}\n";
            $conf .= "external_signaling_address={$extern_ip}\n";
        }
        $conf .= "\n";
    }

    // 5. WS Transport for Unencrypted WebRTC Clients
    if ($ws_enabled && !empty($ws_bind) && !empty($ws_port)) {
        $conf .= "[transport-ws]\n";
        $conf .= "type=transport\n";
        $conf .= "protocol=ws\n";
        $conf .= "bind={$ws_bind}:{$ws_port}\n";
        $conf .= $local_net_lines;
        if (!empty($extern_ip)) {
            $conf .= "external_media_address={$extern_ip}\n";
            $conf .= "external_signaling_address={$extern_ip}\n";
        }
        $conf .= "\n";
    }

    return writeConfWithRollback("pjsip_transports.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadPJSIP()], 'Transport senkronizasyonu');
    }, 'Transport senkronizasyonu');
}


