<?php
/**
 * Sync Conference Rooms Dialplan (/etc/asterisk/pbx/extensions_conferences.conf)
 */

function syncConferences() {
    return withSyncLock('conferences', '__syncConferencesBody');
}

function __syncConferencesBody() {
    $db = getDB();
    $conferences = $db->query("SELECT * FROM pbx_conferences WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Native Conference Rooms Dialplan Context (Auto-generated by AI PBX)\n\n";

    foreach ($conferences as $cf) {
        $id = intval($cf['id']);
        $num = preg_replace('/[^0-9]/', '', (string)$cf['room_number']);
        $title = toCleanAscii($cf['title']);
        $user_pin = preg_replace('/[^0-9]/', '', (string)($cf['user_pin'] ?? ''));
        $admin_pin = preg_replace('/[^0-9]/', '', (string)($cf['admin_pin'] ?? ''));
        $wait_marked = !empty($cf['wait_marked']) ? 'yes' : 'no';
        $end_marked = !empty($cf['end_marked']) ? 'yes' : 'no';
        $announce_join_leave = !empty($cf['announce_join_leave']) ? 'yes' : 'no';
        $announce_user_count = !empty($cf['announce_user_count']) ? 'yes' : 'no';
        $record = !empty($cf['record_conference']) ? 'yes' : 'no';
        $mute = !empty($cf['mute_on_join']) ? 'yes' : 'no';
        $moh = preg_replace('/[^a-zA-Z0-9_-]/', '', $cf['music_on_hold'] ?? 'default') ?: 'default';

        $conf .= "; ---- Conference #{$id}: {$title} ({$num}) ----\n";
        $conf .= "[app-confbridge-{$id}]\n";
        $conf .= "exten => s,1,NoOp(Conference Room {$id}: {$title} - Room Number: {$num})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";
        $conf .= " same => n,Answer()\n";

        // ConfBridge dynamic settings
        $conf .= " same => n,Set(CONFBRIDGE(bridge,record_conference)={$record})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,music_on_hold_class)={$moh})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,wait_marked)={$wait_marked})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,end_marked)={$end_marked})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,announce_join_leave)={$announce_join_leave})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,announce_user_count)={$announce_user_count})\n";
        $conf .= " same => n,Set(CONFBRIDGE(user,startmuted)={$mute})\n";

        if ($admin_pin !== '' || $user_pin !== '') {
            $conf .= " same => n,Read(CONF_PIN,conf-getpin,10,,3,10)\n";
            if ($admin_pin !== '') {
                $conf .= " same => n,GotoIf(\$[\"\${CONF_PIN}\" = \"{$admin_pin}\"]?cf_admin_{$id})\n";
            }
            if ($user_pin !== '') {
                $conf .= " same => n,GotoIf(\$[\"\${CONF_PIN}\" = \"{$user_pin}\"]?cf_user_{$id})\n";
            }
            $conf .= " same => n,Playback(conf-invalidpin)\n";
            $conf .= " same => n,Hangup()\n";

            if ($admin_pin !== '') {
                $conf .= " same => n(cf_admin_{$id}),Set(CONFBRIDGE(user,admin)=yes)\n";
                $conf .= " same => n,Set(CONFBRIDGE(user,marked)=yes)\n";
                $conf .= " same => n,Goto(cf_enter_{$id})\n";
            }
            if ($user_pin !== '') {
                $conf .= " same => n(cf_user_{$id}),Set(CONFBRIDGE(user,admin)=no)\n";
                $conf .= " same => n,Goto(cf_enter_{$id})\n";
            }
        }

        $conf .= " same => n(cf_enter_{$id}),ConfBridge({$num})\n";
        $conf .= " same => n,Hangup()\n\n";
    }

    return writeConfWithRollback('extensions_conferences.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Konferans Odaları senkronizasyonu');
    }, 'Konferans Odaları senkronizasyonu');
}
