<?php
/**
 * Single Master File Trunk Sync Module (/etc/asterisk/pbx/pjsip_trunks.conf)
 * Consolidates all active SIP trunks into a single master configuration file reading from `sip` key-value table.
 */

require_once __DIR__ . '/../sip_helper.php';

function syncTrunk($trunk_id) {
    return syncAllTrunks();
}

function syncAllTrunks() {
    return withSyncLock('trunks', '__syncAllTrunksBody');
}

function __syncAllTrunksBody() {
    $db = getDB();
    $trunks = $db->query("SELECT * FROM pbx_trunks WHERE is_active = 1 ORDER BY trunk_name ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; ==========================================================\n";
    $conf .= "; Master PJSIP Trunks Configuration (Auto-generated by AI PBX via sip Key-Value DB)\n";
    $conf .= "; ==========================================================\n\n";

    foreach ($trunks as $t) {
        $t_name = $t['trunk_name'];
        $title = toCleanAscii($t['title']);

        // Fetch settings from `sip` table (or fallback to sync)
        $sip_map = SIPHelper::getSettingsMap($t_name);
        if (empty($sip_map)) {
            SIPHelper::syncTrunkToSIP($t);
            $sip_map = SIPHelper::getSettingsMap($t_name);
        }

        $ip = toCleanAscii(!empty($sip_map['ip_address']) ? trim($sip_map['ip_address']) : trim($t['ip_address']));
        $port = !empty($sip_map['port']) ? intval($sip_map['port']) : intval($t['port'] ?: 5060);
        $transport = normalizeSipTransport(!empty($sip_map['transport']) ? $sip_map['transport'] : ($t['transport'] ?? 'udp'));
        $codecs = toCleanAscii(!empty($sip_map['allow']) ? $sip_map['allow'] : (!empty($t['codecs']) ? $t['codecs'] : 'alaw,ulaw'));
        $raw_context = toCleanAscii(!empty($sip_map['context']) ? $sip_map['context'] : (!empty($t['context']) ? $t['context'] : 'from-trunk-inbound'));
        $context = ($raw_context === '' || $raw_context === 'from-trunk-inbound' || $raw_context === 'from-trunk-kapanma-tonu')
            ? "from-trunk-{$t_name}"
            : $raw_context;
        $qualify = !empty($sip_map['qualify_frequency']) ? intval($sip_map['qualify_frequency']) : intval($t['qualify_frequency'] ?: 60);
        $t38 = (!empty($sip_map['t38_udptl']) && $sip_map['t38_udptl'] === 'yes') || !empty($t['t38_support']);
        $dtmf_mode = toCleanAscii(!empty($sip_map['dtmf_mode']) ? $sip_map['dtmf_mode'] : (!empty($t['dtmf_mode']) ? $t['dtmf_mode'] : 'rfc4733'));
        $direct_media = toCleanAscii(!empty($sip_map['direct_media']) ? $sip_map['direct_media'] : (!empty($t['direct_media']) ? $t['direct_media'] : 'no'));
        $timers = toCleanAscii(!empty($sip_map['timers']) ? $sip_map['timers'] : (!empty($t['timers']) ? $t['timers'] : 'yes'));

        $rtp_symmetric = toCleanAscii(!empty($sip_map['rtp_symmetric']) ? $sip_map['rtp_symmetric'] : (!empty($t['rtp_symmetric']) ? $t['rtp_symmetric'] : 'yes'));
        $force_rport = toCleanAscii(!empty($sip_map['force_rport']) ? $sip_map['force_rport'] : (!empty($t['force_rport']) ? $t['force_rport'] : 'yes'));
        $rewrite_contact = toCleanAscii(!empty($sip_map['rewrite_contact']) ? $sip_map['rewrite_contact'] : (!empty($t['rewrite_contact']) ? $t['rewrite_contact'] : 'yes'));
        $outbound_proxy = toCleanAscii(!empty($sip_map['outbound_proxy']) ? $sip_map['outbound_proxy'] : (!empty($t['outbound_proxy']) ? $t['outbound_proxy'] : ''));
        $match_hosts = toCleanAscii(!empty($sip_map['match_hosts']) ? $sip_map['match_hosts'] : (!empty($t['match_hosts']) ? $t['match_hosts'] : $ip));
        $max_contacts = !empty($sip_map['max_contacts']) ? intval($sip_map['max_contacts']) : intval($t['max_contacts'] ?? 1 ?: 1);

        $t38_ec = toCleanAscii(!empty($sip_map['t38_udptl_ec']) ? $sip_map['t38_udptl_ec'] : (!empty($t['t38_udptl_ec']) ? $t['t38_udptl_ec'] : 'redundancy'));
        $t38_nat = toCleanAscii(!empty($sip_map['t38_udptl_nat']) ? $sip_map['t38_udptl_nat'] : (!empty($t['t38_udptl_nat']) ? $t['t38_udptl_nat'] : 'yes'));
        $t38_maxdatagram = !empty($sip_map['t38_udptl_maxdatagram']) ? intval($sip_map['t38_udptl_maxdatagram']) : intval($t['t38_udptl_maxdatagram'] ?? 400 ?: 400);

        $fax_detect = (!empty($sip_map['fax_detect']) && $sip_map['fax_detect'] === 'yes') || (!empty($t['fax_detect']) && (int)$t['fax_detect'] === 1);
        $fax_detect_timeout = !empty($sip_map['fax_detect_timeout']) ? intval($sip_map['fax_detect_timeout']) : intval($t['fax_detect_timeout'] ?? 30 ?: 30);

        $auth_user = toCleanAscii(!empty($sip_map['auth_username']) ? $sip_map['auth_username'] : (!empty($t['auth_username']) ? $t['auth_username'] : ''));
        $auth_pass = toCleanAscii(!empty($sip_map['auth_password']) ? $sip_map['auth_password'] : (!empty($t['auth_password']) ? $t['auth_password'] : ''));
        $has_auth = ($auth_user !== '' && $auth_pass !== '');

        $from_user = toCleanAscii(!empty($sip_map['from_user']) ? $sip_map['from_user'] : (!empty($t['from_user']) ? $t['from_user'] : ''));
        $from_domain = toCleanAscii(!empty($sip_map['from_domain']) ? $sip_map['from_domain'] : (!empty($t['from_domain']) ? $t['from_domain'] : ''));
        $send_pai = (!empty($sip_map['send_pai']) && $sip_map['send_pai'] === 'yes') || !empty($t['send_pai']);
        $send_rpid = (!empty($sip_map['send_rpid']) && $sip_map['send_rpid'] === 'yes') || !empty($t['send_rpid']);

        // Connection mode (2026-09-01):
        //   'ip'       → the far PBX has a fixed IP; a STATIC contact is kept on the AOR
        //   'register' → the far PBX registers TO US; the static contact is REMOVED
        //                (the address is learned from the registration) and INBOUND
        //                authentication (auth=) is added to the endpoint.
        // CAUTION: in 'register' mode the AOR has no contact until the far end
        // registers — so we CANNOT CALL that trunk. Switch over together with the
        // registration setting on the far end.
        $conn_mode = (($t['connection_mode'] ?? 'ip') === 'register') ? 'register' : 'ip';
        // Do NOT APPLY register mode without credentials: no auth= line could be
        // generated, so the registration would be accepted WITHOUT A PASSWORD
        // (anyone from the same IP could register). The service layer blocks it
        // too; this is the last line of defence.
        if ($conn_mode === 'register' && !$has_auth) {
            $conn_mode = 'ip';
        }

        // The AOR NAME MUST be exactly the USERNAME the far end REGISTERS with.
        // Asterisk's registrar compares the names in the endpoint's aors= list
        // with the registering name; without a match REGISTER gets 404 Not Found
        // and the log says "AOR '' not found for endpoint 'x'".
        // Exactly this happened live on 2026-09-01: with aors=<trunk name> the NEC
        // registered as 'nec2'. (The same trap showed up earlier with the
        // internal SIP accounts — there too the endpoint SECTION name is looked
        // up, not the number.) IP mode has no such constraint; the AOR name stays
        // the trunk name.
        $aor_name = $t_name;
        if ($conn_mode === 'register') {
            $kayit_adi = preg_replace('/[^a-zA-Z0-9_-]/', '', $auth_user);
            if ($kayit_adi !== '') {
                $aor_name = $kayit_adi;
            }
        }

        $reg_enabled = (!empty($sip_map['registration_enabled']) && $sip_map['registration_enabled'] == '1') || !empty($t['registration_enabled']);
        $reg_expire = !empty($sip_map['registration_expiration']) ? intval($sip_map['registration_expiration']) : intval($t['registration_expiration'] ?: 3600);
        $reg_retry = !empty($sip_map['registration_retry_interval']) ? intval($sip_map['registration_retry_interval']) : intval($t['registration_retry_interval'] ?: 60);

        // 1. Endpoint Section
        $conf .= "; SIP Trunk ID {$t['id']}: {$title} ({$t_name})\n";
        $conf .= "[{$t_name}]\n";
        $conf .= "type=endpoint\n";
        $conf .= "context={$context}\n";
        $conf .= "disallow=all\n";
        $conf .= "allow={$codecs}\n";
        $conf .= "transport={$transport}\n";
        $conf .= "aors={$aor_name}\n";
        $conf .= "direct_media={$direct_media}\n";
        $conf .= "rtp_symmetric={$rtp_symmetric}\n";
        $conf .= "force_rport={$force_rport}\n";
        $conf .= "rewrite_contact={$rewrite_contact}\n";
        $conf .= "dtmf_mode={$dtmf_mode}\n";
        $conf .= "timers={$timers}\n";

        if ($outbound_proxy !== '') {
            $conf .= "outbound_proxy={$outbound_proxy}\n";
        }
        if ($conn_mode === 'register') {
            // INBOUND authentication: the far end's REGISTER (and INVITEs) are
            // authenticated with these details. The OPPOSITE direction of outbound_auth.
            $conf .= "auth={$t_name}-auth\n";
        }
        if ($has_auth) {
            $conf .= "outbound_auth={$t_name}-auth\n";
        }
        $trunk_cid = toCleanAscii(!empty($sip_map['outbound_caller_id']) ? $sip_map['outbound_caller_id'] : (!empty($t['outbound_caller_id']) ? $t['outbound_caller_id'] : ''));
        if ($from_user !== '' && $from_user !== $trunk_cid) {
            $conf .= "from_user={$from_user}\n";
            $conf .= "contact_user={$from_user}\n";
        }
        if ($from_domain !== '') {
            $conf .= "from_domain={$from_domain}\n";
        }
        if ($send_pai) {
            $conf .= "send_pai=yes\n";
        }
        if ($send_rpid) {
            $conf .= "send_rpid=yes\n";
        }
        $conf .= "trust_id_outbound=yes\n";

        if ($t38) {
            $conf .= "t38_udptl=yes\n";
            $conf .= "t38_udptl_ec={$t38_ec}\n";
            $conf .= "t38_udptl_maxdatagram={$t38_maxdatagram}\n";
            $conf .= "t38_udptl_nat={$t38_nat}\n";
        } else {
            $conf .= "t38_udptl=no\n";
        }

        if ($fax_detect) {
            $conf .= "fax_detect=yes\n";
            $conf .= "fax_detect_timeout={$fax_detect_timeout}\n";
        } else {
            $conf .= "fax_detect=no\n";
        }

        // Custom parameters from pbx_trunks.custom_pjsip_params
        if (!empty($t['custom_pjsip_params'])) {
            $custom_lines = explode("\n", str_replace("\r", "", $t['custom_pjsip_params']));
            foreach ($custom_lines as $cline) {
                $cline = trim($cline);
                if ($cline === '' || $cline[0] === ';' || $cline[0] === '#') continue;
                if (strpos($cline, '=') !== false) {
                    $conf .= toCleanAscii($cline) . "\n";
                }
            }
        }

        // Pass-through any custom extra parameters stored in `sip` table
        $ignore_keys = [
            'id', 'trunk_name', 'title', 'ip_address', 'port', 'context', 'transport', 'disallow', 'allow',
            'direct_media', 'rtp_symmetric', 'force_rport', 'rewrite_contact', 'qualify_frequency',
            'max_contacts', 't38_udptl', 't38_udptl_ec', 't38_udptl_nat', 't38_udptl_maxdatagram',
            'fax_detect', 'fax_detect_timeout', 'dtmf_mode', 'timers',
            'from_user', 'from_domain', 'send_pai', 'send_rpid', 'auth_username', 'auth_password',
            'registration_enabled', 'registration_expiration', 'registration_retry_interval',
            'outbound_auth', 'outbound_proxy', 'match_hosts',
            'outbound_caller_id', 'callerid', 'did_trim_digits', 'allow_outbound_routing', 'outbound_route_group',
            'connection_mode', 'is_active', 'created_at', 'custom_pjsip_params'
        ];
        foreach ($sip_map as $k => $v) {
            if (in_array($k, $ignore_keys) || $v === '') continue;
            $conf .= toCleanAscii($k) . "=" . toCleanAscii($v) . "\n";
        }
        $conf .= "\n";

        // 2. Auth Section (if credentials provided)
        if ($has_auth) {
            $conf .= "[{$t_name}-auth]\n";
            $conf .= "type=auth\n";
            $conf .= "auth_type=userpass\n";
            $conf .= "username={$auth_user}\n";
            $conf .= "password={$auth_pass}\n\n";
        }

        // 3. AOR Section
        $conf .= "[{$aor_name}]\n";
        $conf .= "type=aor\n";
        if ($conn_mode === 'register') {
            // NO static contact: the address is learned from the far end's
            // registration. remove_existing is required — when the far PBX
            // restarts and registers with a new contact, the OLD, unexpired
            // registration would fill the max_contacts limit and get the new one
            // rejected (the trunk dies silently).
            $conf .= "remove_existing=yes\n";
        } else {
            $conf .= "contact=sip:{$ip}:{$port}\n";
        }
        $conf .= "max_contacts={$max_contacts}\n";
        $conf .= "qualify_frequency={$qualify}\n";
        if ($outbound_proxy !== '') {
            $conf .= "outbound_proxy={$outbound_proxy}\n";
        }
        $conf .= "\n";

        // 4. Outbound Registration Section (if enabled and auth credentials present)
        if ($reg_enabled && $has_auth) {
            $server_host = ($from_domain !== '') ? $from_domain : ($ip . ':' . $port);
            $client_user = ($from_user !== '') ? $from_user : $auth_user;
            $conf .= "[{$t_name}-reg]\n";
            $conf .= "type=registration\n";
            $conf .= "transport={$transport}\n";
            $conf .= "outbound_auth={$t_name}-auth\n";
            $conf .= "server_uri=sip:{$server_host}\n";
            $conf .= "client_uri=sip:{$client_user}@{$server_host}\n";
            $conf .= "expiration={$reg_expire}\n";
            $conf .= "retry_interval={$reg_retry}\n";
            if ($outbound_proxy !== '') {
                $conf .= "outbound_proxy={$outbound_proxy}\n";
            }
            $conf .= "\n";
        }

        // 5. Identify Section
        $conf .= "[{$t_name}]\n";
        $conf .= "type=identify\n";
        $conf .= "endpoint={$t_name}\n";
        $conf .= "match={$match_hosts}\n\n";
    }

    // Delete old individual trunk files if any exist
    $old_files = glob(ASTERISK_PBX_DIR . '/pjsip_trunk_*.conf');
    if (is_array($old_files)) {
        foreach ($old_files as $f) {
            FileHelper::deleteFile($f);
        }
    }

    return writeConfWithRollback("pjsip_trunks.conf", $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadPJSIP()], 'Trunk senkronizasyonu');
    }, 'Trunk senkronizasyonu');
}

