<?php
/**
 * Sync Voicemail Mailboxes (/etc/asterisk/pbx/voicemail_pbx.conf)
 */

function syncVoicemail() {
    return withSyncLock('voicemail', '__syncVoicemailBody');
}

function __syncVoicemailBody() {
    $db = getDB();
    $users = $db->query(
        "SELECT extension, full_name, email, voicemail_enabled, voicemail_pin, voicemail_email, voicemail_attach_audio 
         FROM sys_users 
         WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip'
         ORDER BY extension ASC"
    )->fetchAll(PDO::FETCH_ASSOC);

    // 1. Ensure /etc/asterisk/voicemail.conf includes pbx/voicemail_pbx.conf
    $main_vm_conf = '/etc/asterisk/voicemail.conf';
    if (is_file($main_vm_conf)) {
        $vm_content = @file_get_contents($main_vm_conf);
        if ($vm_content !== false && strpos($vm_content, 'voicemail_pbx.conf') === false) {
            // Put include right after [default]
            if (preg_match('/^\[default\]/m', $vm_content)) {
                $vm_content = preg_replace('/^\[default\]/m', "[default]\n#include \"pbx/voicemail_pbx.conf\"", $vm_content, 1);
            } else {
                $vm_content .= "\n[default]\n#include \"pbx/voicemail_pbx.conf\"\n";
            }
            @file_put_contents($main_vm_conf, $vm_content);
        }
    }

    // 2. Generate voicemail_pbx.conf
    $conf = "; Native Voicemail Mailboxes (Auto-generated by AI PBX)\n";
    $conf .= "; mailbox => password,name,email,pager,options\n\n";

    foreach ($users as $u) {
        $ext = preg_replace('/[^0-9]/', '', (string)$u['extension']);
        if ($ext === '') continue;

        $enabled = isset($u['voicemail_enabled']) ? intval($u['voicemail_enabled']) : 1;
        if (!$enabled) continue;

        $pin = !empty($u['voicemail_pin']) ? preg_replace('/[^0-9]/', '', (string)$u['voicemail_pin']) : $ext;
        if ($pin === '') $pin = $ext;

        $name = toCleanAscii($u['full_name']);
        $email = trim($u['voicemail_email'] ?? '') ?: trim($u['email'] ?? '');
        $attach = (isset($u['voicemail_attach_audio']) && intval($u['voicemail_attach_audio']) === 0) ? 'no' : 'yes';

        $conf .= "{$ext} => {$pin},{$name},{$email},,attach={$attach}|saycid=yes|envelope=yes\n";
    }

    return writeConfWithRollback('voicemail_pbx.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadVoicemail()], 'Sesli Posta senkronizasyonu');
    }, 'Sesli Posta senkronizasyonu');
}
