<?php
/**
 * Feature Code (Star Code) Dialplan Sync Module (/etc/asterisk/pbx/extensions_featurecodes.conf)
 *
 * Kodlar `pbx_feature_codes` tablosundan okunur (admin panelden düzenlenebilir).
 * DND/Çağrı Yönlendirme durumu astdb yerine doğrudan sys_users'ta tutulur;
 * bu yüzden telefon üzerinden kod tuşlandığında dialplan sadece bir arka plan
 * betiğini tetikler (feature_code_action.php), o da DB'yi günceller ve
 * syncEverything() ile dialplan'ı yeniden üretip reload eder — sistemin
 * genelindeki "DB -> config üret -> reload" deseniyle birebir aynı.
 */

function syncFeatureCodes() {
    return withSyncLock('featurecodes', '__syncFeatureCodesBody');
}

function __syncFeatureCodesBody() {
    $db = getDB();
    $codes = $db->query("SELECT * FROM pbx_feature_codes WHERE is_active = 1 ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

    $conf = "; Feature Code (Star Code) Dialplan (Auto-generated by AI PBX)\n\n";
    $conf .= "[featurecodes-pbx]\n\n";

    foreach ($codes as $c) {
        $code = preg_replace('/[^0-9A-Za-z_.*#\[\]-]/', '', trim($c['code']));
        $key = preg_replace('/[^a-zA-Z0-9_]/', '', (string)$c['feature_key']);
        if ($code === '' || $key === '') continue;

        $conf .= "; " . toCleanAscii($c['title']) . " ({$key})\n";
        $conf .= "exten => {$code},1,NoOp(Feature Code {$key} by \${CALLERID(num)})\n";

        $allowed = trim($c['allowed_roles'] ?? '');
        $gated = $allowed !== '';
        if ($gated) {
            $roles = array_filter(array_map(function ($r) { return preg_replace('/[^a-zA-Z0-9_]/', '', trim($r)); }, explode(',', $allowed)));
            $conds = array_map(function ($r) { return "\"\${USER_ROLE}\" = \"{$r}\""; }, $roles);
            $conf .= " same => n,GotoIf(\$[" . implode(' | ', $conds) . "]?allowed_{$key})\n";
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Playback(beep)\n";
            $conf .= " same => n,Hangup()\n";
            $conf .= " same => n(allowed_{$key}),NoOp(Yetki dogrulandi: \${USER_ROLE})\n";
        }

        switch ($key) {
            case 'dnd_toggle':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php dnd_toggle \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_set':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(CFTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${CFTARGET}\" = \"\"]?cfset_empty)\n";
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_set \${CALLERID(num)} \${CFTARGET} &)\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(cfset_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'cf_cancel':
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_cancel \${CALLERID(num)} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_group':
                $conf .= " same => n,Pickup()\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'pickup_directed':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(PICKTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${PICKTARGET}\" = \"\"]?pickdir_empty)\n";
                $conf .= " same => n,PickupChan(PJSIP/\${PICKTARGET}-sip&PJSIP/\${PICKTARGET}-webrtc&PJSIP/\${PICKTARGET}-mob-webrtc)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(pickdir_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'queue_login':
            case 'queue_logout':
                // Kod bir desen ("_*81." gibi) — baştaki '_' ve sondaki joker karakter(ler)
                // ("." veya "X") atılınca kalan sabit önek uzunluğu, tuşlanan geri kalan
                // basamakların (${EXTEN:N}) kuyruk ID'si (pbx_queues.id) olarak alınacağı yeri belirler.
                $prefix_len = strlen(rtrim(ltrim($code, '_'), '.X'));
                $action = ($key === 'queue_login') ? 'queue_login' : 'queue_logout';
                $conf .= " same => n,Set(QID=\${EXTEN:{$prefix_len}})\n";
                $conf .= " same => n,GotoIf(\$[\"\${QID}\" = \"\"]?{$key}_empty)\n";
                $conf .= " same => n,System(/usr/local/bin/feature_code_action.php {$action} \${CALLERID(num)} \${QID} &)\n";
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n({$key}_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            case 'spy':
                $conf .= " same => n,Answer()\n";
                $conf .= " same => n,Read(SPYTARGET,,10,,3,10)\n";
                $conf .= " same => n,GotoIf(\$[\"\${SPYTARGET}\" = \"\"]?spy_empty)\n";
                $conf .= " same => n,ChanSpy(PJSIP/\${SPYTARGET},b)\n";
                $conf .= " same => n,Hangup()\n";
                $conf .= " same => n(spy_empty),Playback(beep)\n";
                $conf .= " same => n,Hangup()\n";
                break;

            default:
                // Bilinmeyen/gelecekteki feature_key: güvenli varsayılan (sadece kapat)
                $conf .= " same => n,Hangup()\n";
                break;
        }
        $conf .= "\n";
    }

    return writeConfWithRollback('extensions_featurecodes.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], 'Özellik Kodu senkronizasyonu');
    }, 'Özellik Kodu senkronizasyonu');
}
