<?php
/**
 * UDPTL (T.38 Faks Medya Portları & FEC) Senkronizasyonu (/etc/asterisk/udptl.conf)
 */

const UDPTL_CONF_PATH = '/etc/asterisk/udptl.conf';

function syncUdptlSettings()
{
    return withSyncLock('udptl', '__syncUdptlSettingsBody');
}

function __syncUdptlSettingsBody()
{
    $start       = (int) getSystemSetting('udptl_start', '4100');
    $end         = (int) getSystemSetting('udptl_end', '4999');
    $checksums   = getSystemSetting('udptl_checksums', 'yes') === 'no' ? 'no' : 'yes';
    $fec_entries = max(0, min(9, (int) getSystemSetting('udptl_fec_entries', '3')));
    $fec_span    = max(0, min(9, (int) getSystemSetting('udptl_fec_span', '3')));

    if ($start < 1024 || $start > 65535 || $end < 1024 || $end > 65535 || $end <= $start) {
        $start = 4100;
        $end   = 4999;
    }

    $conf  = "; UDPTL Configuration (Auto-generated by AI PBX)\n";
    $conf .= "; Bu dosya panelden üretilir — elle yapılan değişiklikler bir sonraki\n";
    $conf .= "; 'Uygula' işleminde KAYBOLUR. Santral Ayarları > UDPTL bölümünü kullanın.\n";
    $conf .= "\n[general]\n";
    $conf .= "udptlstart={$start}\n";
    $conf .= "udptlend={$end}\n";
    $conf .= "udptlchecksums={$checksums}\n";
    $conf .= "udptlfecentries={$fec_entries}\n";
    $conf .= "udptlfecspan={$fec_span}\n";

    $onceki = is_readable(UDPTL_CONF_PATH) ? file_get_contents(UDPTL_CONF_PATH) : null;

    if (!FileHelper::writeFile(UDPTL_CONF_PATH, $conf, 'asterisk', 'asterisk', 0644)) {
        throw new \Exception('udptl.conf yazılamadı (izin/sahiplik?)');
    }

    try {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadUDPTL()], 'UDPTL ayarları');
    } catch (\Exception $e) {
        if ($onceki !== null && FileHelper::writeFile(UDPTL_CONF_PATH, $onceki, 'asterisk', 'asterisk', 0644)) {
            AsteriskHelper::reloadUDPTL();
            throw new \Exception('UDPTL ayarları uygulanamadı, ÖNCEKİ HÂLE OTOMATİK GERİ ALINDI: ' . $e->getMessage());
        }
        throw new \Exception('UDPTL ayarları uygulanamadı ve GERİ ALINAMADI, ELLE MÜDAHALE GEREKİYOR: ' . $e->getMessage());
    }

    return true;
}
