<?php
/**
 * RTP settings sync (/etc/asterisk/rtp.conf)
 *
 * It differs from the other generators in TWO ways:
 *
 * 1) The target file is NOT in the `pbx/` subdirectory but directly under
 *    /etc/asterisk. So writePBXConf()/writeConfWithRollback() cannot be used
 *    (they write to ASTERISK_PBX_DIR); the rollback logic is built by hand here.
 *
 * 2) WE generate the whole file. It used to be managed by hand; since it
 *    moved to the portal, manual edits are lost on the next Apply — the
 *    warning at the top of the file says so.
 *
 * NOTE: reload activates `strictrtp`, but a port RANGE change needs a full
 * Asterisk restart (see AsteriskHelper::reloadRTP).
 */

define('RTP_CONF_PATH', ASTERISK_CONF_DIR . '/rtp.conf');

function syncRtpSettings()
{
    return withSyncLock('rtp', '__syncRtpSettingsBody');
}

/**
 * Generates the rtp.conf content — a pure function: does NOT write to disk,
 * does NOT reload. RTP_CONF_PATH is a constant pointing at the live
 * /etc/asterisk/rtp.conf, so __syncRtpSettingsBody() cannot be called from a
 * unit test; the generation logic was split out here so it can be tested
 * (same pattern: buildInternalNumbersConf, buildIVRDialplanBlock).
 */
function buildRtpConf(): string
{
    $start  = (int) getSystemSetting('rtp_start', '10000');
    $end    = (int) getSystemSetting('rtp_end', '12999');
    $strict = getSystemSetting('rtp_strict', 'yes') === 'no' ? 'no' : 'yes';

    // The service layer already validates; this is the last line of defence —
    // if a broken value reached the DB some other way, Asterisk's RTP could
    // stop working completely.
    if ($start < 1024 || $start > 65535 || $end < 1024 || $end > 65535 || $end <= $start) {
        $start = 10000;
        $end   = 12999;
    }

    $extern_ip = trim(getSystemSetting('pjsip_external_ip', ''));
    if ($extern_ip === '') {
        $db = getDB();
        $stmt = $db->query("SELECT data FROM pjsipsettings WHERE keyword = 'externip_val' LIMIT 1");
        $extern_ip = trim((string)($stmt ? $stmt->fetchColumn() : ''));
    }
    if ($extern_ip === '') {
        $extern_ip = portalEnv('EXTERNAL_IP', '');
    }
    // The address Asterisk's ICE host candidate carries. Not SERVER_ADDR: behind
    // the 443 nginx multiplexer that is 127.0.0.1 and the mapping never matched.
    $local_ip = trim(getSystemSetting('server_ip', ''));
    if ($local_ip === '') {
        $local_ip = rtpPrimaryIp();
    }
    $stun_port = defined('STUN_PORT') && STUN_PORT !== '' ? STUN_PORT : '3478';

    $conf  = "; RTP Configuration (Auto-generated by AI PBX)\n";
    $conf .= "; Generated by the portal — manual edits are LOST on the next\n";
    $conf .= "; Apply. Use the RTP section of the PBX settings instead.\n";
    $conf .= "\n[general]\n";
    $conf .= "rtpstart={$start}\n";
    $conf .= "rtpend={$end}\n";
    $conf .= "strictrtp={$strict}\n";
    $conf .= "probation=8\n";
    $conf .= "rtptimeout=60\n";
    $conf .= "rtpholdtimeout=300\n";
    $conf .= "tos=ef\n";
    $conf .= "cos=6\n";
    if ($local_ip !== '') {
        // stunaddr is OFF BY DEFAULT (2026-09-05).
        //
        // MEASURED: with this line on, Asterisk sent a STUN Binding request to
        // the STUN address (3478) while setting up every RTP session and timed
        // out 3 times (3 seconds apart) — so every WebRTC call was BLOCKED for
        // ~6 seconds:
        //   09:16:40 Attempt 1 ... 09:16:43 Attempt 2 ... 09:16:46 Attempt 3
        //   09:16:46 the dialplan starts running
        // User symptom: "calling from the web starts 4-5 s late, 30 s on
        // mobile".
        //
        // The server side is FINE: a STUN query to the same address from a
        // plain socket (from the RTP port range too) is answered in 0.00 s and
        // the firewall allows 3478/udp. The problem is on the Asterisk side:
        // in WebRTC/ICE sessions pjproject's ICE stack owns the socket, and the
        // incoming STUN reply never reaches stun.c's blocking read.
        //
        // What NAT mapping needs is already `ice_host_candidates` below — it
        // works STATICALLY, without any network query. stunaddr was redundant.
        //
        // It can still be turned on by setting `rtp_stunaddr_enabled` to '1'
        // if needed (e.g. for pure SIP installs without ICE).
        if (getSystemSetting('rtp_stunaddr_enabled', '0') === '1') {
            $conf .= "stunaddr={$local_ip}:{$stun_port}\n";
        }
    }

    // NAT: advertise the public address for the server's own one. This is a
    // section of its own — written as "ice_host_candidates=" under [general]
    // Asterisk silently ignored it, so remote WebRTC clients (mobile data,
    // other networks) only got private addresses and had no audio.
    // include_local_address keeps the private candidate for LAN clients.
    if ($local_ip !== '' && filter_var($extern_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) && $extern_ip !== $local_ip) {
        $conf .= "\n[ice_host_candidates]\n";
        $conf .= "include_local_address=yes\n";
        $conf .= "{$local_ip} => {$extern_ip}\n";
    }

    return $conf;
}

/** Primary IPv4 of this server: the source address of the default route. */
function rtpPrimaryIp(): string
{
    $out = (string) @shell_exec('ip -4 route get 1.1.1.1 2>/dev/null');
    if (preg_match('/\bsrc\s+(\d+\.\d+\.\d+\.\d+)/', $out, $m)) {
        return $m[1];
    }
    $first = trim(explode(' ', trim((string) @shell_exec('hostname -I 2>/dev/null')))[0]);
    return filter_var($first, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) ? $first : '';
}

function __syncRtpSettingsBody()
{
    $conf = buildRtpConf();

    // Keep the current content: restore it if the reload fails.
    $onceki = is_readable(RTP_CONF_PATH) ? file_get_contents(RTP_CONF_PATH) : null;

    if (!FileHelper::writeFile(RTP_CONF_PATH, $conf, 'asterisk', 'asterisk', 0644)) {
        throw new \Exception('rtp.conf yazılamadı (izin/sahiplik?)');
    }

    try {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadRTP()], 'RTP ayarları');
    } catch (\Exception $e) {
        if ($onceki !== null && FileHelper::writeFile(RTP_CONF_PATH, $onceki, 'asterisk', 'asterisk', 0644)) {
            AsteriskHelper::reloadRTP();
            throw new \Exception('RTP ayarları uygulanamadı, ÖNCEKİ HÂLE OTOMATİK GERİ ALINDI: ' . $e->getMessage());
        }
        throw new \Exception('RTP ayarları uygulanamadı ve GERİ ALINAMADI, ELLE MÜDAHALE GEREKİYOR: ' . $e->getMessage());
    }

    return true;
}
