<?php
/**
 * Sync General Dialplan (/etc/asterisk/pbx/extensions_general.conf)
 */
require_once __DIR__ . '/DialplanBuilders.php';
require_once dirname(__DIR__) . '/services/LampService.php';

function syncGeneralDialplan() {
    return withSyncLock('general_dialplan', '__syncGeneralDialplanBody');
}

function __syncGeneralDialplanBody() {
    $db = getDB();
    // Fax users (extension_type='fax') have no PJSIP registration at all —
    // they are not part of the extension-to-extension (direct dial) list.
    $active_exts = $db->query("SELECT extension, full_name FROM sys_users WHERE extension IS NOT NULL AND extension != '' AND is_active = 1 AND extension_type = 'sip'")->fetchAll();
    $internal_dial_timeout = intval(getSystemSetting('pjsip_internal_dial_timeout', '30'));

    $conf = "; Native General PBX Dialplan Contexts (Auto-generated by AI PBX)\n\n";

    // Internal calls and hints live in the SHARED context; the outbound route
    // set is NOT included here. That way every group shares the same internal
    // plan and gets only its own outbound routes.
    $conf .= "[from-internal-pbx-ortak]\n";
    $conf .= "; Internal Extension-to-Extension Direct Calling\n";

    // Boss - secretary groups
    $bs_groups = [];
    try {
        $bs_stmt = $db->query("SELECT * FROM pbx_boss_secretary_groups WHERE is_active = 1");
        foreach ($bs_stmt->fetchAll(PDO::FETCH_ASSOC) as $bg) {
            $boss_ext = trim($bg['boss_extension']);
            if ($boss_ext !== '') {
                $bs_groups[$boss_ext] = $bg;
            }
        }
    } catch (\Exception $e) {
        $bs_groups = [];
    }

    if (!empty($active_exts)) {
        foreach ($active_exts as $e) {
            $ext = trim($e['extension']);
            $name = toCleanAscii($e['full_name']);
            // Without a hint, the device state of a queue member
            // "Local/{$ext}@from-internal-pbx" calling this extension ALWAYS
            // looked "Not in use" (idle/available) — the device state of a
            // Local channel never reflects the real PJSIP registration/call
            // state unless the target extension has a hint. Result: an
            // extension with its phone off/unregistered kept looking "online"
            // in the queue and on the supervisor screen.
            // BLF lamps for do-not-disturb, call forwarding and queue login
            // (LampService sets the custom device states). A desk phone key
            // with the value DND1001 / CF1001 / QUEUE1001 shows the lamp;
            // pressing it toggles (only the extension's own phone may).
            foreach (LampService::KINDS as $kind) {
                $conf .= "exten => {$kind}{$ext},hint,Custom:{$kind}{$ext}\n";
                $conf .= "exten => {$kind}{$ext},1,Gosub(aipbx-lamp-toggle,s,1(" . strtolower($kind) . ",{$ext}))\n";
                $conf .= " same => n,Hangup()\n";
            }
            $conf .= "exten => {$ext},hint,PJSIP/{$ext}-sip&PJSIP/{$ext}-webrtc&PJSIP/{$ext}-mob-webrtc\n";
            $conf .= "exten => {$ext},1,NoOp(Direct Call to Extension {$ext} - {$name})\n";
            $conf .= " same => n,Set(CDR(direction)=internal)\n";

            // Boss - secretary check: if this extension is an active boss, the secretary filter applies
            if (isset($bs_groups[$ext])) {
                $bg = $bs_groups[$ext];
                $secs = json_decode($bg['secretaries_json'] ?? '[]', true) ?: [];
                $whitelist = array_filter(array_map('trim', explode(',', $bg['whitelist_extensions'] ?? '')));
                $allowed = array_unique(array_merge([$ext], $secs, $whitelist));

                $condParts = [];
                foreach ($allowed as $ac) {
                    $ac_clean = preg_replace('/[^0-9]/', '', $ac);
                    if ($ac_clean !== '') {
                        $condParts[] = "\"\${CALLERID(num)}\" = \"{$ac_clean}\"";
                    }
                }
                if (!empty($condParts)) {
                    $conf .= " same => n,GotoIf(\$[" . implode(' | ', $condParts) . "]?allow_boss_{$ext})\n";
                }

                $conf .= " same => n,NoOp(Boss {$ext} called, caller not allowed -> ringing the secretary)\n";
                $sec_channels = [];
                foreach ($secs as $s_ext) {
                    $s_clean = preg_replace('/[^0-9]/', '', $s_ext);
                    if ($s_clean !== '') {
                        $sec_channels[] = "Local/{$s_clean}@from-internal-pbx-ortak/n";
                    }
                }

                $bg_timeout = max(5, min(120, intval($bg['ring_timeout'] ?: 20)));
                $bg_strategy = $bg['ring_strategy'] ?? 'ringall';

                if (!empty($sec_channels)) {
                    if ($bg_strategy === 'sequential') {
                        $sec_step = max(5, intval($bg_timeout / max(1, count($sec_channels))));
                        foreach ($sec_channels as $sc) {
                            $conf .= " same => n,Dial({$sc},{$sec_step},tT)\n";
                            $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?sec_ans_{$ext})\n";
                        }
                    } else {
                        $sec_dial_str = implode('&', $sec_channels);
                        $conf .= " same => n,Dial({$sec_dial_str},{$bg_timeout},tT)\n";
                        $conf .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?sec_ans_{$ext})\n";
                    }
                }

                $conf .= " same => n,NoOp(Secretary did not answer -> fallback)\n";
                $conf .= buildDestinationLines($bg['fallback_dest_type'] ?? 'hangup', $bg['fallback_dest_id'] ?? 'busy') . "\n";
                $conf .= " same => n(sec_ans_{$ext}),Hangup()\n";
                $conf .= " same => n(allow_boss_{$ext}),NoOp(Caller allowed to reach the boss)\n";
            }

            $extDial = buildExtensionDialLines($ext, $db, 'direct');
            $conf .= implode("\n", $extDial['lines']) . "\n";
        }
    } else {
        $conf .= "exten => _3XXX,1,NoOp(Internal Call to PJSIP Extension \${EXTEN})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";
        $conf .= " same => n,Set(C_SIP=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-sip)})\n";
        $conf .= " same => n,Set(C_WEB=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-webrtc)})\n";
        $conf .= " same => n,Set(C_MOB=\${PJSIP_DIAL_CONTACTS(\${EXTEN}-mob-webrtc)})\n";
        $conf .= " same => n,Set(DIAL_CONTACTS=\${C_SIP}\${IF(\$[\"\${C_SIP}\" != \"\" & \"\${C_WEB}\" != \"\"]?&)}\${C_WEB})\n";
        $conf .= " same => n,Set(DIAL_CONTACTS=\${DIAL_CONTACTS}\${IF(\$[\"\${DIAL_CONTACTS}\" != \"\" & \"\${C_MOB}\" != \"\"]?&)}\${C_MOB})\n";
        $conf .= " same => n,GotoIf(\$[\"\${DIAL_CONTACTS}\" = \"\"]?unavail)\n";
        $conf .= " same => n,Dial(\${DIAL_CONTACTS},{$internal_dial_timeout},tT)\n";
        $conf .= " same => n,Hangup()\n";
        $conf .= " same => n(unavail),NoOp(No registered contacts for \${EXTEN})\n";
        $conf .= " same => n,Hangup()\n";
    }

    // Default context: shared internal plan + group 1 outbound routes.
    // All existing endpoints and the Local/...@from-internal-pbx calls in the
    // queues are bound here, so its name and behaviour do not change.
    // Destinations given a number in the panel (IVR/queue/time condition/
    // announcement/call ending). Generated in a separate file
    // (SyncInternalNumbers.php) — so this big file is not rewritten when a
    // new number is added.
    // The include is searched after the shared context's OWN extensions:
    // a real extension number always wins.
    $conf .= "include => internal-numbers-pbx\n";

    $conf .= "\n; Default (group 1) — internal + outbound routes\n";
    $conf .= "[from-internal-pbx]\n";
    $conf .= "include => from-internal-pbx-ortak\n";
    $conf .= "include => from-internal-outbound-1\n";
    $conf .= "include => featurecodes-pbx\n\n";

    // Outbound route groups.
    //
    // [from-internal-pbx] uses group 1 (the include above). A separate context
    // is generated for users in other groups: internal calls and feature
    // codes work the same, only the outbound route set changes.
    //
    // Why it is built this way: group 1 stays untouched, so nothing changes
    // on installs without groups or for the Local/...@from-internal-pbx calls
    // in the queues.
    $gruplar = getDB()->query(
        "SELECT DISTINCT route_group FROM pbx_outbound_routes WHERE is_active = 1 AND route_group <> 1 ORDER BY route_group"
    )->fetchAll(PDO::FETCH_COLUMN);

    foreach ($gruplar as $g) {
        $g = intval($g);
        if ($g <= 1) continue;
        $conf .= "; Users of outbound route group {$g}\n";
        $conf .= "[from-internal-g{$g}]\n";
        $conf .= "include => from-internal-pbx-ortak\n";
        $conf .= "include => from-internal-outbound-{$g}\n";
        $conf .= "include => featurecodes-pbx\n\n";
    }

    $conf .= "; AMI Originate Context for Web Dialer & Header Softphone\n";
    $conf .= "[cc-internal]\n";
    $conf .= "include => from-internal-pbx\n\n";

    // Native Incoming FAX Context
    $conf .= "; Native Incoming FAX Context\n";
    $conf .= "[from-trunk-fax]\n";
    $conf .= "exten => _X!,1,NoOp(Incoming FAX processing for \${EXTEN} from \${CALLERID(num)})\n";
    // The channel must be answered EXPLICITLY and the media path given time to settle.
    //
    // There was no Answer() here; ReceiveFAX tried to answer the channel
    // itself and failed:
    //     WARNING res_fax.c: Channel 'PJSIP/<trunk>-...' failed answer attempt.
    // Result: every incoming fax ended with Status=FAILED, Pages=0 (all 78
    // calls on 2026-09-01). Wait(1) gives the audio path time to come up
    // between answering and starting to listen for the fax tone — if the
    // first second of the tone is missed, negotiation never starts.
    $conf .= " same => n,Answer()\n";
    $conf .= " same => n,Wait(1)\n";
    $conf .= " same => n,StopPlaytones()\n";
    $conf .= " same => n,Set(FAXOPT(ecm)=no)\n";
    $conf .= " same => n,Set(FAXOPT(modem)=v29,v27)\n";
    $conf .= " same => n,Set(FAXOPT(maxrate)=9600)\n";
    $conf .= " same => n,Set(FAXOPT(minrate)=2400)\n";
    // UNIQUEID is added: if a 2nd call from the same CALLERID came in the same
    // second, FAX_ID (STRFTIME+CALLERID alone) could collide and overwrite the file.
    // CALLERID(num) is FILTERED: FAX_FILE goes to /bin/sh inside double quotes
    // via System() below; a number like "$(command)" from the outside line
    // (valid in the SIP URI user part) used to run as a command.
    $conf .= " same => n,Set(FAX_ID=\${STRFTIME(\${EPOCH},,%Y%m%d_%H%M%S)}_\${FILTER(0-9+,\${CALLERID(num)})}_\${UNIQUEID})\n";
    $conf .= " same => n,Set(FAX_FILE=/var/spool/asterisk/fax/\${FAX_ID}.tif)\n";
    // The `df` option: `d` (fax debug log) + `f` (on T.38-capable channels, allow
    // automatic fallback to voice band/G.711 when negotiation fails).
    $conf .= " same => n,ReceiveFAX(\${FAX_FILE},df)\n";
    $conf .= " same => n,Hangup()\n\n";
    $conf .= "exten => h,1,NoOp(FAX Receive Completed: Status=\${FAXOPT(status)}, Pages=\${FAXOPT(pages)})\n";
    $conf .= " same => n,Set(FAX_CNUM=\${FILTER(0-9+,\${CALLERID(num)})})\n";
    $conf .= " same => n,Set(FAX_DID=\${FILTER(0-9+,\${IF(\$[\"\${CDR(did)}\" != \"\"]?\${CDR(did)}:\${EXTEN})})})\n";
    $conf .= " same => n,ExecIf(\$[\"\${FAX_FILE}\" != \"\"]?System(/usr/local/bin/process_incoming_fax.sh \"\${FAX_FILE}\" \"\${FAX_DID}\" \"\${FAX_CNUM}\" \"\${FAXOPT(pages)}\" \"\${FAXOPT(status)}\"))\n";

    $fax_header_info = toCleanAscii(getSystemSetting('fax_header_info', 'AI PBX Fax Server'));
    $fax_station_id = toCleanAscii(getSystemSetting('fax_local_station_id', 'AiPBX'));

    $conf .= "\n; Native Outgoing FAX Context (SendFAX via Call Files)\n";
    $conf .= "[outbound-fax]\n";
    $conf .= "exten => s,1,NoOp(Sending Outbound FAX to \${FAX_DEST} from \${FAX_SENDER})\n";
    // The sender name arrives in the call file as SetVar: FAX_SENDER_NAME (fax_send.php);
    // when empty (e.g. an old/hand-made .call file) only the global header is used.
    $conf .= " same => n,Set(FAXOPT(headerinfo)={$fax_header_info}\${IF(\$[\"\${FAX_SENDER_NAME}\" != \"\"]?\" - \"\${FAX_SENDER_NAME}:)})\n";
    // TSID = global prefix + the sending fax user's extension (FAX_SENDER, already
    // set in the .call file by fax_send.php) — e.g. prefix 0312555 + extension
    // 1234 = 03125551234 (2026-08-31, user request).
    $conf .= " same => n,Set(FAXOPT(localstationid)={$fax_station_id}\${FAX_SENDER})\n";
    $conf .= " same => n,SendFAX(\${FAX_TIF_PATH},d,f)\n";
    $conf .= " same => n,Hangup()\n\n";
    $conf .= "exten => h,1,NoOp(Outbound FAX Completed. Status=\${FAXOPT(status)})\n";
    $conf .= " same => n,System(/usr/local/bin/process_outgoing_fax_result.sh \"\${FAX_ID}\" \"\${FAXOPT(status)}\" \"\${FAXOPT(error)}\" \"\${FAXOPT(pages)}\")\n\n";

    // Pressing a DND / CF / QUEUE lamp key (see the hints above). ARG1 = kind,
    // ARG2 = extension. Only the extension's own devices may switch it.
    $conf .= "; BLF lamp keys: toggle do-not-disturb, cancel call forwarding, queue login/logout\n";
    $conf .= "[aipbx-lamp-toggle]\n";
    $conf .= "exten => s,1,NoOp(Lamp key \${ARG1} for \${ARG2} pressed on \${CHANNEL(endpoint)})\n";
    $conf .= " same => n,Answer()\n";
    $conf .= " same => n,GotoIf(\$[\"\${CUT(CHANNEL(endpoint),-,1)}\" != \"\${ARG2}\"]?deny)\n";
    $conf .= " same => n,GotoIf(\$[\"\${ARG1}\" = \"dnd\"]?dnd)\n";
    $conf .= " same => n,GotoIf(\$[\"\${ARG1}\" = \"cf\"]?cf)\n";
    $conf .= " same => n,GotoIf(\$[\"\${DEVICE_STATE(Custom:QUEUE\${ARG2})}\" = \"INUSE\"]?qout)\n";
    $conf .= " same => n,System(/usr/local/bin/feature_code_action.php queue_login \${ARG2} all &)\n";
    $conf .= " same => n,Goto(done)\n";
    $conf .= " same => n(qout),System(/usr/local/bin/feature_code_action.php queue_logout \${ARG2} all &)\n";
    $conf .= " same => n,Goto(done)\n";
    $conf .= " same => n(dnd),System(/usr/local/bin/feature_code_action.php dnd_toggle \${ARG2} &)\n";
    $conf .= " same => n,Goto(done)\n";
    // Forwarding needs a number, so the key can only cancel it (set it with *72 or in My Phone).
    $conf .= " same => n(cf),GotoIf(\$[\"\${DEVICE_STATE(Custom:CF\${ARG2})}\" != \"INUSE\"]?deny)\n";
    $conf .= " same => n,System(/usr/local/bin/feature_code_action.php cf_cancel \${ARG2} &)\n";
    $conf .= " same => n(done),Playback(beep)\n";
    $conf .= " same => n,Return()\n";
    $conf .= " same => n(deny),Playback(beep)\n";
    $conf .= " same => n,Wait(0.2)\n";
    $conf .= " same => n,Playback(beep)\n";
    $conf .= " same => n,Return()\n\n";

    // Enterprise Adaptive Jitter Buffer (AJB) Subroutine for Callee Channels
    $conf .= "; Enterprise Adaptive Jitter Buffer (AJB) Subroutine for Callee Channels\n";
    $conf .= "[sub-callee-jb]\n";
    $conf .= "exten => s,1,NoOp(Applying Adaptive Jitter Buffer to Callee Channel \${CHANNEL})\n";
    $conf .= " same => n,Set(JITTERBUFFER(adaptive)=default)\n";
    $conf .= " same => n,Return()\n\n";

    $ok = writeConfWithRollback('extensions_general.conf', $conf, function() {
        AsteriskHelper::assertReloadsOk([AsteriskHelper::reloadDialplan()], t('sync.ctx_general'));
    }, t('sync.ctx_general'));
    // DND / forwarding may have changed (My Phone, mobile app, feature codes).
    LampService::refresh();
    return $ok;
}
