<?php
/**
 * Dahili Hedef Numaraları Dialplan Üreteci
 * (/etc/asterisk/pbx/extensions_internalnumbers.conf)
 *
 * IVR / kuyruk / zaman koşulu / anons / çağrı sonlandırma tanımlarına panelden
 * verilen isteğe bağlı numaraları tek bir context'e yazar. Numaranın hedefe
 * nasıl çevrileceğini BU DOSYA BİLMEZ — buildDestinationLines() zaten gelen
 * rota ve IVR tuşları için aynı işi yapıyor, burada aynen o çağrılıyor.
 * Böylece "kuyruğa girerken kayıt başlat", "kuyruk dili", "fallback" gibi
 * davranışlar tek yerde tanımlı kalıyor.
 *
 * Context [from-internal-pbx-ortak] tarafından include ediliyor
 * (bkz. SyncGeneralDialplan.php). Asterisk bir context'in KENDİ
 * extension'larını include'lardan önce aradığı için gerçek bir dahili
 * numarası her zaman bu listeyi gölgeler — istenen davranış budur.
 */

require_once __DIR__ . '/DialplanBuilders.php';
require_once __DIR__ . '/../internal_numbers.php';

function syncInternalNumbers()
{
    return withSyncLock('internal_numbers', '__syncInternalNumbersBody');
}

/**
 * Bu hedef dahiliden arandığında kanalın cevaplanması gerekiyor mu?
 *
 * Yalnızca gerçekten bir ses dosyası çalınacaksa true döner. Ayrıntılı
 * gerekçe buildInternalNumbersConf()'un başlığındaki yorumda.
 */
function internalNumberNeedsAnswer(string $destType, string $destId): bool
{
    if ($destType === 'announcement') {
        return true;
    }

    if ($destType === 'hangup') {
        $st = getDB()->prepare(
            "SELECT anc.audio_file
               FROM pbx_hangup_actions ha
               JOIN pbx_announcements anc ON anc.id = ha.announcement_id AND anc.is_active = 1
              WHERE ha.action_key = ? AND ha.is_active = 1
              LIMIT 1"
        );
        $st->execute([$destId]);
        return !empty($st->fetchColumn());
    }

    return false;
}

/**
 * Saf üreteç — DB'ye dokunmaz, diske yazmaz, test edilebilir.
 *
 * Aynı numara iki farklı varlıkta tanımlıysa (uygulama katmanı bunu
 * engelliyor ama veri elle bozulmuş olabilir) İLK tanım kazanır ve ikincisi
 * atlanır: aynı exten'i iki kez yazmak Asterisk reload'ında
 * "extension already in use" uyarısı üretir ve dosyanın tamamını riske atar.
 *
 * Answer() YALNIZCA gerçekten ses dosyası çalacak hedeflere eklenir
 * (bkz. internalNumberNeedsAnswer). Gerekçe üç yönlü:
 *  - Anons: dahiliden arandığında kanal cevaplanmamış durumda Playback'e
 *    girer; erken medya her uçta çalmaz. Answer()+Wait(1) FreePBX'in
 *    app-announcement deseninin aynısı.
 *  - Çağrı sonlandırma: anonsu OLMAYAN bir tanımda Answer() ZARARLI olurdu —
 *    cevaplanmamış kanalda Busy() temiz bir SIP 486 gönderir ve telefon
 *    "meşgul" gösterir; cevaplanmış kanalda ise 10 saniye bant içi ton çalar.
 *    Bu yüzden yalnızca announcement_id dolu tanımlarda cevaplanır.
 *  - Kuyruk ve IVR: hiç eklenmez. Queue() öncesi cevaplama, arayan kuyrukta
 *    beklerken vazgeçse bile çağrıyı CDR'da "cevaplandı" yapar ve çağrı
 *    merkezi raporlarını bozar; IVR bloğu zaten kendi Answer()'ını çağırıyor
 *    (bkz. SyncIVRs.php buildIVRDialplanBlock).
 *
 * @param array $entries internalNumberEntries() çıktısı
 */
function buildInternalNumbersConf(array $entries): string
{
    $conf  = "; Dahili Hedef Numaralari (Auto-generated by AI PBX)\n";
    $conf .= "; Kaynak: pbx_*.internal_number kolonlari - bkz. src/internal_numbers.php\n\n";
    $conf .= "[internal-numbers-pbx]\n";

    if (empty($entries)) {
        $conf .= "; (tanimli dahili hedef numarasi yok)\n";
        return $conf;
    }

    $gorulen = [];
    foreach ($entries as $e) {
        $num = preg_replace('/[^0-9]/', '', (string) $e['number']);
        if ($num === '' || isset($gorulen[$num])) continue;
        $gorulen[$num] = true;

        $label = toCleanAscii((string) $e['label']);
        $conf .= "\n; " . $e['dest_type'] . " #" . $e['dest_id'] . " ({$label})\n";
        $conf .= "exten => {$num},1,NoOp(Dahili hedef {$num} -> " . $e['dest_type'] . "/" . $e['dest_id'] . " - {$label})\n";
        $conf .= " same => n,Set(CDR(direction)=internal)\n";
        if (internalNumberNeedsAnswer($e['dest_type'], $e['dest_id'])) {
            $conf .= " same => n,Answer()\n";
            $conf .= " same => n,Wait(1)\n";
        }
        $conf .= buildDestinationLines($e['dest_type'], $e['dest_id']) . "\n";
    }

    return $conf;
}

function __syncInternalNumbersBody()
{
    $conf = buildInternalNumbersConf(internalNumberEntries());

    return writeConfWithRollback('extensions_internalnumbers.conf', $conf, function () {
        AsteriskHelper::assertReloadsOk(
            [AsteriskHelper::reloadDialplan()],
            'Dahili hedef numarasi senkronizasyonu'
        );
    }, 'Dahili hedef numarasi senkronizasyonu');
}
