<?php
require_once __DIR__ . '/PhoneTemplate.php';

/**
 * Cisco SPA3xx/5xx: the Linksys-style XML profile (<flat-profile>, one
 * element per setting, Name_With_Underscores_<n>_). The phone asks for the
 * file named in its Profile Rule; set it to the copied URL followed by
 * spa$MA.xml, i.e. spa<mac>.xml.
 *
 * Keys: the line keys use Extension_<n>_ / Short_Name_<n>_ /
 * Extended_Function_<n>_, the SPA500S modules Unit_<m>_Key_<k>_.
 */
final class CiscoSpaTemplate extends PhoneTemplate
{
    private const CODECS = ['g722' => 'G722', 'pcma' => 'G711a', 'pcmu' => 'G711u', 'g729' => 'G729a'];

    private const LANGUAGES = [
        'en' => 'English', 'de' => 'German', 'fr' => 'French', 'es' => 'Spanish', 'it' => 'Italian',
        'pt' => 'Portuguese', 'nl' => 'Dutch', 'ru' => 'Russian', 'tr' => 'Turkish',
    ];

    public function vendor(): string
    {
        return 'cisco';
    }

    public function macFromFile(string $file): string
    {
        return preg_match('/^spa([0-9a-f]{12})\.(?:xml|cfg)$/i', $file, $m) ? PhoneModels::normalizeMac($m[1]) : '';
    }

    public function deviceFile(string $mac): string
    {
        return 'spa' . $mac . '.xml';
    }

    public function contentType(): string
    {
        return 'application/xml; charset=utf-8';
    }

    public function notifyResync(): string
    {
        return 'sipura-check-cfg';
    }

    public function notifyReboot(): string
    {
        return 'linksys-cold-restart';
    }

    public function render(array $ctx): string
    {
        $tls = $ctx['transport'] === 'tls';
        $p = [
            'Line_Enable_1_' => 'Yes',
            'Display_Name_1_' => self::xml($ctx['display_name']),
            'User_ID_1_' => self::xml($ctx['extension']),
            'Password_1_' => self::xml($ctx['sip_password'], 128),
            'Use_Auth_ID_1_' => 'Yes',
            'Auth_ID_1_' => self::xml($ctx['extension']),
            'Proxy_1_' => self::xml($ctx['server'], 255) . ':' . (int) $ctx['port'],
            'Register_1_' => 'Yes',
            'SIP_Transport_1_' => $tls ? 'TLS' : 'UDP',
            'Secure_Call_Setting_1_' => (int) $ctx['srtp'] > 0 ? 'Yes' : 'No',
            'Voice_Mail_Number' => self::xml($ctx['voicemail']),
            'Call_Pickup_Code' => self::xml($ctx['pickup_prefix']),
            'Primary_NTP_Server' => self::xml($ctx['ntp'], 255),
            'Time_Zone' => self::gmt((int) $ctx['utc_offset']),
            'Language_Selection' => self::LANGUAGES[$ctx['language']] ?? 'English',
            'Admin_Passwd' => self::xml($ctx['admin_password'], 128),
        ];

        $names = ['Preferred_Codec_1_', 'Second_Preferred_Codec_1_', 'Third_Preferred_Codec_1_'];
        foreach ($ctx['codecs'] as $c) {
            if (isset(self::CODECS[$c]) && $names !== []) {
                $p[array_shift($names)] = self::CODECS[$c];
            }
        }

        if (!empty($ctx['keys'])) {
            $model = PhoneModels::get($ctx['model']) ?? ['keys' => 0, 'exp_keys' => 0, 'exp_max' => 0];
            $phoneKeys = self::keysByPage($ctx['keys'], 0);
            for ($n = 1; $n <= $model['keys']; $n++) {
                $k = $phoneKeys[$n] ?? null;
                $line = $k !== null && $k['type'] === 'line';
                $p["Extension_{$n}_"] = $line ? '1' : 'Disabled';
                $p["Short_Name_{$n}_"] = $k !== null ? self::xml($k['label']) : '';
                $p["Extended_Function_{$n}_"] = $line ? '' : self::function($k);
            }
            for ($unit = 1; $unit <= ($model['exp_keys'] > 0 ? $model['exp_max'] : 0); $unit++) {
                $unitKeys = self::keysByPage($ctx['keys'], $unit);
                for ($n = 1; $n <= $model['exp_keys']; $n++) {
                    $p["Unit_{$unit}_Key_{$n}_"] = self::function($unitKeys[$n] ?? null);
                }
            }
        }

        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        $xml .= "<!-- Generated by AiPBX; changes made on the phone are overwritten at the next provisioning. -->\n";
        $xml .= "<flat-profile>\n";
        foreach ($p as $name => $value) {
            $xml .= "  <{$name} ua=\"na\">{$value}</{$name}>\n";
        }
        return $xml . "</flat-profile>\n";
    }

    /** Extended function string; $PROXY is filled in by the phone. */
    private static function function(?array $k): string
    {
        if ($k === null) {
            return '';
        }
        $t = self::xml($k['target']);
        // ; and = separate the fields of the function string.
        $name = self::xml(str_replace([';', '='], '', (string) $k['label']));
        return match ($k['type']) {
            'blf' => "fnc=blf+sd+cp;sub={$t}@\$PROXY;ext={$t}@\$PROXY;nme={$name}",
            'speeddial' => "fnc=sd;ext={$t}@\$PROXY;nme={$name}",
            'park' => "fnc=prk;sub={$t}@\$PROXY;nme={$name}",
            'dnd' => 'fnc=dnd',
            default => '',
        };
    }

    /** "GMT+03:00" */
    private static function gmt(int $minutes): string
    {
        $sign = $minutes < 0 ? '-' : '+';
        $abs = abs($minutes);
        return sprintf('GMT%s%02d:%02d', $sign, intdiv($abs, 60), $abs % 60);
    }
}
