<?php
require_once __DIR__ . '/PhoneTemplate.php';

/**
 * Grandstream GXP/GRP: cfg<mac>.xml (also asked as cfg<mac>) in the
 * gs_provision P-value format.
 *
 * Keys: the first seven multi-purpose keys use the long-standing P-values
 * (mode P323…P329, account/name/value P301…P321). Later keys and the
 * GXP2200EXT module have model- and firmware-specific P-values and are not
 * written yet (docs/phones.md).
 */
final class GrandstreamTemplate extends PhoneTemplate
{
    public const WRITTEN_KEYS = 7;

    /** MPK modes; dnd and line have no MPK mode and are skipped. */
    private const KEY_MODES = ['speeddial' => 0, 'blf' => 1, 'park' => 9];

    /** RTP payload numbers in P57…P62. */
    private const CODECS = ['pcmu' => 0, 'pcma' => 8, 'g722' => 9, 'g729' => 18, 'opus' => 123];

    public function vendor(): string
    {
        return 'grandstream';
    }

    public function macFromFile(string $file): string
    {
        return preg_match('/^cfg([0-9a-f]{12})(\.xml)?$/i', $file, $m) ? PhoneModels::normalizeMac($m[1]) : '';
    }

    public function deviceFile(string $mac): string
    {
        return 'cfg' . $mac . '.xml';
    }

    public function contentType(): string
    {
        return 'application/xml; charset=utf-8';
    }

    public function notifyResync(): string
    {
        return 'grandstream-check-cfg';
    }

    public function notifyReboot(): string
    {
        // Grandstream reboots after the check-sync download anyway.
        return '';
    }

    public function render(array $ctx): string
    {
        $tls = $ctx['transport'] === 'tls';
        $server = self::clean($ctx['server'], 255) . ':' . (int) $ctx['port'];
        $p = [
            'P271' => '1',                                     // account 1 active
            'P270' => self::clean($ctx['extension']),          // account name
            'P47' => $server,                                  // SIP server
            'P35' => self::clean($ctx['extension']),           // SIP user ID
            'P36' => self::clean($ctx['extension']),           // authenticate ID
            'P34' => self::clean($ctx['sip_password'], 128),   // authenticate password
            'P3' => self::clean($ctx['display_name']),         // display name
            'P33' => self::clean($ctx['voicemail']),           // voicemail access number
            'P130' => $tls ? '2' : '0',                        // transport: 0 UDP, 2 TLS
            'P183' => (string) (int) $ctx['srtp'],             // SRTP: 0 off, 1 optional, 2 forced
            'P30' => self::clean($ctx['ntp'], 255),            // NTP server
            'P64' => 'customize',                              // time zone: custom POSIX rule in P246
            'P246' => self::posixTz((int) $ctx['utc_offset']),
            'P1362' => self::clean($ctx['language'], 5),       // display language
            'P1347' => self::clean($ctx['pickup_prefix']),     // BLF call-pickup prefix
            'P2' => self::clean($ctx['admin_password'], 128),  // web admin password
        ];

        $slot = 57;
        foreach ($ctx['codecs'] as $codec) {
            if (isset(self::CODECS[$codec]) && $slot <= 62) {
                $p['P' . $slot++] = (string) self::CODECS[$codec];
            }
        }

        if (!empty($ctx['keys'])) {
            $keys = self::keysByPage($ctx['keys'], 0);
            for ($i = 0; $i < self::WRITTEN_KEYS; $i++) {
                $k = $keys[$i + 1] ?? null;
                $mode = $k !== null ? (self::KEY_MODES[$k['type']] ?? null) : null;
                $p['P' . (323 + $i)] = $mode === null ? '0' : (string) $mode;
                $p['P' . (301 + 3 * $i)] = '0';
                $p['P' . (302 + 3 * $i)] = $mode === null ? '' : self::clean($k['label']);
                $p['P' . (303 + 3 * $i)] = $mode === null ? '' : self::clean($k['target']);
            }
        }

        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        $xml .= "<!-- Generated by AiPBX; changes made on the phone are overwritten at the next provisioning. -->\n";
        $xml .= "<gs_provision version=\"1\">\n  <mac>" . $ctx['mac'] . "</mac>\n  <config version=\"1\">\n";
        foreach ($p as $name => $value) {
            $xml .= "    <{$name}>" . htmlspecialchars($value, ENT_XML1 | ENT_QUOTES, 'UTF-8') . "</{$name}>\n";
        }
        return $xml . "  </config>\n</gs_provision>\n";
    }

    /** POSIX TZ string for a fixed offset (POSIX counts west of UTC as positive). */
    private static function posixTz(int $minutes): string
    {
        $west = -$minutes;
        $sign = $west < 0 ? '-' : '';
        $abs = abs($west);
        $h = intdiv($abs, 60);
        $m = $abs % 60;
        return 'UTC' . $sign . $h . ($m ? ':' . str_pad((string) $m, 2, '0', STR_PAD_LEFT) : '');
    }
}
