<?php
require_once __DIR__ . '/PhoneTemplate.php';

/**
 * Poly VVX / Edge E (UC Software): the phone asks for its master file
 * <mac>.cfg (000000000000.cfg is the shared one, not served), whose
 * CONFIG_FILES names the settings file phone<mac>.cfg; both are answered.
 * The master file holds no secret.
 *
 * Keys use line key reassignment: lineKey.<n>.category / .index, BLF, speed
 * dial and park targets in attendant.resourceList.<m>. Keys are numbered
 * across the phone and its expansion modules (module keys follow the phone's).
 */
final class PolyTemplate extends PhoneTemplate
{
    /** codecPref names; 0 disables a codec. */
    private const CODECS = ['g722' => 'G722', 'pcma' => 'G711_A', 'pcmu' => 'G711_Mu', 'g729' => 'G729_AB', 'opus' => 'OPUS'];

    private const LANGUAGES = [
        'en' => 'English_United_Kingdom', 'tr' => 'Turkish_Turkey', 'de' => 'German_Germany', 'fr' => 'French_France',
        'es' => 'Spanish_Spain', 'it' => 'Italian_Italy', 'pt' => 'Portuguese_Portugal', 'ru' => 'Russian_Russia',
        'pl' => 'Polish_Poland', 'nl' => 'Dutch_Netherlands', 'sv' => 'Swedish_Sweden', 'da' => 'Danish_Denmark',
        'nb' => 'Norwegian_Norway', 'cs' => 'Czech_Czech_Republic',
    ];

    public function vendor(): string
    {
        return 'poly';
    }

    public function macFromFile(string $file): string
    {
        if (preg_match('/^0{12}\.cfg$/', $file)) {
            return '';
        }
        return preg_match('/^(?:phone)?([0-9a-f]{12})\.cfg$/i', $file, $m) ? PhoneModels::normalizeMac($m[1]) : '';
    }

    public function deviceFile(string $mac): string
    {
        return $mac . '.cfg';
    }

    public function contentType(): string
    {
        return 'application/xml; charset=utf-8';
    }

    public function notifyResync(): string
    {
        return 'polycom-check-cfg';
    }

    public function notifyReboot(): string
    {
        // The phone restarts by itself after check-sync when the settings need it.
        return '';
    }

    public function renderFile(string $file, array $ctx): string
    {
        return str_starts_with(strtolower($file), 'phone') ? $this->render($ctx) : self::master($ctx['mac']);
    }

    /** Master file: points the phone at its settings file next to it. */
    public static function master(string $mac): string
    {
        return "<?xml version=\"1.0\" standalone=\"yes\"?>\n"
            . "<!-- Generated by AiPBX -->\n"
            . "<APPLICATION APP_FILE_PATH=\"\" CONFIG_FILES=\"phone{$mac}.cfg\" MISC_FILES=\"\" LOG_FILE_DIRECTORY=\"\""
            . " OVERRIDES_DIRECTORY=\"\" CONTACTS_DIRECTORY=\"\" LICENSE_DIRECTORY=\"\" USER_PROFILES_DIRECTORY=\"\" CALL_LISTS_DIRECTORY=\"\"/>\n";
    }

    public function render(array $ctx): string
    {
        $tls = $ctx['transport'] === 'tls';
        $ext = self::xml($ctx['extension']);
        $a = [
            'reg.1.address' => $ext,
            'reg.1.label' => $ext,
            'reg.1.displayName' => self::xml($ctx['display_name']),
            'reg.1.auth.userId' => $ext,
            'reg.1.auth.password' => self::xml($ctx['sip_password'], 128),
            'reg.1.server.1.address' => self::xml($ctx['server'], 255),
            'reg.1.server.1.port' => (string) (int) $ctx['port'],
            'reg.1.server.1.transport' => $tls ? 'TLS' : 'UDPOnly',
            'sec.srtp.enable' => (int) $ctx['srtp'] > 0 ? '1' : '0',
            'sec.srtp.offer' => (int) $ctx['srtp'] > 0 ? '1' : '0',
            'sec.srtp.require' => (int) $ctx['srtp'] === 2 ? '1' : '0',
            'msg.mwi.1.subscribe' => $ext,
            'msg.mwi.1.callBackMode' => 'contact',
            'msg.mwi.1.callBack' => self::xml($ctx['voicemail']),
            'feature.directedCallPickup.enabled' => '1',
            'call.directedCallPickupString' => self::xml($ctx['pickup_prefix']),
            'tcpIpApp.sntp.address' => self::xml($ctx['ntp'], 255),
            'tcpIpApp.sntp.gmtOffset' => (string) ((int) $ctx['utc_offset'] * 60),
            'lcl.ml.lang' => self::LANGUAGES[$ctx['language']] ?? 'English_United_Kingdom',
            'device.set' => '1',
            'device.auth.localAdminPassword.set' => '1',
            'device.auth.localAdminPassword' => self::xml($ctx['admin_password'], 128),
        ];

        foreach (self::CODECS as $key => $name) {
            $pos = array_search($key, $ctx['codecs'], true);
            $a["voice.codecPref.{$name}"] = $pos === false ? '0' : (string) ($pos + 1);
        }

        if (!empty($ctx['keys'])) {
            $a['lineKey.reassignment.enabled'] = '1';
            $keys = self::keysFlat($ctx['keys'], $ctx['model']);
            $res = 0;
            for ($n = 1; $n <= self::totalKeys($ctx['model']); $n++) {
                $k = $keys[$n] ?? null;
                switch ($k['type'] ?? '') {
                    case 'line':
                        $a["lineKey.{$n}.category"] = 'Line';
                        $a["lineKey.{$n}.index"] = '1';
                        break;
                    case 'blf':
                    case 'speeddial':
                    case 'park':
                        $res++;
                        $a["attendant.resourceList.{$res}.address"] = self::xml($k['target']);
                        $a["attendant.resourceList.{$res}.label"] = self::xml($k['label']);
                        // normal = watched (BLF); automata = dialled without a lamp.
                        $a["attendant.resourceList.{$res}.type"] = $k['type'] === 'blf' ? 'normal' : 'automata';
                        $a["lineKey.{$n}.category"] = 'BLF';
                        $a["lineKey.{$n}.index"] = (string) $res;
                        break;
                    case 'dnd':
                        $a["lineKey.{$n}.category"] = 'DND';
                        $a["lineKey.{$n}.index"] = '0';
                        break;
                    default:
                        $a["lineKey.{$n}.category"] = 'Unassigned';
                        $a["lineKey.{$n}.index"] = '0';
                }
            }
        }

        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n";
        $xml .= "<!-- Generated by AiPBX; changes made on the phone are overwritten at the next provisioning. -->\n";
        $xml .= "<polycomConfig>\n  <aipbx\n";
        foreach ($a as $name => $value) {
            $xml .= "    {$name}=\"{$value}\"\n";
        }
        return $xml . "  />\n</polycomConfig>\n";
    }
}
