<?php
require_once __DIR__ . '/PhoneTemplate.php';

/**
 * Snom D3xx/D7xx: Snom's XML settings format (<settings><phone-settings> …
 * <functionKeys>). The phone asks for snom<model>-<MAC>.htm after plug and
 * play; with a settings server URL it asks for the name in that URL, e.g.
 * snom-<mac>.xml (both are answered).
 *
 * Function keys are numbered from 0 across the phone and its D7 expansion
 * modules: module keys follow the phone's own keys.
 */
final class SnomTemplate extends PhoneTemplate
{
    /** Snom codec names in codec_priority_list. */
    private const CODECS = ['g722' => 'g722', 'pcma' => 'pcma', 'pcmu' => 'pcmu', 'g729' => 'g729', 'opus' => 'opus'];

    private const LANGUAGES = [
        'en' => 'English', 'tr' => 'Turkce', 'de' => 'Deutsch', 'fr' => 'Francais', 'es' => 'Espanol',
        'it' => 'Italiano', 'nl' => 'Nederlands', 'pt' => 'Portugues', 'ru' => 'Russian', 'pl' => 'Polski',
        'cs' => 'Cestina', 'sv' => 'Svenska', 'da' => 'Dansk', 'fi' => 'Suomi', 'nb' => 'Norsk',
    ];

    public function vendor(): string
    {
        return 'snom';
    }

    public function macFromFile(string $file): string
    {
        return preg_match('/^snom(?:[a-z0-9]+)?-([0-9a-f]{12})\.(?:htm|xml)$/i', $file, $m) ? PhoneModels::normalizeMac($m[1]) : '';
    }

    public function deviceFile(string $mac): string
    {
        return 'snom-' . $mac . '.xml';
    }

    public function contentType(): string
    {
        return 'application/xml; charset=utf-8';
    }

    public function notifyResync(): string
    {
        return 'snom-check-cfg';
    }

    public function notifyReboot(): string
    {
        return 'snom-reboot';
    }

    public function render(array $ctx): string
    {
        $tls = $ctx['transport'] === 'tls';
        $server = self::xml($ctx['server'], 255);
        $codecs = [];
        foreach ($ctx['codecs'] as $c) {
            if (isset(self::CODECS[$c])) {
                $codecs[] = self::CODECS[$c];
            }
        }
        $srtp = ['off', 'optional', 'mandatory'][max(0, min(2, (int) $ctx['srtp']))];

        $s = [
            // Account 1
            ['user_active', 'on', 1],
            ['user_name', self::xml($ctx['extension']), 1],
            ['user_pname', self::xml($ctx['extension']), 1],
            ['user_pass', self::xml($ctx['sip_password'], 128), 1],
            ['user_realname', self::xml($ctx['display_name']), 1],
            ['user_host', $server, 1],
            ['user_outbound', $server . ':' . (int) $ctx['port'] . ';transport=' . ($tls ? 'tls' : 'udp'), 1],
            ['user_srtp', (int) $ctx['srtp'] > 0 ? 'on' : 'off', 1],
            ['user_savp', $srtp, 1],
            ['user_mailbox', self::xml($ctx['voicemail']), 1],
            ['codec_priority_list', implode(',', $codecs), 1],
            // Phone
            ['ntp_server', self::xml($ctx['ntp'], 255), null],
            ['utc_offset', (string) ((int) $ctx['utc_offset'] * 60), null],
            ['language', self::LANGUAGES[$ctx['language']] ?? 'English', null],
            ['web_language', self::LANGUAGES[$ctx['language']] ?? 'English', null],
            ['admin_mode_password', self::xml($ctx['admin_password'], 128), null],
            ['http_user', 'admin', null],
            ['http_pass', self::xml($ctx['admin_password'], 128), null],
        ];

        $xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
        $xml .= "<!-- Generated by AiPBX; changes made on the phone are overwritten at the next provisioning. -->\n";
        $xml .= "<settings>\n  <phone-settings e=\"2\">\n";
        foreach ($s as [$name, $value, $idx]) {
            $xml .= "    <{$name}" . ($idx !== null ? " idx=\"{$idx}\"" : '') . " perm=\"\">{$value}</{$name}>\n";
        }
        $xml .= "  </phone-settings>\n";

        if (!empty($ctx['keys'])) {
            $keys = self::keysFlat($ctx['keys'], $ctx['model']);
            $xml .= "  <functionKeys e=\"2\">\n";
            for ($n = 1; $n <= self::totalKeys($ctx['model']); $n++) {
                $k = $keys[$n] ?? null;
                $label = $k !== null ? self::xml($k['label']) : '';
                $xml .= '    <fkey idx="' . ($n - 1) . '" context="active" label="' . $label . '" perm="">'
                    . self::keyValue($k, $ctx) . "</fkey>\n";
            }
            $xml .= "  </functionKeys>\n";
        }
        return $xml . "</settings>\n";
    }

    /** Snom fkey value; a BLF key picks a ringing call up with the prefix after "|". */
    private static function keyValue(?array $k, array $ctx): string
    {
        if ($k === null) {
            return 'none';
        }
        $target = self::xml($k['target']);
        $server = self::xml($ctx['server'], 255);
        return match ($k['type']) {
            'blf' => "blf &lt;sip:{$target}@{$server}&gt;|" . self::xml($ctx['pickup_prefix']),
            'speeddial' => "speed {$target}",
            'park' => "orbit {$target}",
            'dnd' => 'keyevent F_DND',
            'line' => 'line',
            default => 'none',
        };
    }
}
