<?php
require_once __DIR__ . '/PhoneTemplate.php';

/**
 * Yealink T3x/T4x/T5x: <mac>.cfg (lowercase MAC) in Yealink's key = value
 * format. The shared y0000000000xx.cfg is not served: everything is in the
 * per-phone file.
 */
final class YealinkTemplate extends PhoneTemplate
{
    /** Yealink DSS key types. */
    private const KEY_TYPES = ['line' => 15, 'blf' => 16, 'speeddial' => 13, 'park' => 10, 'dnd' => 5];

    private const CODECS = ['pcmu', 'pcma', 'g722', 'g729', 'opus'];

    private const LANGUAGES = [
        'en' => 'English', 'tr' => 'Turkish', 'de' => 'German', 'fr' => 'French', 'es' => 'Spanish',
        'it' => 'Italian', 'pt' => 'Portuguese', 'ru' => 'Russian', 'pl' => 'Polish', 'nl' => 'Dutch',
        'cs' => 'Czech', 'sv' => 'Swedish', 'uk' => 'Ukrainian', 'hu' => 'Hungarian',
    ];

    public function vendor(): string
    {
        return 'yealink';
    }

    public function macFromFile(string $file): string
    {
        // y000000000028.cfg is the shared file, not a MAC.
        if (preg_match('/^y0{9}[0-9a-f]{3}\.cfg$/i', $file)) {
            return '';
        }
        return preg_match('/^([0-9a-f]{12})\.cfg$/i', $file, $m) ? PhoneModels::normalizeMac($m[1]) : '';
    }

    public function deviceFile(string $mac): string
    {
        return $mac . '.cfg';
    }

    public function contentType(): string
    {
        return 'text/plain; charset=utf-8';
    }

    public function notifyResync(): string
    {
        return 'yealink-check-cfg';
    }

    public function notifyReboot(): string
    {
        return 'yealink-reboot';
    }

    public function render(array $ctx): string
    {
        $tls = $ctx['transport'] === 'tls';
        $lines = [
            '#!version:1.0.0.1',
            '## Generated by AiPBX — changes made on the phone are overwritten at the next provisioning.',
            '',
            'account.1.enable = 1',
            'account.1.label = ' . self::clean($ctx['extension']),
            'account.1.display_name = ' . self::clean($ctx['display_name']),
            'account.1.auth_name = ' . self::clean($ctx['extension']),
            'account.1.user_name = ' . self::clean($ctx['extension']),
            'account.1.password = ' . self::clean($ctx['sip_password'], 128),
            'account.1.sip_server.1.address = ' . self::clean($ctx['server'], 255),
            'account.1.sip_server.1.port = ' . (int) $ctx['port'],
            'account.1.sip_server.1.transport_type = ' . ($tls ? 2 : 0),
            'account.1.srtp_encryption = ' . (int) $ctx['srtp'],
            'account.1.subscribe_mwi = 1',
            'voice_mail.number.1 = ' . self::clean($ctx['voicemail']),
        ];

        // Codecs: the chosen ones in order, the others off.
        $priority = 1;
        foreach (self::CODECS as $codec) {
            $pos = array_search($codec, $ctx['codecs'], true);
            $lines[] = "account.1.codec.{$codec}.enable = " . ($pos === false ? 0 : 1);
        }
        foreach ($ctx['codecs'] as $codec) {
            if (in_array($codec, self::CODECS, true)) {
                $lines[] = "account.1.codec.{$codec}.priority = " . $priority++;
            }
        }

        $lines[] = '';
        $lines[] = 'local_time.ntp_server1 = ' . self::clean($ctx['ntp'], 255);
        $lines[] = 'local_time.time_zone = ' . self::offsetHours((int) $ctx['utc_offset']);
        $lines[] = 'lang.gui = ' . (self::LANGUAGES[$ctx['language']] ?? 'English');
        $lines[] = 'lang.wui = ' . (self::LANGUAGES[$ctx['language']] ?? 'English');
        // Pressing a ringing BLF key picks the call up with *21<extension>.
        $lines[] = 'features.pickup.direct_pickup_enable = 1';
        $lines[] = 'features.pickup.direct_pickup_code = ' . self::clean($ctx['pickup_prefix']);
        $lines[] = 'static.security.user_password = admin:' . self::clean($ctx['admin_password'], 128);

        if (!empty($ctx['keys'])) {
            $lines[] = '';
            $model = PhoneModels::get($ctx['model']) ?? ['keys' => 0, 'exp_keys' => 0, 'exp_max' => 0];
            $lines = array_merge($lines, self::keyLines('linekey.%d', self::keysByPage($ctx['keys'], 0), $model['keys']));
            for ($page = 1; $page < PhoneModels::pageCount($ctx['model']); $page++) {
                $lines = array_merge($lines, self::keyLines("expansion_module.{$page}.key.%d", self::keysByPage($ctx['keys'], $page), $model['exp_keys']));
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Every key of a page: a defined one gets its type, an empty one is
     * cleared (type 0), so a key removed on the page disappears from the phone.
     */
    private static function keyLines(string $prefix, array $keys, int $count): array
    {
        $out = [];
        for ($pos = 1; $pos <= $count; $pos++) {
            $p = sprintf($prefix, $pos);
            $k = $keys[$pos] ?? null;
            if ($k === null || !isset(self::KEY_TYPES[$k['type']])) {
                $out[] = "{$p}.type = 0";
                continue;
            }
            $out[] = "{$p}.type = " . self::KEY_TYPES[$k['type']];
            $out[] = "{$p}.line = 1";
            $out[] = "{$p}.value = " . ($k['type'] === 'line' || $k['type'] === 'dnd' ? '' : self::clean($k['target']));
            $out[] = "{$p}.label = " . self::clean($k['label']);
        }
        return $out;
    }
}
