<?php
/**
 * AI → Applications: AI features that take calls, each with its own internal
 * number (dialled directly or chosen as a destination in IVRs, DIDs and time
 * conditions) and a destination after it. The dialplan is generated by
 * src/sync/SyncAiApps.php; the call itself is handled by the local AI service
 * (POST /v1/calls/start, then Asterisk AudioSocket to 127.0.0.1:8791).
 *
 * First type, "announcement": a text with values, spoken by a voice model of
 * this server. Values are {caller_number}, {caller_name}, {did} (filled by
 * Asterisk) and any {name} returned as JSON by the lookup URL (filled by the
 * service), e.g. {"amount": "1.234,50"} for "Your balance is {amount} lira".
 */

require_once dirname(__DIR__, 2) . '/helpers.php';
require_once dirname(__DIR__, 2) . '/asterisk_sync.php';
require_once dirname(__DIR__, 2) . '/internal_numbers.php';
require_once dirname(__DIR__) . '/LocalAiService.php';
require_once dirname(__DIR__) . '/ai/CloudAiService.php';

class AiAppService
{
    public const TYPES = ['announcement'];
    public const MAX_TEXT = 2000;
    /** Placeholders Asterisk fills itself (the rest come from the lookup URL). */
    public const DIALPLAN_VALUES = [
        'caller_number' => '${CALLERID(num)}',
        'caller_name' => '${CALLERID(name)}',
        'did' => '${CDR(did)}',
    ];

    public static function all(): array
    {
        return getDB()->query('SELECT * FROM pbx_ai_apps ORDER BY title ASC')->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function get(int $id): ?array
    {
        $st = getDB()->prepare('SELECT * FROM pbx_ai_apps WHERE id = ?');
        $st->execute([$id]);
        return $st->fetch(PDO::FETCH_ASSOC) ?: null;
    }

    /** Local voice models that can speak for an application (downloaded or running). */
    public static function voiceModels(): array
    {
        return array_values(array_filter(LocalAiService::models(),
            fn($m) => ($m['kind'] ?? '') === 'tts' && in_array($m['state'] ?? '', ['ready', 'installed', 'loading'], true)));
    }

    /** @return array<string, string> validated row */
    public static function validate(array $d, int $id = 0): array
    {
        $title = trim((string) ($d['title'] ?? ''));
        if ($title === '' || mb_strlen($title) > 100) {
            throw new \Exception(t('ai_apps.err_title'));
        }
        $type = (string) ($d['app_type'] ?? 'announcement');
        if (!in_array($type, self::TYPES, true)) {
            throw new \Exception(t('ai_apps.err_type'));
        }
        $model = (string) ($d['model_id'] ?? '');
        if (!preg_match('/^(engine:(tr|de|en)|[a-z0-9][a-z0-9._-]{1,63})$/', $model)) {
            throw new \Exception(t('ai_apps.err_model'));
        }
        $text = trim((string) ($d['text_template'] ?? ''));
        if ($text === '' || mb_strlen($text) > self::MAX_TEXT) {
            throw new \Exception(sprintf(t('ai_apps.err_text'), self::MAX_TEXT));
        }
        $fallback = trim((string) ($d['fallback_text'] ?? ''));
        if (mb_strlen($fallback) > self::MAX_TEXT) {
            throw new \Exception(sprintf(t('ai_apps.err_text'), self::MAX_TEXT));
        }
        $lookup = trim((string) ($d['lookup_url'] ?? ''));
        if ($lookup !== '' && (strlen($lookup) > 500 || !preg_match('#^https?://[^\s]+$#', $lookup) || !filter_var($lookup, FILTER_VALIDATE_URL))) {
            throw new \Exception(t('ai_apps.err_lookup'));
        }
        $destType = (string) ($d['dest_type'] ?? 'hangup');
        $destId = (string) ($d['dest_id'] ?? '');
        if (!preg_match('/^[a-z_]{2,30}$/', $destType) || mb_strlen($destId) > 64) {
            throw new \Exception(t('ai_apps.err_dest'));
        }
        if ($destType === 'ai_app' && (int) $destId === $id && $id > 0) {
            throw new \Exception(t('ai_apps.err_dest_self'));
        }
        $number = internalNumberSanitize($d['internal_number'] ?? '');
        return [
            'title' => $title, 'app_type' => $type, 'model_id' => $model,
            'speed' => (string) max(0.5, min(2.0, round((float) ($d['speed'] ?? 1), 2))),
            'text_template' => $text, 'lookup_url' => $lookup, 'fallback_text' => $fallback,
            'dest_type' => $destType, 'dest_id' => $destId,
            'max_concurrent' => (string) max(1, min(50, (int) ($d['max_concurrent'] ?? 4))),
            'internal_number' => $number, 'is_active' => !empty($d['is_active']) ? '1' : '0',
        ];
    }

    public static function save(array $d): int
    {
        $id = (int) ($d['id'] ?? 0);
        $v = self::validate($d, $id);
        $old = $id > 0 ? self::get($id) : null;
        if ($id > 0 && $old === null) {
            throw new \Exception(t('ai_apps.err_not_found'));
        }
        if ($v['internal_number'] !== '') {
            assertInternalNumberAvailable($v['internal_number'], 'ai_app', $id);
        }
        $db = getDB();
        $cols = ['title', 'app_type', 'model_id', 'speed', 'text_template', 'lookup_url', 'fallback_text', 'dest_type', 'dest_id', 'max_concurrent', 'is_active'];
        $vals = array_map(fn($c) => $v[$c], $cols);
        $cols[] = 'internal_number';
        $vals[] = $v['internal_number'] !== '' ? $v['internal_number'] : null;
        if ($id > 0) {
            $db->prepare('UPDATE pbx_ai_apps SET ' . implode(', ', array_map(fn($c) => "$c = ?", $cols)) . ' WHERE id = ?')
               ->execute([...$vals, $id]);
        } else {
            $db->prepare('INSERT INTO pbx_ai_apps (' . implode(', ', $cols) . ') VALUES (' . implode(', ', array_fill(0, count($cols), '?')) . ')')
               ->execute($vals);
            $id = (int) $db->lastInsertId();
        }
        $uid = $_SESSION['user_id'] ?? null;
        markPendingSync('ai_apps', 'ai_app', $id, 'AI application: ' . $v['title'], $old ? 'update' : 'create', $uid);
        if (($old['internal_number'] ?? '') !== ($v['internal_number'] !== '' ? $v['internal_number'] : null)) {
            markPendingSync('internal_numbers', 'ai_app', $id, 'AI application: ' . $v['title'], 'update', $uid);
        }
        return $id;
    }

    public static function delete(int $id): void
    {
        $app = self::get($id);
        if ($app === null) {
            return;
        }
        getDB()->prepare('DELETE FROM pbx_ai_apps WHERE id = ?')->execute([$id]);
        $uid = $_SESSION['user_id'] ?? null;
        markPendingSync('ai_apps', 'ai_app', $id, 'AI application: ' . $app['title'], 'delete', $uid);
        if (!empty($app['internal_number'])) {
            markPendingSync('internal_numbers', 'ai_app', $id, 'AI application: ' . $app['title'], 'delete', $uid);
        }
    }

    /** The voice model an application uses now ("engine:<lang>" follows AI → Cloud services). */
    public static function resolveModel(string $model): string
    {
        if (str_starts_with($model, 'engine:')) {
            $e = CloudAiService::engine('tts', substr($model, 7));
            return str_starts_with($e, 'local:') ? substr($e, 6) : '';
        }
        return $model;
    }

    /** The shared secret of /v1/calls/start (the dialplan cannot read the API token). */
    public static function dialplanKey(): string
    {
        $file = LocalAiService::tokenFile();
        $token = is_readable($file) ? trim((string) file_get_contents($file)) : '';
        return $token !== '' ? hash_hmac('sha256', 'aipbx-dialplan', $token) : '';
    }

    /**
     * A text for the CURL post body: everything URL-encoded in PHP except the
     * dialplan values, which Asterisk inserts with URIENCODE — so no comma,
     * semicolon or bracket of the text ever reaches the dialplan parser.
     */
    public static function dialplanEncode(string $text): string
    {
        $out = '';
        $parts = preg_split('/(\{(?:' . implode('|', array_keys(self::DIALPLAN_VALUES)) . ')\})/', $text, -1, PREG_SPLIT_DELIM_CAPTURE) ?: [$text];
        foreach ($parts as $p) {
            $key = trim($p, '{}');
            $out .= isset(self::DIALPLAN_VALUES[$key]) && $p === '{' . $key . '}'
                ? '${URIENCODE(' . self::DIALPLAN_VALUES[$key] . ')}'
                : rawurlencode($p);
        }
        return $out;
    }
}
